module
import Models.Main
#print axioms Models.Main.admission
#print axioms Models.Main.admitCosts
#print axioms Models.Main.admit_accepts_cheap
#print axioms Models.Main.admit_rejects_costly
#print axioms Models.Main.branchCode
#print axioms Models.Main.branchStep
#print axioms Models.Main.branch_refuses_precondition
#print axioms Models.Main.branch_takes_else
#print axioms Models.Main.branch_takes_then
#print axioms Models.Main.chainCode
#print axioms Models.Main.chainStep
#print axioms Models.Main.chain_accepts
#print axioms Models.Main.chain_refuses_precondition
#print axioms Models.Main.chain_refuses_stage_output
#print axioms Models.Main.classify
#print axioms Models.Main.classifyChecked
#print axioms Models.Main.classify_eight
#print axioms Models.Main.drainChainStep
#print axioms Models.Main.drain_chain_accepts
#print axioms Models.Main.drain_chain_refuses_postcondition
#print axioms Models.Main.flowCode
#print axioms Models.Main.flowStep
#print axioms Models.Main.flow_accepts
#print axioms Models.Main.flow_refuses_input
#print axioms Models.Main.flow_refuses_junction
#print axioms Models.Main.guessChecked
#print axioms Models.Main.guessOvershoot
#print axioms Models.Main.guessTwice
#print axioms Models.Main.guess_accepts
#print axioms Models.Main.guess_refuses_precondition
#print axioms Models.Main.ledgerFull
#print axioms Models.Main.ledgerPost
#print axioms Models.Main.ledger_accepts
#print axioms Models.Main.ledger_full_accepts
#print axioms Models.Main.ledger_full_refuses_output
#print axioms Models.Main.ledger_refuses_input
#print axioms Models.Main.ledger_refuses_output
#print axioms Models.Main.ledger_refuses_precondition
#print axioms Models.Main.overshootChecked
#print axioms Models.Main.overshoot_pair_refuses_postcondition
#print axioms Models.Main.overshoot_refuses_postcondition
#print axioms Models.Main.pairClamp
#print axioms Models.Main.pair_clamp_accepts
#print axioms Models.Main.pair_clamp_refuses_input
#print axioms Models.Main.quadCode
#print axioms Models.Main.rawChainStep
#print axioms Models.Main.raw_chain_accepts
#print axioms Models.Main.raw_chain_refuses_input
#print axioms Models.Main.raw_chain_refuses_precondition
#print axioms Models.Main.respond
#print axioms Models.Main.spillStream
#print axioms Models.Main.step
#print axioms Models.Main.stepCode
#print axioms Models.Main.streamCode
#print axioms Models.Main.stream_accepts
#print axioms Models.Main.stream_refuses_output
#print axioms Models.Main.twiceCode
#print axioms Models.Main.twice_accepts
#print axioms Models.Main.twice_refuses
#print axioms Models.Main.twinStep
#print axioms Models.Main.twin_accepts
#print axioms Models.Main.twin_refuses_input
#print axioms Models.Main.twin_refuses_precondition
#print axioms Models.Main.valueCode
