module
import Models.Recognizer
#print axioms Models.Recognizer.DigitContract.postcondition_complete
#print axioms Models.Recognizer.DigitContract.postcondition_sound
#print axioms Models.Recognizer.DigitEvidence.digit_net_correct
#print axioms Models.Recognizer.DigitEvidence.digit_net_exact
#print axioms Models.Recognizer.DigitEvidence.labeled_agreement
#print axioms Models.Recognizer.DigitModel
#print axioms Models.Recognizer.DigitNet
#print axioms Models.Recognizer.DigitNet.encoded
#print axioms Models.Recognizer.DigitNet.layer1
#print axioms Models.Recognizer.DigitNet.layer2
#print axioms Models.Recognizer.DigitNet.layer3
#print axioms Models.Recognizer.DigitNet.layer4
#print axioms Models.Recognizer.DigitNet.logits
#print axioms Models.Recognizer.RawDigitModel
#print axioms Models.Recognizer.Recognizes
#print axioms Models.Recognizer.banner
#print axioms Models.Recognizer.banner.bytes
#print axioms Models.Recognizer.banner.decoded
#print axioms Models.Recognizer.digitName
#print axioms Models.Recognizer.digitNames
#print axioms Models.Recognizer.digitNames.bytes
#print axioms Models.Recognizer.digitNames.decoded
#print axioms Models.Recognizer.digit_net_correct
#print axioms Models.Recognizer.digit_net_exact
#print axioms Models.Recognizer.digit_net_width
#print axioms Models.Recognizer.hiddenBias
#print axioms Models.Recognizer.hiddenBias.bytes
#print axioms Models.Recognizer.hiddenBias.decoded
#print axioms Models.Recognizer.hiddenWeights
#print axioms Models.Recognizer.hiddenWeights.bytes
#print axioms Models.Recognizer.hiddenWeights.decoded
#print axioms Models.Recognizer.labeledGlyphs
#print axioms Models.Recognizer.labeled_agreement
#print axioms Models.Recognizer.outputBias
#print axioms Models.Recognizer.outputBias.bytes
#print axioms Models.Recognizer.outputBias.decoded
#print axioms Models.Recognizer.outputWeights
#print axioms Models.Recognizer.outputWeights.bytes
#print axioms Models.Recognizer.outputWeights.decoded
#print axioms Models.Recognizer.recognizesCheck
#print axioms Models.Recognizer.recognizes_check_complete
#print axioms Models.Recognizer.recognizes_check_sound
#print axioms Models.Recognizer.sameDigit
#print axioms Models.Recognizer.same_digit_sound
