import LexLeanPreservation.RustSound
set_option autoImplicit false
set_option maxRecDepth 100000
namespace LexLeanPreserve.Cb84dbee15ade8bebba231846c7e5815b.R5.RustStd
open LexLeanTarget LexLeanPreservation.Rust

def program : TargetSyntax.Program :=
  { adts := [], functions := [
    { parameters := [0, 1], types := [.nat, .nat], result := (.pair .nat (.pair .nat .bool)),
      body := (.build .pair (.pair .nat (.pair .nat .bool)) [(.call 1 [(.closure 2 []), (.var 0), (.var 1)]), (.call 3 [(.closure 4 []), (.var 0), (.var 1)])]) },
    { parameters := [0, 1, 2], types := [(.fn [.nat] .nat), .nat, .nat], result := .nat,
      body := (.«match» .nat (.var 1) [(.arm .zero [] (.var 2)), (.arm .succ [3] (.call 1 [(.var 0), (.var 3), (.apply (.var 0) [(.var 2)])]))]) },
    { parameters := [0], types := [.nat], result := .nat,
      body := (.prim .natAdd [(.var 0), (.value .nat (.nat 1))]) },
    { parameters := [0, 1, 2], types := [(.fn [.nat] (.option .nat)), .nat, .nat], result := (.pair .nat .bool),
      body := (.«match» (.pair .nat .bool) (.var 1) [(.arm .zero [] (.build .pair (.pair .nat .bool) [(.var 2), (.build .false .bool [])])), (.arm .succ [3] (.«match» (.pair .nat .bool) (.apply (.var 0) [(.var 2)]) [(.arm .none [] (.build .pair (.pair .nat .bool) [(.var 2), (.build .true .bool [])])), (.arm .some [4] (.call 3 [(.var 0), (.var 3), (.var 4)]))]))]) },
    { parameters := [0], types := [.nat], result := (.option .nat),
      body := (.cond (.prim .natLt [(.var 0), (.value .nat (.nat 10))]) (.build .some (.option .nat) [(.prim .natAdd [(.var 0), (.value .nat (.nat 2))])]) (.build .none (.option .nat) [])) }] }

def krate : RustSyntax.Crate :=
  ({ profile := .std, items := [
    (.enum (.fn 0) [{ number := 2, fields := [] }]),
    (.apply 0 [.nat] .nat true [{ function := 2, captures := [], functionFallible := true }]),
    (.enum (.fn 1) [{ number := 4, fields := [] }]),
    (.apply 1 [.nat] (.option .nat) true [{ function := 4, captures := [], functionFallible := true }]),
    (.function (.generated .function 0) [{ pattern := (.bind (.generated .binding 0)), type := .nat }, { pattern := (.bind (.generated .binding 1)), type := .nat }] (.fallible (.pair .nat (.pair .nat .bool))) (.mk [] (.succeed (.pair (.call (.function 1) [(.construct (.closure 0 2) []), (.copy (.generated .binding 0)), (.copy (.generated .binding 1))] true) (.call (.function 3) [(.construct (.closure 1 4) []), (.copy (.generated .binding 0)), (.copy (.generated .binding 1))] true))))),
    (.function (.generated .function 1) [{ pattern := (.bind (.generated .binding 0)), type := (.fn 0) }, { pattern := (.bind (.generated .binding 1)), type := .nat }, { pattern := (.bind (.generated .binding 2)), type := .nat }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 1)) none (.copy (.generated .binding 1)))] (.cond (.isZero (.generated .holder 1)) (.mk [] (.succeed (.copy (.generated .binding 2)))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 1)))] (.call (.function 1) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 2))] true)))] false))))),
    (.function (.generated .function 2) [{ pattern := (.bind (.generated .binding 0)), type := .nat }] (.fallible .nat) (.mk [(.mk (.bind (.generated .operand 3)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 4)) none (.lit (.nat 1)))] (.call (.runtime .natAdd) [(.move (.generated .operand 3)), (.move (.generated .operand 4))] false))),
    (.function (.generated .function 3) [{ pattern := (.bind (.generated .binding 0)), type := (.fn 1) }, { pattern := (.bind (.generated .binding 1)), type := .nat }, { pattern := (.bind (.generated .binding 2)), type := .nat }] (.fallible (.pair .nat .bool)) (.mk [(.mk (.bind (.generated .holder 5)) none (.copy (.generated .binding 1)))] (.cond (.isZero (.generated .holder 5)) (.mk [] (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool false))))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 5))), (.mk (.bind (.generated .holder 7)) none (.block (.mk [(.mk (.bind (.generated .callee 6)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 6) [(.copy (.generated .binding 2))] true))))] (.matchOn (.move (.generated .holder 7)) [(.mk .none (.mk [] (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool true)))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 3) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))]))))),
    (.function (.generated .function 4) [{ pattern := (.bind (.generated .binding 0)), type := .nat }] (.fallible (.option .nat)) (.mk [(.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 9)) none (.lit (.nat 10)))] (.cond (.call (.runtime .natLt) [(.move (.generated .operand 8)), (.move (.generated .operand 9))] false) (.mk [] (.succeed (.construct .some [(.block (.mk [(.mk (.bind (.generated .operand 10)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 11)) none (.lit (.nat 2)))] (.call (.runtime .natAdd) [(.move (.generated .operand 10)), (.move (.generated .operand 11))] true)))]))) (.mk [] (.succeed (.construct (.none .nat) []))))))] } : LexLeanTarget.RustSyntax.Crate)

def flags : Flags := [(([.nat], .nat), true), (([.nat], (.option .nat)), true)]

theorem fun0 : FunOK program krate flags 0 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.succeed (.pair (.call (.function 1) [(.construct (.closure 0 2) []), (.copy (.generated .binding 0)), (.copy (.generated .binding 1))] true) (.call (.function 3) [(.construct (.closure 1 4) []), (.copy (.generated .binding 0)), (.copy (.generated .binding 1))] true))), [(1, .nat, (some 1)), (0, .nat, (some 0))], rfl, rfl,
    (Corr.fOfB (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.fn [.nat] .nat), .nat, .nat]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.closure (caps := []) (mask := []) (af := true) (ff := true) (Corr.opsNil) rfl rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.fn [.nat] (.option .nat)), .nat, .nat]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.closure (caps := []) (mask := []) (af := true) (ff := true) (Corr.opsNil) rfl rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl rfl)) (Corr.lNil))))))⟩⟩

theorem fun1 : FunOK program krate flags 1 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 1)) none (.copy (.generated .binding 1)))], (.cond (.isZero (.generated .holder 1)) (.mk [] (.succeed (.copy (.generated .binding 2)))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 1)))] (.call (.function 1) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 2))] true)))] false))), [(2, .nat, (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat] .nat), (some 0))], rfl, rfl,
    (Corr.matchNat (sl := (some 3)) (Corr.var rfl rfl) rfl rfl rfl (Corr.kIf (la := []) (ta := (.succeed (.copy (.generated .binding 2)))) (lb := []) (tb := (.call (.function 1) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 2))] true)))] false)) (Corr.fOfB (Corr.bOfE (Corr.var rfl rfl))) (Corr.callF (ts := [(.fn [.nat] .nat), .nat, .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))]) (tail := (.apply (.generated .callee 2) [(.copy (.generated .binding 2))] true)) (Corr.apply (ps := [.nat]) (af := true) (Corr.var rfl rfl) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl)) (Corr.lNil))))) rfl rfl rfl rfl)))⟩⟩

theorem fun2 : FunOK program krate flags 2 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 3)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 4)) none (.lit (.nat 1)))], (.call (.runtime .natAdd) [(.move (.generated .operand 3)), (.move (.generated .operand 4))] false), [(0, .nat, (some 0))], rfl, rfl,
    (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)⟩⟩

theorem fun3 : FunOK program krate flags 3 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 5)) none (.copy (.generated .binding 1)))], (.cond (.isZero (.generated .holder 5)) (.mk [] (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool false))))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 5))), (.mk (.bind (.generated .holder 7)) none (.block (.mk [(.mk (.bind (.generated .callee 6)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 6) [(.copy (.generated .binding 2))] true))))] (.matchOn (.move (.generated .holder 7)) [(.mk .none (.mk [] (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool true)))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 3) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))]))), [(2, .nat, (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat] (.option .nat)), (some 0))], rfl, rfl,
    (Corr.matchNat (sl := (some 3)) (Corr.var rfl rfl) rfl rfl rfl (Corr.kIf (la := []) (ta := (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool false))))) (lb := [(.mk (.bind (.generated .holder 7)) none (.block (.mk [(.mk (.bind (.generated .callee 6)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 6) [(.copy (.generated .binding 2))] true))))]) (tb := (.matchOn (.move (.generated .holder 7)) [(.mk .none (.mk [] (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool true)))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 3) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))])) (Corr.fOfB (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil)))))) (Corr.matchArms (st := (.option .nat)) (U := []) (view := false) (idx := [0, 1]) (Corr.eOfB (lets := [(.mk (.bind (.generated .callee 6)) (some (.fn 1)) (.clone (.generated .binding 0)))]) (tail := (.apply (.generated .callee 6) [(.copy (.generated .binding 2))] true)) (Corr.apply (ps := [.nat]) (af := true) (Corr.var rfl rfl) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(3, .nat, (some 3)), (2, .nat, (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat] (.option .nat)), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.succeed (.pair (.copy (.generated .binding 2)) (.lit (.bool true))))) (Corr.mCons (Γ' := [(4, .nat, (some 4)), (3, .nat, (some 3)), (2, .nat, (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat] (.option .nat)), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 3) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)) (Corr.mNil) rfl rfl rfl (Corr.callF (ts := [(.fn [.nat] (.option .nat)), .nat, .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl)) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil))))))) rfl rfl rfl)))⟩⟩

theorem fun4 : FunOK program krate flags 4 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 9)) none (.lit (.nat 10)))], (.cond (.call (.runtime .natLt) [(.move (.generated .operand 8)), (.move (.generated .operand 9))] false) (.mk [] (.succeed (.construct .some [(.block (.mk [(.mk (.bind (.generated .operand 10)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 11)) none (.lit (.nat 2)))] (.call (.runtime .natAdd) [(.move (.generated .operand 10)), (.move (.generated .operand 11))] true)))]))) (.mk [] (.succeed (.construct (.none .nat) [])))), [(0, .nat, (some 0))], rfl, rfl,
    (Corr.cond (lc := [(.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 9)) none (.lit (.nat 10)))]) (ce := (.call (.runtime .natLt) [(.move (.generated .operand 8)), (.move (.generated .operand 9))] false)) (lk := []) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.succeed (.construct .some [(.block (.mk [(.mk (.bind (.generated .operand 10)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 11)) none (.lit (.nat 2)))] (.call (.runtime .natAdd) [(.move (.generated .operand 10)), (.move (.generated .operand 11))] true)))]))) (lb := []) (tb := (.succeed (.construct (.none .nat) []))) (Corr.fOfB (Corr.build (ts := [.nat]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 10)) none (.copy (.generated .binding 0))), (.mk (.bind (.generated .operand 11)) none (.lit (.nat 2)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 10)), (.move (.generated .operand 11))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.lNil))) rfl)) (Corr.fOfB (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl))))⟩⟩

theorem crate_ok : CrateOK program krate flags := by
  intro f fn h
  match f with
  | 0 => exact fun0
  | 1 => exact fun1
  | 2 => exact fun2
  | 3 => exact fun3
  | 4 => exact fun4
  | _ + 5 => simp [program, index_eq] at h

/-- Every function of the program is simulated by its rendering. -/
theorem root : ∀ n f, FunSem program krate flags n f := fun n f => simulate crate_ok n f

end LexLeanPreserve.Cb84dbee15ade8bebba231846c7e5815b.R5.RustStd
