import LexLeanPreservation.RustSound
set_option autoImplicit false
set_option maxRecDepth 100000
namespace LexLeanPreserve.Cba27a3dc52c63de8b08b0726788d5c73.R1.RustStd
open LexLeanTarget LexLeanPreservation.Rust

def program : TargetSyntax.Program :=
  { adts := [], functions := [
    { parameters := [0, 1], types := [(.list (.pair .nat .nat)), .nat], result := .nat,
      body := (.call 1 [(.closure 2 [(.var 1)]), (.value .nat (.nat 0)), (.var 0)]) },
    { parameters := [0, 1, 2], types := [(.fn [.nat, .nat, .nat] .nat), .nat, (.list (.pair .nat .nat))], result := .nat,
      body := (.«match» .nat (.var 2) [(.arm .nil [] (.var 1)), (.arm .cons [3, 4] (.call 1 [(.var 0), (.apply (.var 0) [(.var 1), (.first (.var 3)), (.second (.var 3))]), (.var 4)]))]) },
    { parameters := [0, 1, 2, 3], types := [.nat, .nat, .nat, .nat], result := .nat,
      body := (.prim .natAdd [(.prim .natAdd [(.var 1), (.var 2)]), (.prim .natAdd [(.var 3), (.var 0)])]) }] }

def krate : RustSyntax.Crate :=
  ({ profile := .std, items := [
    (.enum (.fn 0) [{ number := 2, fields := [.nat] }]),
    (.apply 0 [.nat, .nat, .nat] .nat true [{ function := 2, captures := [.copy], functionFallible := true }]),
    (.function (.generated .function 0) [{ pattern := (.bind (.generated .binding 0)), type := (.list (.pair .nat .nat)) }, { pattern := (.bind (.generated .binding 1)), type := .nat }] (.fallible .nat) (.mk [] (.call (.function 1) [(.construct (.closure 0 2) [(.copy (.generated .binding 1))]), (.lit (.nat 0)), (.clone (.generated .binding 0))] false))),
    (.function (.generated .function 1) [{ pattern := (.bind (.generated .binding 0)), type := (.fn 0) }, { pattern := (.bind (.generated .binding 1)), type := .nat }, { pattern := (.bind (.generated .binding 2)), type := (.list (.pair .nat .nat)) }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 1)) none (.clone (.generated .binding 2)))] (.matchOn (.uncons (.generated .holder 1)) [(.mk .none (.mk [] (.succeed (.copy (.generated .binding 1))))), (.mk (.some (.tuple [(.bind (.generated .binding 3)), (.bind (.generated .binding 4))])) (.mk [] (.call (.function 1) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 1)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 3)), .wild]) none (.copy (.generated .binding 3)))] (.move (.generated .part 3)))), (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 4))]) none (.copy (.generated .binding 3)))] (.move (.generated .part 4))))] true))), (.clone (.generated .binding 4))] false)))]))),
    (.function (.generated .function 2) [{ pattern := (.bind (.generated .binding 0)), type := .nat }, { pattern := (.bind (.generated .binding 1)), type := .nat }, { pattern := (.bind (.generated .binding 2)), type := .nat }, { pattern := (.bind (.generated .binding 3)), type := .nat }] (.fallible .nat) (.mk [(.mk (.bind (.generated .operand 9)) none (.block (.mk [(.mk (.bind (.generated .operand 5)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 6)) none (.copy (.generated .binding 2)))] (.call (.runtime .natAdd) [(.move (.generated .operand 5)), (.move (.generated .operand 6))] true)))), (.mk (.bind (.generated .operand 10)) none (.block (.mk [(.mk (.bind (.generated .operand 7)) none (.copy (.generated .binding 3))), (.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0)))] (.call (.runtime .natAdd) [(.move (.generated .operand 7)), (.move (.generated .operand 8))] true))))] (.call (.runtime .natAdd) [(.move (.generated .operand 9)), (.move (.generated .operand 10))] false)))] } : LexLeanTarget.RustSyntax.Crate)

def flags : Flags := [(([.nat, .nat, .nat], .nat), true)]

theorem fun0 : FunOK program krate flags 0 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.call (.function 1) [(.construct (.closure 0 2) [(.copy (.generated .binding 1))]), (.lit (.nat 0)), (.clone (.generated .binding 0))] false), [(1, .nat, (some 1)), (0, (.list (.pair .nat .nat)), (some 0))], rfl, rfl,
    (Corr.callF (ts := [(.fn [.nat, .nat, .nat] .nat), .nat, (.list (.pair .nat .nat))]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.closure (caps := [.nat]) (mask := [false]) (af := true) (ff := true) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.value rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl)⟩⟩

theorem fun1 : FunOK program krate flags 1 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 1)) none (.clone (.generated .binding 2)))], (.matchOn (.uncons (.generated .holder 1)) [(.mk .none (.mk [] (.succeed (.copy (.generated .binding 1))))), (.mk (.some (.tuple [(.bind (.generated .binding 3)), (.bind (.generated .binding 4))])) (.mk [] (.call (.function 1) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 1)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 3)), .wild]) none (.copy (.generated .binding 3)))] (.move (.generated .part 3)))), (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 4))]) none (.copy (.generated .binding 3)))] (.move (.generated .part 4))))] true))), (.clone (.generated .binding 4))] false)))]), [(2, (.list (.pair .nat .nat)), (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat, .nat, .nat] .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.list (.pair .nat .nat))) (U := []) (view := true) (idx := [0, 1]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(2, (.list (.pair .nat .nat)), (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat, .nat, .nat] .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.succeed (.copy (.generated .binding 1)))) (Corr.mCons (Γ' := [(4, (.list (.pair .nat .nat)), (some 4)), (3, (.pair .nat .nat), (some 3)), (2, (.list (.pair .nat .nat)), (some 2)), (1, .nat, (some 1)), (0, (.fn [.nat, .nat, .nat] .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 1) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 2) [(.copy (.generated .binding 1)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 3)), .wild]) none (.copy (.generated .binding 3)))] (.move (.generated .part 3)))), (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 4))]) none (.copy (.generated .binding 3)))] (.move (.generated .part 4))))] true))), (.clone (.generated .binding 4))] false)) (Corr.mNil) rfl rfl rfl (Corr.callF (ts := [(.fn [.nat, .nat, .nat] .nat), .nat, (.list (.pair .nat .nat))]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .callee 2)) (some (.fn 0)) (.clone (.generated .binding 0)))]) (tail := (.apply (.generated .callee 2) [(.copy (.generated .binding 1)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 3)), .wild]) none (.copy (.generated .binding 3)))] (.move (.generated .part 3)))), (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 4))]) none (.copy (.generated .binding 3)))] (.move (.generated .part 4))))] true)) (Corr.apply (ps := [.nat, .nat, .nat]) (af := true) (Corr.var rfl rfl) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [(.bind (.generated .part 3)), .wild]) none (.copy (.generated .binding 3)))]) (tail := (.move (.generated .part 3))) (Corr.first (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 4))]) none (.copy (.generated .binding 3)))]) (tail := (.move (.generated .part 4))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lNil))))) rfl rfl rfl rfl)) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl)) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.var rfl rfl)))) rfl rfl rfl)⟩⟩

theorem fun2 : FunOK program krate flags 2 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 9)) none (.block (.mk [(.mk (.bind (.generated .operand 5)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 6)) none (.copy (.generated .binding 2)))] (.call (.runtime .natAdd) [(.move (.generated .operand 5)), (.move (.generated .operand 6))] true)))), (.mk (.bind (.generated .operand 10)) none (.block (.mk [(.mk (.bind (.generated .operand 7)) none (.copy (.generated .binding 3))), (.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0)))] (.call (.runtime .natAdd) [(.move (.generated .operand 7)), (.move (.generated .operand 8))] true))))], (.call (.runtime .natAdd) [(.move (.generated .operand 9)), (.move (.generated .operand 10))] false), [(3, .nat, (some 3)), (2, .nat, (some 2)), (1, .nat, (some 1)), (0, .nat, (some 0))], rfl, rfl,
    (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 5)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 6)) none (.copy (.generated .binding 2)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 5)), (.move (.generated .operand 6))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 7)) none (.copy (.generated .binding 3))), (.mk (.bind (.generated .operand 8)) none (.copy (.generated .binding 0)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 7)), (.move (.generated .operand 8))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)⟩⟩

theorem crate_ok : CrateOK program krate flags := by
  intro f fn h
  match f with
  | 0 => exact fun0
  | 1 => exact fun1
  | 2 => exact fun2
  | _ + 3 => simp [program, index_eq] at h

/-- Every function of the program is simulated by its rendering. -/
theorem root : ∀ n f, FunSem program krate flags n f := fun n f => simulate crate_ok n f

end LexLeanPreserve.Cba27a3dc52c63de8b08b0726788d5c73.R1.RustStd
