//! The production realization calculus itself (SPEC.md §17.14), as the
//! `compiler` project states it to Lean: its syntax (`TargetSyntax`), its
//! denotation (`TargetSemantics`), the encoders of LexLean collection values
//! that fixture statements compare against (`TargetOracle`), the `Main`
//! entrypoint, and the project's configuration.
//!
//! The modules' semantic data is a few hundred kilobytes of canonical JSON,
//! which no reviewer reads; the calculus is read here instead, as the terms
//! that build it. The committed files are exactly what [`files`] renders,
//! which `cargo xtask check-calculus` enforces, so the JSON is never edited
//! by hand and a change to the calculus is a change to this file.

use std::cell::Cell;
use std::collections::BTreeMap;

use lexlean::calculus::term::{self, SEMANTICS, SYNTAX};
use serde_json::Value as Json;

use crate::lx::{
    self, add, and, axioms, beq, ble, blt, bool_t, boolean, bytes, cons, definition, first,
    inductive, int8_t, int_t, ite, let_in, list, list_t, local_t, map_literal, map_t, matching,
    member, module_tex, mutual, nat, nat_t, nat_wide, nil, none, not, option_t, or, pair,
    parameter, prim, product_t, project, record, recursive, scalar_t, second, some, string_t,
    structure, value, var,
};

/// The module of the collection-value encoders.
pub const ORACLE: &str = "TargetOracle";

/// The module holding the fixture statements, generated by `calculus`.
const FIXTURES: &str = "TargetFixtures";

/// All three of Lean's standard axioms: the exact policy of every
/// declaration here whose audit reports `Classical.choice`.
const CLASSICAL: &[&str] = &["Classical.choice", "Quot.sound", "propext"];

/// The fixed widths: the `TargetSyntax` constructor, and the LexLean type
/// that realizes it.
const FIXED: [(&str, &str); 8] = [
    ("u8", "uint8"),
    ("u16", "uint16"),
    ("u32", "uint32"),
    ("u64", "uint64"),
    ("i8", "int8"),
    ("i16", "int16"),
    ("i32", "int32"),
    ("i64", "int64"),
];

/// The signed fixed widths, the only ones `checkedNeg` accepts.
const SIGNED: [(&str, &str); 4] = [
    ("i8", "int8"),
    ("i16", "int16"),
    ("i32", "int32"),
    ("i64", "int64"),
];

/// The integer `Value` constructors a conversion or decimal formatting
/// reads.
const INTEGERS: [&str; 9] = ["int", "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64"];

/// The `Value` constructors `equal` compares by LexLean's own equality.
const EQUATABLE: [&str; 12] = [
    "nat", "bool", "string", "bytes", "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64",
];

/// The key types of the total key order `compare` realizes (§17.12): the
/// `Value` constructor, its LexLean type, and the axiom policy of the
/// definition ordering two such keys.
const KEYS: [(&str, &str, &[&str]); 12] = [
    ("nat", "nat", &[]),
    ("int", "int", &[]),
    ("bool", "bool", &["propext"]),
    ("string", "string", CLASSICAL),
    ("u8", "uint8", &[]),
    ("u16", "uint16", &[]),
    ("u32", "uint32", &[]),
    ("u64", "uint64", &[]),
    ("i8", "int8", &[]),
    ("i16", "int16", &[]),
    ("i32", "int32", &[]),
    ("i64", "int64", &[]),
];

/// The constructor shapes a `match` arm or a `build` names, besides `adt`.
const SHAPES: [&str; 15] = [
    "none", "some", "ok", "error", "nil", "cons", "zero", "succ", "pair", "true", "false", "unit",
    "lt", "eq", "gt",
];

/// The primitives with no syntactic argument, in declaration order.
const PRIMITIVES: [&str; 40] = [
    "natAdd",
    "natSub",
    "natMul",
    "natQuot",
    "natRem",
    "natEq",
    "natLe",
    "natLt",
    "intAdd",
    "intSub",
    "intMul",
    "intNeg",
    "intQuot",
    "intRem",
    "checkedAdd",
    "checkedSub",
    "checkedMul",
    "checkedNeg",
    "checkedQuot",
    "bitAnd",
    "bitOr",
    "bitXor",
    "bitNot",
    "shiftLeft",
    "shiftRight",
    "equal",
    "boolNot",
    "boolAnd",
    "boolOr",
    "append",
    "length",
    "index",
    "slice",
    "utf8Encode",
    "utf8Decode",
    "compareBytes",
    "splitExact",
    "join",
    "formatDecimal",
    "compare",
];

/// A constructor table: each constructor with its field types.
type Constructors = Vec<(&'static str, Vec<Json>)>;

// --- references ------------------------------------------------------------

/// A type of `TargetSyntax`.
fn syntax_t(name: &str) -> Json {
    term::named(SYNTAX, name)
}

/// A call of a function of the module being generated.
fn call(function: &str, arguments: Vec<Json>) -> Json {
    lx::call(member(function), arguments)
}

/// A constructor of the module being generated, or a builtin such as
/// `Option.none`.
fn ctor(constructor: &str, arguments: Vec<Json>) -> Json {
    lx::construct(member(constructor), arguments)
}

fn syntax_ctor(constructor: &str, arguments: Vec<Json>) -> Json {
    lx::construct(term::member(SYNTAX, constructor), arguments)
}

fn owned(binders: &[&str]) -> Vec<String> {
    binders.iter().map(|binder| (*binder).to_owned()).collect()
}

/// A branch on a constructor of the module being generated, or a builtin.
fn branch(constructor: &str, binders: &[&str], body: Json) -> Json {
    lx::branch(member(constructor), owned(binders), body)
}

fn syntax_branch(constructor: &str, binders: &[&str], body: Json) -> Json {
    lx::branch(term::member(SYNTAX, constructor), owned(binders), body)
}

// --- TargetSyntax ----------------------------------------------------------
//
// The constructor tables are written once, in the syntax's own terms (a
// field of type `Ty` is the local `Ty`), and serve both the declarations and
// every match the semantics makes over them, so a match cannot fall out of
// step with the constructors it covers.

fn nullary(names: &[&'static str]) -> Constructors {
    names.iter().map(|name| (*name, Vec::new())).collect()
}

fn int_kind_constructors() -> Constructors {
    FIXED.iter().map(|(name, _)| (*name, Vec::new())).collect()
}

fn ty_constructors() -> Constructors {
    let ty = || local_t("Ty");
    vec![
        ("unit", vec![]),
        ("bool", vec![]),
        ("nat", vec![]),
        ("int", vec![]),
        ("fixed", vec![local_t("IntKind")]),
        ("string", vec![]),
        ("bytes", vec![]),
        ("ordering", vec![]),
        ("option", vec![ty()]),
        ("result", vec![ty(), ty()]),
        ("list", vec![ty()]),
        ("pair", vec![ty(), ty()]),
        ("adt", vec![nat_t()]),
        ("fn", vec![list_t(ty()), ty()]),
    ]
}

fn value_constructors() -> Constructors {
    let value = || local_t("Value");
    let mut out = vec![
        ("unit", vec![]),
        ("bool", vec![bool_t()]),
        ("nat", vec![nat_t()]),
        ("int", vec![int_t()]),
    ];
    out.extend(
        FIXED
            .iter()
            .map(|(name, kind)| (*name, vec![scalar_t(kind)])),
    );
    out.extend([
        ("string", vec![string_t()]),
        ("bytes", vec![scalar_t("bytes")]),
        ("ordering", vec![local_t("Order")]),
        ("none", vec![]),
        ("some", vec![value()]),
        ("ok", vec![value()]),
        ("error", vec![value()]),
        ("list", vec![list_t(value())]),
        ("pair", vec![value(), value()]),
        ("adt", vec![nat_t(), list_t(value())]),
        ("closure", vec![nat_t(), list_t(value())]),
    ]);
    out
}

fn shape_constructors() -> Constructors {
    let mut out = nullary(&SHAPES);
    out.push(("adt", vec![nat_t()]));
    out
}

fn prim_constructors() -> Constructors {
    let mut out = nullary(&PRIMITIVES);
    out.push(("convert", vec![local_t("IntKind")]));
    out.push(("parseDecimal", vec![local_t("Ty")]));
    out
}

fn expr_constructors() -> Constructors {
    let expr = || local_t("Expr");
    let exprs = || list_t(local_t("Expr"));
    vec![
        ("value", vec![local_t("Ty"), local_t("Value")]),
        ("var", vec![nat_t()]),
        ("let", vec![nat_t(), local_t("Ty"), expr(), expr()]),
        ("cond", vec![expr(), expr(), expr()]),
        ("match", vec![local_t("Ty"), expr(), list_t(local_t("Arm"))]),
        ("build", vec![local_t("Shape"), local_t("Ty"), exprs()]),
        ("call", vec![nat_t(), exprs()]),
        ("closure", vec![nat_t(), exprs()]),
        ("apply", vec![expr(), exprs()]),
        ("prim", vec![local_t("Prim"), exprs()]),
        ("first", vec![expr()]),
        ("second", vec![expr()]),
        ("field", vec![expr(), nat_t()]),
    ]
}

/// The `TargetSyntax` module: types, values, shapes, primitives,
/// expressions, and programs of the calculus.
#[must_use]
pub fn syntax_module() -> String {
    let declarations = vec![
        inductive("IntKind", int_kind_constructors()),
        inductive("Order", nullary(&["less", "same", "more"])),
        inductive("Ty", ty_constructors()),
        inductive("Value", value_constructors()),
        inductive("Shape", shape_constructors()),
        inductive("Prim", prim_constructors()),
        mutual("Code", inductive("Expr", expr_constructors())),
        mutual(
            "Code",
            inductive(
                "Arm",
                vec![(
                    "arm",
                    vec![local_t("Shape"), list_t(nat_t()), local_t("Expr")],
                )],
            ),
        ),
        structure("Adt", vec![("constructors", list_t(list_t(local_t("Ty"))))]),
        structure(
            "Function",
            vec![
                ("parameters", list_t(nat_t())),
                ("types", list_t(local_t("Ty"))),
                ("result", local_t("Ty")),
                ("body", local_t("Expr")),
            ],
        ),
        structure(
            "Program",
            vec![
                ("adts", list_t(local_t("Adt"))),
                ("functions", list_t(local_t("Function"))),
            ],
        ),
    ];
    module_tex(SYNTAX, &[], declarations)
}

// --- TargetSemantics: shared types and terms -------------------------------

fn value_t() -> Json {
    syntax_t("Value")
}
fn values_t() -> Json {
    list_t(value_t())
}
fn order_t() -> Json {
    syntax_t("Order")
}
/// An environment: each local's number with its value, innermost first.
fn environment_t() -> Json {
    list_t(product_t(nat_t(), value_t()))
}
fn outcome_t() -> Json {
    local_t("Outcome")
}
fn function_t() -> Json {
    syntax_t("Function")
}

fn outcome(constructor: &str, arguments: Vec<Json>) -> Json {
    ctor(&format!("Outcome.{constructor}"), arguments)
}
fn outcomes(constructor: &str, arguments: Vec<Json>) -> Json {
    ctor(&format!("Outcomes.{constructor}"), arguments)
}
fn stuck() -> Json {
    outcome("stuck", Vec::new())
}
fn exhausted() -> Json {
    outcome("exhausted", Vec::new())
}
/// A value outcome charged `steps`.
fn produced(result: Json, steps: Json) -> Json {
    outcome("value", vec![result, steps])
}
/// A value outcome charged nothing beyond what its caller charges: a
/// primitive's or a constructor's result, whose step `eval` counts.
fn done(result: Json) -> Json {
    produced(result, nat(0))
}
fn order(constructor: &str) -> Json {
    syntax_ctor(&format!("Order.{constructor}"), Vec::new())
}
/// A list of values, for `destruct`'s fields.
fn values(items: Vec<Json>) -> Json {
    list(value_t(), items)
}
fn some_values(items: Json) -> Json {
    some(values_t(), items)
}
fn no_values() -> Json {
    none(values_t())
}

/// Which outcome family a match inspects: one expression's, or a list's.
#[derive(Clone, Copy)]
enum Family {
    One,
    Many,
}

/// A match on an outcome. Its value case binds the value (or values) and
/// the steps taken; its overflow case binds the steps taken.
fn outcome_match(
    scrutinee: Json,
    family: Family,
    value: (&[&str], Json),
    overflow: (&[&str], Json),
    stuck: Json,
    exhausted: Json,
) -> Json {
    let (family, produced) = match family {
        Family::One => ("Outcome", "value"),
        Family::Many => ("Outcomes", "values"),
    };
    matching(
        scrutinee,
        vec![
            branch(&format!("{family}.{produced}"), value.0, value.1),
            branch(&format!("{family}.overflow"), overflow.0, overflow.1),
            branch(&format!("{family}.stuck"), &[], stuck),
            branch(&format!("{family}.exhausted"), &[], exhausted),
        ],
    )
}

fn option_match(scrutinee: Json, absent: Json, binder: &str, present: Json) -> Json {
    matching(
        scrutinee,
        vec![
            branch("Option.none", &[], absent),
            branch("Option.some", &[binder], present),
        ],
    )
}

fn list_match(scrutinee: Json, empty: Json, head: &str, tail: &str, nonempty: Json) -> Json {
    matching(
        scrutinee,
        vec![
            branch("List.nil", &[], empty),
            branch("List.cons", &[head, tail], nonempty),
        ],
    )
}

fn order_match(scrutinee: Json, less: Json, same: Json, more: Json) -> Json {
    matching(
        scrutinee,
        vec![
            syntax_branch("Order.less", &[], less),
            syntax_branch("Order.same", &[], same),
            syntax_branch("Order.more", &[], more),
        ],
    )
}

/// A match on an `IntKind`, its body built for each fixed width in turn.
fn kind_match(scrutinee: Json, mut body: impl FnMut(&str, &str) -> Json) -> Json {
    matching(
        scrutinee,
        FIXED
            .iter()
            .map(|(name, kind)| syntax_branch(&format!("IntKind.{name}"), &[], body(name, kind)))
            .collect(),
    )
}

/// `none` or `some` of a primitive's optional result, as a value outcome:
/// a checked operation that fails is `Value.none`, never stuck.
fn optional(result: Json, constructor: &str) -> Json {
    option_match(
        result,
        done(value("none", Vec::new())),
        "result",
        done(value("some", vec![value(constructor, vec![var("result")])])),
    )
}

/// One case of a match on a `TargetSyntax` type.
struct Case {
    constructor: &'static str,
    binders: Vec<String>,
    body: Json,
}

fn on(constructor: &'static str, binders: &[&str], body: Json) -> Case {
    Case {
        constructor,
        binders: owned(binders),
        body,
    }
}

fn take_case(cases: &mut Vec<Case>, constructor: &str) -> Option<Case> {
    let position = cases
        .iter()
        .position(|case| case.constructor == constructor)?;
    Some(cases.remove(position))
}

fn case_branch(ty: &str, case: Case) -> Json {
    lx::branch(
        term::member(SYNTAX, &format!("{ty}.{}", case.constructor)),
        case.binders,
        case.body,
    )
}

/// A match on a `TargetSyntax` type with a case for every constructor. The
/// branches follow the declaration, whatever order the cases were built in.
///
/// # Panics
///
/// Panics when a constructor has no case or a case names no constructor.
fn exhaustive(
    scrutinee: Json,
    ty: &str,
    constructors: &Constructors,
    mut cases: Vec<Case>,
) -> Json {
    let branches = constructors
        .iter()
        .map(|(constructor, _)| {
            let case = take_case(&mut cases, constructor)
                .unwrap_or_else(|| panic!("{ty}.{constructor} has no case"));
            case_branch(ty, case)
        })
        .collect();
    assert!(cases.is_empty(), "a {ty} case names no constructor");
    matching(scrutinee, branches)
}

// --- TargetSemantics: the builder ------------------------------------------

/// Builds `TargetSemantics` terms that need binders of their own.
///
/// A branch must bind every field of its constructor, and a binder the body
/// never reads is drawn fresh: `ignored`, `argument`, `rest`, `steps`,
/// `function`, `bound`, numbered in one sequence across the module. The
/// numbering is part of the committed bytes, so the order in which terms
/// are built is load-bearing: a term's sub-terms (its arguments, in Rust's
/// left-to-right evaluation) draw before the term itself, and reordering two
/// definitions renumbers every binder after them.
struct Semantics {
    drawn: Cell<u32>,
}

impl Semantics {
    fn new() -> Self {
        Semantics {
            drawn: Cell::new(0),
        }
    }

    fn fresh(&self, base: &str) -> String {
        self.drawn.set(self.drawn.get() + 1);
        format!("{base}{}", self.drawn.get())
    }

    fn ignored(&self) -> String {
        self.fresh("ignored")
    }

    /// A match on a `TargetSyntax` type where every constructor without a
    /// case takes `default`, its fields bound and ignored.
    fn match_or(
        &self,
        scrutinee: Json,
        ty: &str,
        constructors: &Constructors,
        mut cases: Vec<Case>,
        default: &Json,
    ) -> Json {
        let branches = constructors
            .iter()
            .map(|(constructor, fields)| {
                let case = take_case(&mut cases, constructor).unwrap_or_else(|| Case {
                    constructor,
                    binders: fields.iter().map(|_| self.ignored()).collect(),
                    body: default.clone(),
                });
                case_branch(ty, case)
            })
            .collect();
        assert!(cases.is_empty(), "a {ty} case names no constructor");
        matching(scrutinee, branches)
    }

    fn value_match(&self, scrutinee: Json, cases: Vec<Case>, default: Json) -> Json {
        self.match_or(scrutinee, "Value", &value_constructors(), cases, &default)
    }

    fn type_match(&self, scrutinee: Json, cases: Vec<Case>, default: Json) -> Json {
        self.match_or(scrutinee, "Ty", &ty_constructors(), cases, &default)
    }

    /// Destructure the operand list `values` into exactly `N` operands; any
    /// other length is stuck.
    fn operands<const N: usize>(&self, body: impl FnOnce([Json; N]) -> Json) -> Json {
        let names: Vec<String> = (0..N).map(|_| self.fresh("argument")).collect();
        let rests: Vec<String> = (0..N).map(|_| self.fresh("rest")).collect();
        let exact = body(std::array::from_fn(|index| var(&names[index])));
        let remainder = |index: usize| {
            if index == 0 {
                var("values")
            } else {
                var(&rests[index - 1])
            }
        };
        let mut term = list_match(
            remainder(N),
            exact,
            &self.ignored(),
            &self.ignored(),
            stuck(),
        );
        for index in (0..N).rev() {
            term = list_match(
                remainder(index),
                stuck(),
                &names[index],
                &rests[index],
                term,
            );
        }
        term
    }

    /// `N` operands that must all be `Value.<constructor>`, unwrapped into
    /// `binders`; anything else is stuck.
    fn operands_of<const N: usize>(
        &self,
        constructor: &'static str,
        binders: [&str; N],
        body: impl FnOnce([Json; N]) -> Json,
    ) -> Json {
        self.operands(|operands: [Json; N]| {
            let mut term = body(binders.map(var));
            for (operand, binder) in operands.into_iter().zip(binders).rev() {
                term = self.value_match(operand, vec![on(constructor, &[binder], term)], stuck());
            }
            term
        })
    }

    /// Two operands of one fixed width, unwrapped as `leftNumber` and
    /// `rightNumber`; mixed widths are stuck.
    fn fixed_pair(&self, body: impl Fn(Json, Json, &'static str, &str) -> Json) -> Json {
        self.operands(|[left, right]| {
            let cases = FIXED
                .iter()
                .map(|&(name, kind)| {
                    let inner = self.value_match(
                        right.clone(),
                        vec![on(
                            name,
                            &["rightNumber"],
                            body(var("leftNumber"), var("rightNumber"), name, kind),
                        )],
                        stuck(),
                    );
                    on(name, &["leftNumber"], inner)
                })
                .collect();
            self.value_match(left, cases, stuck())
        })
    }

    /// One operand of any of the fixed widths `widths`, unwrapped as
    /// `leftNumber`.
    fn fixed_one(
        &self,
        widths: &[(&'static str, &str)],
        body: impl Fn(Json, &'static str, &str) -> Json,
    ) -> Json {
        self.operands(|[operand]| {
            let cases = widths
                .iter()
                .map(|&(name, kind)| on(name, &["leftNumber"], body(var("leftNumber"), name, kind)))
                .collect();
            self.value_match(operand, cases, stuck())
        })
    }

    /// A checked fixed-width operation: overflow is `Value.none`.
    fn checked(&self, operation: &str) -> Json {
        self.fixed_pair(|left, right, name, kind| {
            optional(
                prim(operation, vec![left, right], option_t(scalar_t(kind))),
                name,
            )
        })
    }

    fn bitwise(&self, operation: &str) -> Json {
        self.fixed_pair(|left, right, name, kind| {
            done(value(
                name,
                vec![prim(operation, vec![left, right], scalar_t(kind))],
            ))
        })
    }

    /// A shift of any fixed width by a `u32` amount; an amount at or beyond
    /// the width is `Value.none`.
    fn shift(&self, operation: &str) -> Json {
        self.operands(|[number, amount]| {
            let by_width = FIXED
                .iter()
                .map(|&(name, kind)| {
                    on(
                        name,
                        &["leftNumber"],
                        optional(
                            prim(
                                operation,
                                vec![var("leftNumber"), var("amount")],
                                option_t(scalar_t(kind)),
                            ),
                            name,
                        ),
                    )
                })
                .collect();
            self.value_match(
                amount,
                vec![on(
                    "u32",
                    &["amount"],
                    self.value_match(number, by_width, stuck()),
                )],
                stuck(),
            )
        })
    }

    /// Continue with `scrutinee`'s value, binding it and its steps; any
    /// other outcome passes through, an overflow charged this node's step.
    fn propagate(&self, family: Family, scrutinee: Json, binders: [&str; 2], then: Json) -> Json {
        let steps = self.fresh("steps");
        outcome_match(
            scrutinee,
            family,
            (&binders, then),
            (
                &[&steps],
                outcome("overflow", vec![add(var(&steps), nat(1))]),
            ),
            stuck(),
            exhausted(),
        )
    }

    /// Call function `index` of the program on `arguments`: its body runs in
    /// a fresh environment of its parameters alone, and the call is charged
    /// `steps` on top of the body's.
    fn function_call(&self, index: Json, arguments: Json, steps: Json) -> Json {
        let function = self.fresh("function");
        let bound = self.fresh("bound");
        option_match(
            prim(
                "index",
                vec![project(var("program"), "functions"), index],
                option_t(function_t()),
            ),
            stuck(),
            &function,
            option_match(
                call(
                    "bindAll",
                    vec![
                        project(var(&function), "parameters"),
                        arguments,
                        nil(product_t(nat_t(), value_t())),
                    ],
                ),
                stuck(),
                &bound,
                call(
                    "addSteps",
                    vec![eval(var(&bound), project(var(&function), "body")), steps],
                ),
            ),
        )
    }
}

// --- TargetSemantics: outcomes and environments ----------------------------

fn outcome_types() -> [Json; 2] {
    [
        inductive(
            "Outcome",
            vec![
                ("value", vec![value_t(), nat_t()]),
                ("overflow", vec![nat_t()]),
                ("stuck", vec![]),
                ("exhausted", vec![]),
            ],
        ),
        inductive(
            "Outcomes",
            vec![
                ("values", vec![values_t(), nat_t()]),
                ("overflow", vec![nat_t()]),
                ("stuck", vec![]),
                ("exhausted", vec![]),
            ],
        ),
    ]
}

fn add_steps() -> Json {
    definition(
        "addSteps",
        vec![
            parameter("result", outcome_t()),
            parameter("extra", nat_t()),
        ],
        outcome_t(),
        outcome_match(
            var("result"),
            Family::One,
            (
                &["computed", "steps"],
                produced(var("computed"), add(var("steps"), var("extra"))),
            ),
            (
                &["steps"],
                outcome("overflow", vec![add(var("steps"), var("extra"))]),
            ),
            stuck(),
            exhausted(),
        ),
    )
}

/// The innermost binding of a local wins: `let` and `bindAll` push to the
/// front.
fn lookup() -> Json {
    recursive(
        "environment",
        definition(
            "lookup",
            vec![
                parameter("environment", environment_t()),
                parameter("name", nat_t()),
            ],
            option_t(value_t()),
            list_match(
                var("environment"),
                none(value_t()),
                "entry",
                "rest",
                ite(
                    beq(first(var("entry")), var("name")),
                    some(value_t(), second(var("entry"))),
                    call("lookup", vec![var("rest"), var("name")]),
                ),
            ),
        ),
    )
}

/// The number of bindings a lookup of `name` examines before it finds
/// one: what reading a local costs beyond its own step.
fn depth() -> Json {
    recursive(
        "environment",
        definition(
            "depth",
            vec![
                parameter("environment", environment_t()),
                parameter("name", nat_t()),
            ],
            nat_t(),
            list_match(
                var("environment"),
                nat(0),
                "entry",
                "rest",
                ite(
                    beq(first(var("entry")), var("name")),
                    nat(0),
                    add(nat(1), call("depth", vec![var("rest"), var("name")])),
                ),
            ),
        ),
    )
}

/// A value's weight: one per node, and a string's characters or a byte
/// string's bytes. Every primitive is charged the weights of its operands
/// and of its result, so no primitive's work goes uncounted (§17.14).
fn weight(s: &Semantics) -> Json {
    let one_more_than = |term: Json| add(nat(1), term);
    let of = |binder: &str| call("weight", vec![var(binder)]);
    let of_all = |binder: &str| call("weights", vec![var(binder)]);
    let tag = s.ignored();
    let callee = s.ignored();
    let cases = vec![
        on(
            "string",
            &["text"],
            one_more_than(prim("length", vec![var("text")], nat_t())),
        ),
        on(
            "bytes",
            &["octets"],
            one_more_than(prim("length", vec![var("octets")], nat_t())),
        ),
        on("some", &["inner"], one_more_than(of("inner"))),
        on("ok", &["inner"], one_more_than(of("inner"))),
        on("error", &["inner"], one_more_than(of("inner"))),
        on("list", &["items"], one_more_than(of_all("items"))),
        on(
            "pair",
            &["left", "right"],
            one_more_than(add(of("left"), of("right"))),
        ),
        on("adt", &[&tag, "fields"], one_more_than(of_all("fields"))),
        on(
            "closure",
            &[&callee, "captured"],
            one_more_than(of_all("captured")),
        ),
    ];
    axioms(
        CLASSICAL,
        mutual(
            "Weight",
            recursive(
                "value",
                definition(
                    "weight",
                    vec![parameter("value", value_t())],
                    nat_t(),
                    s.value_match(var("value"), cases, nat(1)),
                ),
            ),
        ),
    )
}

/// The weights of a list of values.
fn weights() -> Json {
    axioms(
        CLASSICAL,
        mutual(
            "Weight",
            recursive(
                "values",
                definition(
                    "weights",
                    vec![parameter("values", values_t())],
                    nat_t(),
                    list_match(
                        var("values"),
                        nat(0),
                        "head",
                        "tail",
                        add(
                            call("weight", vec![var("head")]),
                            call("weights", vec![var("tail")]),
                        ),
                    ),
                ),
            ),
        ),
    )
}

/// A primitive's outcome charged `extra` steps and, when it produced a
/// value, that value's weight.
fn charge_result() -> Json {
    axioms(
        CLASSICAL,
        definition(
            "chargeResult",
            vec![
                parameter("result", outcome_t()),
                parameter("extra", nat_t()),
            ],
            outcome_t(),
            outcome_match(
                var("result"),
                Family::One,
                (
                    &["computed", "steps"],
                    produced(
                        var("computed"),
                        add(
                            add(var("steps"), var("extra")),
                            call("weight", vec![var("computed")]),
                        ),
                    ),
                ),
                (
                    &["steps"],
                    outcome("overflow", vec![add(var("steps"), var("extra"))]),
                ),
                stuck(),
                exhausted(),
            ),
        ),
    )
}

/// Bind names to values pairwise; a length mismatch is `none`.
fn bind_all(s: &Semantics) -> Json {
    recursive(
        "names",
        definition(
            "bindAll",
            vec![
                parameter("names", list_t(nat_t())),
                parameter("values", values_t()),
                parameter("environment", environment_t()),
            ],
            option_t(environment_t()),
            list_match(
                var("names"),
                list_match(
                    var("values"),
                    some(environment_t(), var("environment")),
                    &s.ignored(),
                    &s.ignored(),
                    none(environment_t()),
                ),
                "name",
                "names2",
                list_match(
                    var("values"),
                    none(environment_t()),
                    "value",
                    "values2",
                    call(
                        "bindAll",
                        vec![
                            var("names2"),
                            var("values2"),
                            cons(pair_of("name", "value"), var("environment")),
                        ],
                    ),
                ),
            ),
        ),
    )
}

fn pair_of(left: &str, right: &str) -> Json {
    pair(var(left), var(right))
}

/// A `nat` result is realized in `[0, 2^64)`; beyond it is `overflow`,
/// never a wrapped value.
fn nat_result() -> Json {
    definition(
        "natResult",
        vec![parameter("number", nat_t())],
        outcome_t(),
        ite(
            blt(var("number"), nat_wide(1 << 64)),
            done(value("nat", vec![var("number")])),
            outcome("overflow", vec![nat(0)]),
        ),
    )
}

/// An `int` result is realized in the 64-bit two's complement range.
fn int_result() -> Json {
    axioms(
        &["Quot.sound", "propext"],
        definition(
            "intResult",
            vec![parameter("number", int_t())],
            outcome_t(),
            option_match(
                prim(
                    "checked_convert",
                    vec![var("number")],
                    option_t(scalar_t("int64")),
                ),
                outcome("overflow", vec![nat(0)]),
                "bounded",
                done(value("int", vec![var("number")])),
            ),
        ),
    )
}

// --- TargetSemantics: the key order ----------------------------------------

/// LexLean has no `Ordering` literal and no match on `Ordering`; a
/// `compare_bytes` result is classified against the orderings
/// `compare_bytes` itself yields.
fn from_ordering() -> Json {
    let ordering = || scalar_t("ordering");
    let is = |sample: Json| prim("equal", vec![var("order"), sample], bool_t());
    axioms(
        &["propext"],
        definition(
            "fromOrdering",
            vec![parameter("order", ordering())],
            order_t(),
            ite(
                is(prim(
                    "compare_bytes",
                    vec![bytes("00"), bytes("01")],
                    ordering(),
                )),
                order("less"),
                ite(
                    is(prim(
                        "compare_bytes",
                        vec![bytes(""), bytes("")],
                        ordering(),
                    )),
                    order("same"),
                    order("more"),
                ),
            ),
        ),
    )
}

fn same_order() -> Json {
    let row = |less: bool, same: bool, more: bool| {
        order_match(var("right"), boolean(less), boolean(same), boolean(more))
    };
    definition(
        "sameOrder",
        vec![parameter("left", order_t()), parameter("right", order_t())],
        bool_t(),
        order_match(
            var("left"),
            row(true, false, false),
            row(false, true, false),
            row(false, false, true),
        ),
    )
}

/// The positions of the two inserted keys, in LexLean's own key order: the
/// left key was inserted with 0, so it leads exactly when it is less, and
/// equal keys collapse to one entry.
fn order_of(s: &Semantics) -> Json {
    definition(
        "orderOf",
        vec![parameter("positions", list_t(nat_t()))],
        order_t(),
        list_match(
            var("positions"),
            order("same"),
            "leading",
            "rest",
            list_match(
                var("rest"),
                order("same"),
                &s.ignored(),
                &s.ignored(),
                ite(beq(var("leading"), nat(0)), order("less"), order("more")),
            ),
        ),
    )
}

/// The name of the definition ordering two keys of `Value.<constructor>`.
fn key_order(constructor: &str) -> String {
    let mut characters = constructor.chars();
    let initial = characters.next().map(|c| c.to_ascii_uppercase());
    format!(
        "order{}{}",
        initial.into_iter().collect::<String>(),
        characters.as_str()
    )
}

/// Two keys ordered by inserting them into a LexLean map and reading back
/// the order of their values, so `compare` is LexLean's own key order by
/// construction rather than a second definition of it.
fn key_orders() -> Vec<Json> {
    KEYS.iter()
        .map(|&(constructor, kind, policy)| {
            let key = || scalar_t(kind);
            let map = || map_t(key(), nat_t());
            let inserted = prim(
                "map_insert",
                vec![
                    prim(
                        "map_insert",
                        vec![
                            map_literal(key(), nat_t(), Vec::new()),
                            var("leftKey"),
                            nat(0),
                        ],
                        map(),
                    ),
                    var("rightKey"),
                    nat(1),
                ],
                map(),
            );
            let declaration = definition(
                &key_order(constructor),
                vec![parameter("leftKey", key()), parameter("rightKey", key())],
                order_t(),
                call(
                    "orderOf",
                    vec![prim("map_values", vec![inserted], list_t(nat_t()))],
                ),
            );
            if policy.is_empty() {
                declaration
            } else {
                axioms(policy, declaration)
            }
        })
        .collect()
}

/// `compare` on two values: keys of one type by their key order, pairs and
/// lists lexicographically; values of different types are unordered.
fn compare_value(s: &Semantics) -> Json {
    let unordered = || none(order_t());
    let mut cases: Vec<Case> = KEYS
        .iter()
        .map(|&(constructor, _, _)| {
            on(
                constructor,
                &["leftKey"],
                s.value_match(
                    var("right"),
                    vec![on(
                        constructor,
                        &["rightKey"],
                        some(
                            order_t(),
                            call(
                                &key_order(constructor),
                                vec![var("leftKey"), var("rightKey")],
                            ),
                        ),
                    )],
                    unordered(),
                ),
            )
        })
        .collect();
    cases.push(on(
        "pair",
        &["leftFirst", "leftSecond"],
        s.value_match(
            var("right"),
            vec![on(
                "pair",
                &["rightFirst", "rightSecond"],
                option_match(
                    call("compareValue", vec![var("leftFirst"), var("rightFirst")]),
                    unordered(),
                    "firstOrder",
                    order_match(
                        var("firstOrder"),
                        some(order_t(), order("less")),
                        call("compareValue", vec![var("leftSecond"), var("rightSecond")]),
                        some(order_t(), order("more")),
                    ),
                ),
            )],
            unordered(),
        ),
    ));
    cases.push(on(
        "list",
        &["leftItems"],
        s.value_match(
            var("right"),
            vec![on(
                "list",
                &["rightItems"],
                call("compareValues", vec![var("leftItems"), var("rightItems")]),
            )],
            unordered(),
        ),
    ));
    axioms(
        CLASSICAL,
        mutual(
            "Comparison",
            recursive(
                "left",
                definition(
                    "compareValue",
                    vec![parameter("left", value_t()), parameter("right", value_t())],
                    option_t(order_t()),
                    s.value_match(var("left"), cases, unordered()),
                ),
            ),
        ),
    )
}

/// Lists lexicographically: a proper prefix is less.
fn compare_values(s: &Semantics) -> Json {
    let ordered = |constructor: &str| some(order_t(), order(constructor));
    axioms(
        CLASSICAL,
        mutual(
            "Comparison",
            recursive(
                "left",
                definition(
                    "compareValues",
                    vec![
                        parameter("left", values_t()),
                        parameter("right", values_t()),
                    ],
                    option_t(order_t()),
                    list_match(
                        var("left"),
                        list_match(
                            var("right"),
                            ordered("same"),
                            &s.ignored(),
                            &s.ignored(),
                            ordered("less"),
                        ),
                        "leftHead",
                        "leftTail",
                        list_match(
                            var("right"),
                            ordered("more"),
                            "rightHead",
                            "rightTail",
                            option_match(
                                call("compareValue", vec![var("leftHead"), var("rightHead")]),
                                none(order_t()),
                                "headOrder",
                                order_match(
                                    var("headOrder"),
                                    ordered("less"),
                                    call("compareValues", vec![var("leftTail"), var("rightTail")]),
                                    ordered("more"),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    )
}

// --- TargetSemantics: shapes -----------------------------------------------

/// The fields a shape binds when `value` has that shape, or `none`: what a
/// `match` arm sees.
fn destruct(s: &Semantics) -> Json {
    let fields = |items: Vec<Json>| some_values(values(items));
    let is_order = |constructor: &str| {
        on(
            "ordering",
            &["order"],
            ite(
                call("sameOrder", vec![var("order"), order(constructor)]),
                fields(vec![]),
                no_values(),
            ),
        )
    };
    let one = |constructor: &'static str, case: Case| {
        on(
            constructor,
            &[],
            s.value_match(var("value"), vec![case], no_values()),
        )
    };
    let mut cases = vec![
        one("none", on("none", &[], fields(vec![]))),
        one("some", on("some", &["inner"], fields(vec![var("inner")]))),
        one("ok", on("ok", &["inner"], fields(vec![var("inner")]))),
        one("error", on("error", &["inner"], fields(vec![var("inner")]))),
        one(
            "nil",
            on(
                "list",
                &["items"],
                list_match(
                    var("items"),
                    fields(vec![]),
                    &s.ignored(),
                    &s.ignored(),
                    no_values(),
                ),
            ),
        ),
        one(
            "cons",
            on(
                "list",
                &["items"],
                list_match(
                    var("items"),
                    no_values(),
                    "head",
                    "tail",
                    fields(vec![var("head"), value("list", vec![var("tail")])]),
                ),
            ),
        ),
        one(
            "zero",
            on(
                "nat",
                &["number"],
                ite(beq(var("number"), nat(0)), fields(vec![]), no_values()),
            ),
        ),
        one(
            "succ",
            on(
                "nat",
                &["number"],
                ite(
                    beq(var("number"), nat(0)),
                    no_values(),
                    fields(vec![value(
                        "nat",
                        vec![prim("subtract", vec![var("number"), nat(1)], nat_t())],
                    )]),
                ),
            ),
        ),
        one(
            "pair",
            on(
                "pair",
                &["left", "right"],
                fields(vec![var("left"), var("right")]),
            ),
        ),
        one(
            "true",
            on(
                "bool",
                &["flag"],
                ite(var("flag"), fields(vec![]), no_values()),
            ),
        ),
        one(
            "false",
            on(
                "bool",
                &["flag"],
                ite(var("flag"), no_values(), fields(vec![])),
            ),
        ),
        one("unit", on("unit", &[], fields(vec![]))),
        one("lt", is_order("less")),
        one("eq", is_order("same")),
        one("gt", is_order("more")),
    ];
    cases.push(on(
        "adt",
        &["constructor"],
        s.value_match(
            var("value"),
            vec![on(
                "adt",
                &["tag", "fields"],
                ite(
                    beq(var("tag"), var("constructor")),
                    some_values(var("fields")),
                    no_values(),
                ),
            )],
            no_values(),
        ),
    ));
    definition(
        "destruct",
        vec![
            parameter("shape", syntax_t("Shape")),
            parameter("value", value_t()),
        ],
        option_t(values_t()),
        exhaustive(var("shape"), "Shape", &shape_constructors(), cases),
    )
}

/// The value a `build` of a shape makes from its operands.
fn construct(s: &Semantics) -> Json {
    let empty = |result: Json| s.operands(|[]| done(result));
    let unary =
        |constructor: &'static str| s.operands(|[operand]| done(value(constructor, vec![operand])));
    let mut cases = vec![
        on("none", &[], empty(value("none", vec![]))),
        on("some", &[], unary("some")),
        on("ok", &[], unary("ok")),
        on("error", &[], unary("error")),
        on("nil", &[], empty(value("list", vec![nil(value_t())]))),
        on(
            "cons",
            &[],
            s.operands(|[head, tail]| {
                s.value_match(
                    tail,
                    vec![on(
                        "list",
                        &["items"],
                        done(value("list", vec![cons(head, var("items"))])),
                    )],
                    stuck(),
                )
            }),
        ),
        on("zero", &[], empty(value("nat", vec![nat(0)]))),
        on(
            "succ",
            &[],
            s.operands(|[number]| {
                s.value_match(
                    number,
                    vec![on(
                        "nat",
                        &["number"],
                        call("natResult", vec![add(var("number"), nat(1))]),
                    )],
                    stuck(),
                )
            }),
        ),
        on(
            "pair",
            &[],
            s.operands(|[left, right]| done(value("pair", vec![left, right]))),
        ),
        on("true", &[], empty(value("bool", vec![boolean(true)]))),
        on("false", &[], empty(value("bool", vec![boolean(false)]))),
        on("unit", &[], empty(value("unit", vec![]))),
        on("lt", &[], empty(value("ordering", vec![order("less")]))),
        on("eq", &[], empty(value("ordering", vec![order("same")]))),
        on("gt", &[], empty(value("ordering", vec![order("more")]))),
    ];
    cases.push(on(
        "adt",
        &["constructor"],
        done(value("adt", vec![var("constructor"), var("values")])),
    ));
    definition(
        "construct",
        vec![
            parameter("shape", syntax_t("Shape")),
            parameter("values", values_t()),
        ],
        outcome_t(),
        exhaustive(var("shape"), "Shape", &shape_constructors(), cases),
    )
}

// --- TargetSemantics: primitives -------------------------------------------

fn from_strings() -> Json {
    recursive(
        "texts",
        definition(
            "fromStrings",
            vec![parameter("texts", list_t(string_t()))],
            values_t(),
            list_match(
                var("texts"),
                nil(value_t()),
                "text",
                "rest",
                cons(
                    value("string", vec![var("text")]),
                    call("fromStrings", vec![var("rest")]),
                ),
            ),
        ),
    )
}

/// The texts of a list of `Value.string`s; any other element is `none`.
fn to_strings(s: &Semantics) -> Json {
    let texts = || list_t(string_t());
    recursive(
        "values",
        definition(
            "toStrings",
            vec![parameter("values", values_t())],
            option_t(texts()),
            list_match(
                var("values"),
                some(texts(), nil(string_t())),
                "value",
                "rest",
                s.value_match(
                    var("value"),
                    vec![on(
                        "string",
                        &["text"],
                        option_match(
                            call("toStrings", vec![var("rest")]),
                            none(texts()),
                            "texts",
                            some(texts(), cons(var("text"), var("texts"))),
                        ),
                    )],
                    none(texts()),
                ),
            ),
        ),
    )
}

/// Every primitive by reference to the language-1.2 primitive of the same
/// meaning (§17.14), so a value of the calculus means what LexLean says it
/// means. Ill-typed operands are stuck, which a valid program never is.
#[allow(clippy::too_many_lines)]
fn primitive(s: &Semantics) -> Json {
    let nat2 = |body: fn(Json, Json) -> Json| {
        s.operands_of("nat", ["leftNumber", "rightNumber"], |[a, b]| body(a, b))
    };
    let nat3 = |body: fn(Json, Json, Json) -> Json| {
        s.operands_of(
            "nat",
            ["leftNumber", "rightNumber", "zeroNumber"],
            |[a, b, zero]| body(a, b, zero),
        )
    };
    let int2 = |body: fn(Json, Json) -> Json| {
        s.operands_of("int", ["leftNumber", "rightNumber"], |[a, b]| body(a, b))
    };
    let int3 = |body: fn(Json, Json, Json) -> Json| {
        s.operands_of(
            "int",
            ["leftNumber", "rightNumber", "zeroNumber"],
            |[a, b, zero]| body(a, b, zero),
        )
    };
    let bool2 = |connective: fn(Json, Json) -> Json| {
        s.operands_of("bool", ["leftFlag", "rightFlag"], |[a, b]| {
            done(value("bool", vec![connective(a, b)]))
        })
    };
    let bool_value = |flag: Json| done(value("bool", vec![flag]));
    let nat_result = |number: Json| call("natResult", vec![number]);
    let int_result = |number: Json| call("intResult", vec![number]);
    let nat_op = |operation: &str, operands: Vec<Json>| prim(operation, operands, nat_t());
    let int_op = |operation: &str, operands: Vec<Json>| prim(operation, operands, int_t());
    let absent = || done(value("none", vec![]));
    let present = |inner: Json| done(value("some", vec![inner]));

    // Built in this order, which fixes the numbering of their binders;
    // `exhaustive` emits them in `Prim`'s declaration order.
    let mut cases = vec![
        on(
            "natAdd",
            &[],
            nat2(|a, b| call("natResult", vec![add(a, b)])),
        ),
        on(
            "natSub",
            &[],
            nat2(|a, b| done(value("nat", vec![prim("subtract", vec![a, b], nat_t())]))),
        ),
        on(
            "natMul",
            &[],
            nat2(|a, b| call("natResult", vec![prim("multiply", vec![a, b], nat_t())])),
        ),
        on(
            "natQuot",
            &[],
            nat3(|a, b, zero| {
                done(value(
                    "nat",
                    vec![prim("quotient", vec![a, b, zero], nat_t())],
                ))
            }),
        ),
        on(
            "natRem",
            &[],
            nat3(|a, b, zero| {
                done(value(
                    "nat",
                    vec![prim("remainder", vec![a, b, zero], nat_t())],
                ))
            }),
        ),
        on(
            "natEq",
            &[],
            nat2(|a, b| done(value("bool", vec![beq(a, b)]))),
        ),
        on(
            "natLe",
            &[],
            nat2(|a, b| done(value("bool", vec![ble(a, b)]))),
        ),
        on(
            "natLt",
            &[],
            nat2(|a, b| done(value("bool", vec![blt(a, b)]))),
        ),
        // `a + b` is `a - (-b)`: LexLean's `int` has subtraction and negation
        // as primitives, and `add` is natural addition only.
        on(
            "intAdd",
            &[],
            int2(|a, b| {
                call(
                    "intResult",
                    vec![prim(
                        "subtract",
                        vec![a, prim("negate", vec![b], int_t())],
                        int_t(),
                    )],
                )
            }),
        ),
        on(
            "intSub",
            &[],
            int2(|a, b| call("intResult", vec![prim("subtract", vec![a, b], int_t())])),
        ),
        on(
            "intMul",
            &[],
            int2(|a, b| call("intResult", vec![prim("multiply", vec![a, b], int_t())])),
        ),
        on(
            "intNeg",
            &[],
            s.operands_of("int", ["leftNumber"], |[a]| {
                int_result(int_op("negate", vec![a]))
            }),
        ),
        on(
            "intQuot",
            &[],
            int3(|a, b, zero| {
                call(
                    "intResult",
                    vec![prim("quotient", vec![a, b, zero], int_t())],
                )
            }),
        ),
        on(
            "intRem",
            &[],
            int3(|a, b, zero| {
                call(
                    "intResult",
                    vec![prim("remainder", vec![a, b, zero], int_t())],
                )
            }),
        ),
        on("checkedAdd", &[], s.checked("checked_add")),
        on("checkedSub", &[], s.checked("checked_subtract")),
        on("checkedMul", &[], s.checked("checked_multiply")),
        on("checkedQuot", &[], s.checked("checked_quotient")),
        on(
            "checkedNeg",
            &[],
            s.fixed_one(&SIGNED, |number, name, kind| {
                optional(
                    prim("checked_negate", vec![number], option_t(scalar_t(kind))),
                    name,
                )
            }),
        ),
        on("bitAnd", &[], s.bitwise("bit_and")),
        on("bitOr", &[], s.bitwise("bit_or")),
        on("bitXor", &[], s.bitwise("bit_xor")),
        on(
            "bitNot",
            &[],
            s.fixed_one(&FIXED, |number, name, kind| {
                done(value(
                    name,
                    vec![prim("bit_not", vec![number], scalar_t(kind))],
                ))
            }),
        ),
        on("shiftLeft", &[], s.shift("shift_left")),
        on("shiftRight", &[], s.shift("shift_right")),
        on("equal", &[], equal(s)),
        on(
            "boolNot",
            &[],
            s.operands_of("bool", ["flag"], |[flag]| bool_value(not(flag))),
        ),
        on("boolAnd", &[], bool2(and)),
        on("boolOr", &[], bool2(or)),
        on(
            "append",
            &[],
            s.operands(|[left, right]| {
                let list_case = on(
                    "list",
                    &["leftItems"],
                    s.value_match(
                        right.clone(),
                        vec![on(
                            "list",
                            &["rightItems"],
                            done(value(
                                "list",
                                vec![prim(
                                    "append",
                                    vec![var("leftItems"), var("rightItems")],
                                    values_t(),
                                )],
                            )),
                        )],
                        stuck(),
                    ),
                );
                let bytes_case = on(
                    "bytes",
                    &["leftBytes"],
                    s.value_match(
                        right,
                        vec![on(
                            "bytes",
                            &["rightBytes"],
                            done(value(
                                "bytes",
                                vec![prim(
                                    "append",
                                    vec![var("leftBytes"), var("rightBytes")],
                                    scalar_t("bytes"),
                                )],
                            )),
                        )],
                        stuck(),
                    ),
                );
                s.value_match(left, vec![list_case, bytes_case], stuck())
            }),
        ),
        on(
            "length",
            &[],
            s.operands(|[operand]| {
                let length = |binder: &str| nat_result(nat_op("length", vec![var(binder)]));
                s.value_match(
                    operand,
                    vec![
                        on("list", &["items"], length("items")),
                        on("bytes", &["octets"], length("octets")),
                        on("string", &["text"], length("text")),
                    ],
                    stuck(),
                )
            }),
        ),
        on(
            "index",
            &[],
            s.operands(|[sequence, position]| {
                let by_sequence = s.value_match(
                    sequence,
                    vec![
                        on(
                            "list",
                            &["items"],
                            option_match(
                                prim(
                                    "index",
                                    vec![var("items"), var("position")],
                                    option_t(value_t()),
                                ),
                                absent(),
                                "item",
                                present(var("item")),
                            ),
                        ),
                        on(
                            "bytes",
                            &["octets"],
                            optional(
                                prim(
                                    "index",
                                    vec![var("octets"), var("position")],
                                    option_t(scalar_t("uint8")),
                                ),
                                "u8",
                            ),
                        ),
                    ],
                    stuck(),
                );
                s.value_match(
                    position,
                    vec![on("nat", &["position"], by_sequence)],
                    stuck(),
                )
            }),
        ),
        on(
            "slice",
            &[],
            s.operands(|[sequence, start, stop]| {
                let part = |binder: &str, ty: Json, wrap: &str| {
                    option_match(
                        prim(
                            "slice",
                            vec![var(binder), var("start"), var("stop")],
                            option_t(ty),
                        ),
                        absent(),
                        "part",
                        present(value(wrap, vec![var("part")])),
                    )
                };
                let by_sequence = s.value_match(
                    sequence,
                    vec![
                        on("list", &["items"], part("items", values_t(), "list")),
                        on(
                            "bytes",
                            &["octets"],
                            part("octets", scalar_t("bytes"), "bytes"),
                        ),
                    ],
                    stuck(),
                );
                let by_stop = s.value_match(stop, vec![on("nat", &["stop"], by_sequence)], stuck());
                s.value_match(start, vec![on("nat", &["start"], by_stop)], stuck())
            }),
        ),
        on(
            "utf8Encode",
            &[],
            s.operands_of("string", ["text"], |[text]| {
                done(value(
                    "bytes",
                    vec![prim("utf8_encode", vec![text], scalar_t("bytes"))],
                ))
            }),
        ),
        on(
            "utf8Decode",
            &[],
            s.operands_of("bytes", ["octets"], |[octets]| {
                option_match(
                    prim("utf8_decode", vec![octets], option_t(string_t())),
                    absent(),
                    "text",
                    present(value("string", vec![var("text")])),
                )
            }),
        ),
        on(
            "compareBytes",
            &[],
            s.operands_of("bytes", ["leftBytes", "rightBytes"], |[left, right]| {
                done(value(
                    "ordering",
                    vec![call(
                        "fromOrdering",
                        vec![prim(
                            "compare_bytes",
                            vec![left, right],
                            scalar_t("ordering"),
                        )],
                    )],
                ))
            }),
        ),
        on(
            "splitExact",
            &[],
            s.operands(|[text, separator, count]| {
                let split = option_match(
                    prim(
                        "split_exact",
                        vec![var("text"), var("separator"), var("count")],
                        option_t(list_t(string_t())),
                    ),
                    absent(),
                    "parts",
                    present(value("list", vec![call("fromStrings", vec![var("parts")])])),
                );
                let by_count = s.value_match(count, vec![on("u32", &["count"], split)], stuck());
                let by_separator = s.value_match(
                    separator,
                    vec![on("string", &["separator"], by_count)],
                    stuck(),
                );
                s.value_match(text, vec![on("string", &["text"], by_separator)], stuck())
            }),
        ),
        on(
            "join",
            &[],
            s.operands(|[items, separator]| {
                let joined = option_match(
                    call("toStrings", vec![var("items")]),
                    stuck(),
                    "texts",
                    done(value(
                        "string",
                        vec![prim(
                            "join",
                            vec![var("texts"), var("separator")],
                            string_t(),
                        )],
                    )),
                );
                let by_separator = s.value_match(
                    separator,
                    vec![on("string", &["separator"], joined)],
                    stuck(),
                );
                s.value_match(items, vec![on("list", &["items"], by_separator)], stuck())
            }),
        ),
        on(
            "formatDecimal",
            &[],
            s.operands(|[number]| {
                let cases = INTEGERS
                    .iter()
                    .map(|source| {
                        on(
                            source,
                            &["source"],
                            done(value(
                                "string",
                                vec![prim("format_decimal", vec![var("source")], string_t())],
                            )),
                        )
                    })
                    .collect();
                s.value_match(number, cases, stuck())
            }),
        ),
        on(
            "compare",
            &[],
            s.operands(|[left, right]| {
                option_match(
                    call("compareValue", vec![left, right]),
                    stuck(),
                    "order",
                    done(value("ordering", vec![var("order")])),
                )
            }),
        ),
    ];
    cases.push(on("convert", &["target"], convert(s)));
    cases.push(on("parseDecimal", &["target"], parse_decimal(s)));
    axioms(
        CLASSICAL,
        definition(
            "primitive",
            vec![
                parameter("operation", syntax_t("Prim")),
                parameter("values", values_t()),
            ],
            outcome_t(),
            exhaustive(var("operation"), "Prim", &prim_constructors(), cases),
        ),
    )
}

/// Scalar equality. The cases are built before the operands are named, so
/// they read the right operand through the `let` that binds it.
fn equal(s: &Semantics) -> Json {
    let right_value = || var("rightValue0");
    let mut cases: Vec<Case> = EQUATABLE
        .iter()
        .map(|constructor| {
            on(
                constructor,
                &["leftValue"],
                s.value_match(
                    right_value(),
                    vec![on(
                        constructor,
                        &["rightValue"],
                        done(value(
                            "bool",
                            vec![prim(
                                "equal",
                                vec![var("leftValue"), var("rightValue")],
                                bool_t(),
                            )],
                        )),
                    )],
                    stuck(),
                ),
            )
        })
        .collect();
    // `Order` is the calculus's own type, so its equality is `sameOrder`.
    cases.push(on(
        "ordering",
        &["leftOrder"],
        s.value_match(
            right_value(),
            vec![on(
                "ordering",
                &["rightOrder"],
                done(value(
                    "bool",
                    vec![call("sameOrder", vec![var("leftOrder"), var("rightOrder")])],
                )),
            )],
            stuck(),
        ),
    ));
    s.operands(|[left, right]| {
        let_in(
            "rightValue0",
            value_t(),
            right,
            s.value_match(left, cases, stuck()),
        )
    })
}

/// Checked conversion of any integer to the `target` width: out of range is
/// `Value.none`.
fn convert(s: &Semantics) -> Json {
    s.operands(|[operand]| {
        kind_match(var("target"), |name, kind| {
            let cases = INTEGERS
                .iter()
                .map(|source| {
                    on(
                        source,
                        &["source"],
                        optional(
                            prim(
                                "checked_convert",
                                vec![var("source")],
                                option_t(scalar_t(kind)),
                            ),
                            name,
                        ),
                    )
                })
                .collect();
            s.value_match(operand.clone(), cases, stuck())
        })
    })
}

/// Decimal parsing into an `int` or a fixed width. Unparsable text is
/// `Value.none`; an `int` outside its realization overflows, as every
/// `int` result does; any other target type is stuck.
fn parse_decimal(s: &Semantics) -> Json {
    s.operands_of("string", ["text"], |[text]| {
        let int_case = option_match(
            prim("parse_decimal", vec![text.clone()], option_t(int_t())),
            done(value("none", vec![])),
            "parsed",
            option_match(
                prim(
                    "checked_convert",
                    vec![var("parsed")],
                    option_t(scalar_t("int64")),
                ),
                outcome("overflow", vec![nat(0)]),
                "bounded",
                done(value("some", vec![value("int", vec![var("parsed")])])),
            ),
        );
        let fixed_case = kind_match(var("kind"), |name, kind| {
            optional(
                prim(
                    "parse_decimal",
                    vec![text.clone()],
                    option_t(scalar_t(kind)),
                ),
                name,
            )
        });
        s.type_match(
            var("target"),
            vec![on("int", &[], int_case), on("fixed", &["kind"], fixed_case)],
            stuck(),
        )
    })
}

// --- TargetSemantics: evaluation -------------------------------------------

/// `eval` of `expression` in `environment` with the remaining fuel.
fn eval(environment: Json, expression: Json) -> Json {
    call(
        "eval",
        vec![var("remaining"), var("program"), environment, expression],
    )
}

fn eval_list(expressions: Json) -> Json {
    call(
        "evalList",
        vec![
            var("remaining"),
            var("program"),
            var("environment"),
            expressions,
        ],
    )
}

fn one_more(steps: &str) -> Json {
    add(var(steps), nat(1))
}

/// One step per evaluated node, charged on top of the steps its operands
/// took, and every operation the evaluator performs beyond it (§17.14): the
/// bindings a local's lookup examines, each arm a match tries, a closure's
/// captures passed on application, the fields a projection skips, and a
/// primitive's operand and result weights.
#[allow(clippy::too_many_lines)]
fn expression_cases(s: &Semantics) -> Vec<Case> {
    let environment = || var("environment");
    vec![
        on(
            "value",
            &["literalType", "literal"],
            produced(var("literal"), nat(1)),
        ),
        on(
            "var",
            &["name"],
            option_match(
                call("lookup", vec![environment(), var("name")]),
                stuck(),
                "found",
                produced(
                    var("found"),
                    add(nat(1), call("depth", vec![environment(), var("name")])),
                ),
            ),
        ),
        on(
            "let",
            &["name", "boundType", "bound", "body"],
            s.propagate(
                Family::One,
                eval(environment(), var("bound")),
                ["boundValue", "boundSteps"],
                call(
                    "addSteps",
                    vec![
                        eval(
                            cons(pair_of("name", "boundValue"), environment()),
                            var("body"),
                        ),
                        one_more("boundSteps"),
                    ],
                ),
            ),
        ),
        on(
            "cond",
            &["condition", "thenBranch", "elseBranch"],
            s.propagate(
                Family::One,
                eval(environment(), var("condition")),
                ["conditionValue", "conditionSteps"],
                s.value_match(
                    var("conditionValue"),
                    vec![on(
                        "bool",
                        &["flag"],
                        call(
                            "addSteps",
                            vec![
                                ite(
                                    var("flag"),
                                    eval(environment(), var("thenBranch")),
                                    eval(environment(), var("elseBranch")),
                                ),
                                one_more("conditionSteps"),
                            ],
                        ),
                    )],
                    stuck(),
                ),
            ),
        ),
        on(
            "match",
            &["resultType", "scrutinee", "arms"],
            s.propagate(
                Family::One,
                eval(environment(), var("scrutinee")),
                ["scrutineeValue", "scrutineeSteps"],
                call(
                    "addSteps",
                    vec![
                        call(
                            "evalArms",
                            vec![
                                var("remaining"),
                                var("program"),
                                environment(),
                                var("scrutineeValue"),
                                var("arms"),
                            ],
                        ),
                        one_more("scrutineeSteps"),
                    ],
                ),
            ),
        ),
        on(
            "build",
            &["shape", "builtType", "operands"],
            s.propagate(
                Family::Many,
                eval_list(var("operands")),
                ["operandValues", "operandSteps"],
                call(
                    "addSteps",
                    vec![
                        call("construct", vec![var("shape"), var("operandValues")]),
                        one_more("operandSteps"),
                    ],
                ),
            ),
        ),
        on(
            "call",
            &["callee", "operands"],
            s.propagate(
                Family::Many,
                eval_list(var("operands")),
                ["operandValues", "operandSteps"],
                s.function_call(
                    var("callee"),
                    var("operandValues"),
                    one_more("operandSteps"),
                ),
            ),
        ),
        on(
            "closure",
            &["callee", "captures"],
            s.propagate(
                Family::Many,
                eval_list(var("captures")),
                ["captured", "captureSteps"],
                produced(
                    value("closure", vec![var("callee"), var("captured")]),
                    one_more("captureSteps"),
                ),
            ),
        ),
        // A closure's captures are passed before the operands.
        on(
            "apply",
            &["target", "operands"],
            s.propagate(
                Family::One,
                eval(environment(), var("target")),
                ["targetValue", "targetSteps"],
                s.value_match(
                    var("targetValue"),
                    vec![on(
                        "closure",
                        &["callee", "captured"],
                        s.propagate(
                            Family::Many,
                            eval_list(var("operands")),
                            ["operandValues", "operandSteps"],
                            s.function_call(
                                var("callee"),
                                prim(
                                    "append",
                                    vec![var("captured"), var("operandValues")],
                                    values_t(),
                                ),
                                add(
                                    add(add(var("targetSteps"), var("operandSteps")), nat(1)),
                                    prim("length", vec![var("captured")], nat_t()),
                                ),
                            ),
                        ),
                    )],
                    stuck(),
                ),
            ),
        ),
        on(
            "prim",
            &["operation", "operands"],
            s.propagate(
                Family::Many,
                eval_list(var("operands")),
                ["operandValues", "operandSteps"],
                call(
                    "chargeResult",
                    vec![
                        call("primitive", vec![var("operation"), var("operandValues")]),
                        add(
                            one_more("operandSteps"),
                            call("weights", vec![var("operandValues")]),
                        ),
                    ],
                ),
            ),
        ),
        on(
            "first",
            &["inner"],
            s.propagate(
                Family::One,
                eval(environment(), var("inner")),
                ["innerValue", "innerSteps"],
                s.value_match(
                    var("innerValue"),
                    vec![on(
                        "pair",
                        &["left", "right"],
                        produced(var("left"), one_more("innerSteps")),
                    )],
                    stuck(),
                ),
            ),
        ),
        on(
            "second",
            &["inner"],
            s.propagate(
                Family::One,
                eval(environment(), var("inner")),
                ["innerValue", "innerSteps"],
                s.value_match(
                    var("innerValue"),
                    vec![on(
                        "pair",
                        &["left", "right"],
                        produced(var("right"), one_more("innerSteps")),
                    )],
                    stuck(),
                ),
            ),
        ),
        on(
            "field",
            &["inner", "position"],
            s.propagate(
                Family::One,
                eval(environment(), var("inner")),
                ["innerValue", "innerSteps"],
                s.value_match(
                    var("innerValue"),
                    vec![on(
                        "adt",
                        &["tag", "fields"],
                        option_match(
                            prim(
                                "index",
                                vec![var("fields"), var("position")],
                                option_t(value_t()),
                            ),
                            stuck(),
                            "selected",
                            produced(
                                var("selected"),
                                add(one_more("innerSteps"), var("position")),
                            ),
                        ),
                    )],
                    stuck(),
                ),
            ),
        ),
    ]
}

/// The parameters every evaluation function shares, then its own.
fn evaluation_parameters(last: Json) -> Vec<Json> {
    vec![
        parameter("fuel", nat_t()),
        parameter("program", syntax_t("Program")),
        parameter("environment", environment_t()),
        last,
    ]
}

/// Structural recursion on `fuel`: running out is `exhausted`, which
/// reports only that the fuel bounded the evaluation.
fn on_fuel(exhausted: Json, remaining: Json) -> Json {
    matching(
        var("fuel"),
        vec![
            branch("Nat.zero", &[], exhausted),
            branch("Nat.succ", &["remaining"], remaining),
        ],
    )
}

fn evaluation(s: &Semantics) -> [Json; 3] {
    let expressions = expression_cases(s);
    let eval_definition = definition(
        "eval",
        evaluation_parameters(parameter("expression", syntax_t("Expr"))),
        outcome_t(),
        on_fuel(
            exhausted(),
            exhaustive(var("expression"), "Expr", &expr_constructors(), expressions),
        ),
    );
    // Operands evaluate left to right; the list's steps are the sum of its
    // elements'.
    let environment = || var("environment");
    let eval_list_definition = definition(
        "evalList",
        evaluation_parameters(parameter("expressions", list_t(syntax_t("Expr")))),
        local_t("Outcomes"),
        on_fuel(
            outcomes("exhausted", vec![]),
            list_match(
                var("expressions"),
                outcomes("values", vec![nil(value_t()), nat(0)]),
                "head",
                "rest",
                outcome_match(
                    eval(environment(), var("head")),
                    Family::One,
                    (
                        &["headValue", "headSteps"],
                        outcome_match(
                            eval_list(var("rest")),
                            Family::Many,
                            (
                                &["restValues", "restSteps"],
                                outcomes(
                                    "values",
                                    vec![
                                        cons(var("headValue"), var("restValues")),
                                        add(var("headSteps"), var("restSteps")),
                                    ],
                                ),
                            ),
                            (
                                &["restOverflow"],
                                outcomes(
                                    "overflow",
                                    vec![add(var("headSteps"), var("restOverflow"))],
                                ),
                            ),
                            outcomes("stuck", vec![]),
                            outcomes("exhausted", vec![]),
                        ),
                    ),
                    (
                        &["headOverflow"],
                        outcomes("overflow", vec![var("headOverflow")]),
                    ),
                    outcomes("stuck", vec![]),
                    outcomes("exhausted", vec![]),
                ),
            ),
        ),
    );
    // The first arm whose shape the scrutinee has is taken; none is stuck,
    // which an exhaustive match never is. Each arm tried is one step.
    let eval_arms_definition = definition(
        "evalArms",
        evaluation_parameters(parameter("scrutinee", value_t()))
            .into_iter()
            .chain([parameter("arms", list_t(syntax_t("Arm")))])
            .collect(),
        outcome_t(),
        on_fuel(
            exhausted(),
            list_match(
                var("arms"),
                stuck(),
                "first",
                "rest",
                matching(
                    var("first"),
                    vec![syntax_branch(
                        "Arm.arm",
                        &["shape", "binders", "body"],
                        option_match(
                            call("destruct", vec![var("shape"), var("scrutinee")]),
                            call(
                                "addSteps",
                                vec![
                                    call(
                                        "evalArms",
                                        vec![
                                            var("remaining"),
                                            var("program"),
                                            environment(),
                                            var("scrutinee"),
                                            var("rest"),
                                        ],
                                    ),
                                    nat(1),
                                ],
                            ),
                            "fields",
                            option_match(
                                call(
                                    "bindAll",
                                    vec![var("binders"), var("fields"), environment()],
                                ),
                                stuck(),
                                "extended",
                                call("addSteps", vec![eval(var("extended"), var("body")), nat(1)]),
                            ),
                        ),
                    )],
                ),
            ),
        ),
    );
    [eval_definition, eval_list_definition, eval_arms_definition].map(|declaration| {
        axioms(
            CLASSICAL,
            mutual("Evaluation", recursive("fuel", declaration)),
        )
    })
}

/// The denotation of a program: the entry's parameters bound to the
/// arguments, its body evaluated with `fuel`.
fn run() -> Json {
    axioms(
        CLASSICAL,
        definition(
            "run",
            vec![
                parameter("fuel", nat_t()),
                parameter("program", syntax_t("Program")),
                parameter("entry", nat_t()),
                parameter("arguments", values_t()),
            ],
            outcome_t(),
            option_match(
                prim(
                    "index",
                    vec![project(var("program"), "functions"), var("entry")],
                    option_t(function_t()),
                ),
                stuck(),
                "function",
                option_match(
                    call(
                        "bindAll",
                        vec![
                            project(var("function"), "parameters"),
                            var("arguments"),
                            nil(product_t(nat_t(), value_t())),
                        ],
                    ),
                    stuck(),
                    "environment",
                    call(
                        "eval",
                        vec![
                            var("fuel"),
                            var("program"),
                            var("environment"),
                            project(var("function"), "body"),
                        ],
                    ),
                ),
            ),
        ),
    )
}

/// The `TargetSemantics` module: outcomes and the evaluator.
#[must_use]
pub fn semantics_module() -> String {
    let s = Semantics::new();
    // Each element is built in turn, and fresh binders are numbered in that
    // order (see `Semantics`).
    let mut declarations: Vec<Json> = Vec::new();
    declarations.extend(outcome_types());
    declarations.push(add_steps());
    declarations.push(lookup());
    declarations.push(depth());
    declarations.push(bind_all(&s));
    declarations.push(nat_result());
    declarations.push(int_result());
    declarations.push(from_ordering());
    declarations.push(same_order());
    declarations.push(order_of(&s));
    declarations.extend(key_orders());
    declarations.push(compare_value(&s));
    declarations.push(compare_values(&s));
    declarations.push(weight(&s));
    declarations.push(weights());
    declarations.push(charge_result());
    declarations.push(destruct(&s));
    declarations.push(construct(&s));
    declarations.push(from_strings());
    declarations.push(to_strings(&s));
    declarations.push(primitive(&s));
    declarations.extend(evaluation(&s));
    declarations.push(run());
    module_tex(SEMANTICS, &[SYNTAX], declarations)
}

// --- TargetOracle and Main --------------------------------------------------

/// A LexLean list encoded element by element as target values, so a fixture
/// theorem can state that a library realization computes exactly what
/// LexLean's own collection primitive computes.
fn encoder(name: &str, element: Json, encode: impl Fn(Json) -> Json) -> Json {
    recursive(
        "items",
        definition(
            name,
            vec![parameter("items", list_t(element))],
            values_t(),
            list_match(
                var("items"),
                nil(value_t()),
                "item",
                "rest",
                cons(encode(var("item")), call(name, vec![var("rest")])),
            ),
        ),
    )
}

/// The `TargetOracle` module: the encoders the collection fixtures need.
#[must_use]
pub fn oracle_module() -> String {
    let declarations = vec![
        encoder("encodeNats", nat_t(), |item| value("nat", vec![item])),
        encoder("encodeInts", int_t(), |item| value("int", vec![item])),
        encoder("encodeI8s", int8_t(), |item| value("i8", vec![item])),
        encoder("encodeBools", bool_t(), |item| value("bool", vec![item])),
        encoder("encodeStrings", string_t(), |item| {
            value("string", vec![item])
        }),
        encoder("encodeNatStrings", product_t(nat_t(), string_t()), |item| {
            value(
                "pair",
                vec![
                    value("nat", vec![first(item.clone())]),
                    value("string", vec![second(item)]),
                ],
            )
        }),
        encoder(
            "encodeAdjacency",
            product_t(nat_t(), list_t(nat_t())),
            |item| {
                value(
                    "pair",
                    vec![
                        value("nat", vec![first(item.clone())]),
                        value("list", vec![call("encodeNats", vec![second(item)])]),
                    ],
                )
            },
        ),
    ];
    module_tex(ORACLE, &[SYNTAX], declarations)
}

/// The `Main` module. The project's entrypoint imports every module, so a
/// build of `compiler/` elaborates, replays, and audits all of them; its
/// one definition is the program with nothing in it.
#[must_use]
pub fn main_module() -> String {
    let empty_program = definition(
        "emptyProgram",
        Vec::new(),
        syntax_t("Program"),
        record(
            term::member(SYNTAX, "Program"),
            vec![
                ("adts", nil(syntax_t("Adt"))),
                ("functions", nil(syntax_t("Function"))),
            ],
        ),
    );
    // `Main` is the project's root, so the GNAF model and its fixtures
    // (§17.15) are elaborated, replayed, and audited only if it imports them.
    let mut imports = vec![SYNTAX, SEMANTICS, ORACLE];
    imports.extend(crate::calculus::reasoning::ORACLE_MODULES);
    imports.extend([
        FIXTURES,
        crate::calculus::reasoning::FIXTURES,
        lexlean::gnaf::MODEL,
        crate::gnaf::FIXTURES_MODULE,
    ]);
    module_tex("Main", &imports, vec![empty_program])
}

// --- project configuration -------------------------------------------------

/// `text` with `from` replaced by `to`.
///
/// # Panics
///
/// Panics when `text` does not contain `from`: the production example has
/// been changed, and the `compiler` project must not silently diverge.
fn renamed(text: &str, from: &str, to: &str) -> String {
    assert!(
        text.contains(from),
        "the production example no longer contains {from:?}"
    );
    text.replace(from, to)
}

/// The `compiler` project is configured exactly as the production example
/// (same toolchain, lexicon source, and limits) under its own name, so it
/// passes the gates of §28.6 on the same terms as that example.
fn configuration() -> [(&'static str, String); 4] {
    let lexlean = renamed(
        &renamed(
            include_str!("../../../examples/production/lexlean.toml"),
            "name = \"production\"",
            "name = \"compiler\"",
        ),
        "module_prefix = \"Production\"",
        "module_prefix = \"Compiler\"",
    );
    [
        ("compiler/lexlean.toml", lexlean),
        (
            "compiler/lakefile.toml",
            renamed(
                include_str!("../../../examples/production/lakefile.toml"),
                "production_host",
                "compiler_host",
            ),
        ),
        (
            "compiler/lake-manifest.json",
            renamed(
                include_str!("../../../examples/production/lake-manifest.json"),
                "production_host",
                "compiler_host",
            ),
        ),
        (
            "compiler/lean-toolchain",
            include_str!("../../../examples/production/lean-toolchain").to_owned(),
        ),
    ]
}

/// Every file this module generates, by path relative to the repository
/// root.
#[must_use]
pub fn files() -> BTreeMap<String, Vec<u8>> {
    let mut out: BTreeMap<String, Vec<u8>> = configuration()
        .into_iter()
        .map(|(path, text)| (path.to_owned(), text.into_bytes()))
        .collect();
    for (module, text) in [
        (SYNTAX, syntax_module()),
        (SEMANTICS, semantics_module()),
        (ORACLE, oracle_module()),
        ("Main", main_module()),
    ] {
        out.insert(format!("compiler/src/{module}.lex.tex"), text.into_bytes());
    }
    for (module, text) in crate::calculus::reasoning::oracle_modules() {
        out.insert(format!("compiler/src/{module}.lex.tex"), text.into_bytes());
    }
    out
}
