import LexLeanPreservation.RustSound
set_option autoImplicit false
set_option maxRecDepth 100000
namespace LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R30.RustStd
open LexLeanTarget LexLeanPreservation.Rust

def program : TargetSyntax.Program :=
  { adts := [{ constructors := [[.nat], [(.adt 0), (.adt 0)], [(.list (.adt 1)), (.adt 0)]] },
    { constructors := [[.string, (.adt 0)], [(.adt 1), (.adt 1)]] }], functions := [
    { parameters := [0], types := [(.adt 0)], result := .nat,
      body := (.call 1 [(.var 0)]) },
    { parameters := [0], types := [(.adt 0)], result := .nat,
      body := (.«match» .nat (.var 0) [(.arm (.adt 0) [1] (.value .nat (.nat 1))), (.arm (.adt 1) [2, 3] (.prim .natAdd [(.prim .natAdd [(.call 1 [(.var 2)]), (.call 1 [(.var 3)])]), (.value .nat (.nat 1))])), (.arm (.adt 2) [4, 5] (.prim .natAdd [(.call 2 [(.var 4)]), (.call 1 [(.var 5)])]))]) },
    { parameters := [0], types := [(.list (.adt 1))], result := .nat,
      body := (.«match» .nat (.var 0) [(.arm .nil [] (.value .nat (.nat 0))), (.arm .cons [1, 2] (.prim .natAdd [(.call 3 [(.var 1)]), (.call 2 [(.var 2)])]))]) },
    { parameters := [0], types := [(.adt 1)], result := .nat,
      body := (.«match» .nat (.var 0) [(.arm (.adt 0) [1, 2] (.prim .natAdd [(.call 1 [(.var 2)]), (.value .nat (.nat 1))])), (.arm (.adt 1) [3, 4] (.prim .natAdd [(.call 3 [(.var 3)]), (.call 3 [(.var 4)])]))]) }] }

def krate : RustSyntax.Crate :=
  ({ profile := .std, items := [
    (.enum (.adt 0) [{ number := 0, fields := [.nat] }, { number := 1, fields := [(.rc (.adt 0)), (.rc (.adt 0))] }, { number := 2, fields := [(.list (.adt 1)), (.rc (.adt 0))] }]),
    (.enum (.adt 1) [{ number := 0, fields := [.str, (.adt 0)] }, { number := 1, fields := [(.rc (.adt 1)), (.rc (.adt 1))] }]),
    (.function (.generated .function 0) [{ pattern := (.bind (.generated .binding 0)), type := (.adt 0) }] (.fallible .nat) (.mk [] (.call (.function 1) [(.clone (.generated .binding 0))] false))),
    (.function (.generated .function 1) [{ pattern := (.bind (.generated .binding 0)), type := (.adt 0) }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 1)) none (.clone (.generated .binding 0)))] (.matchOn (.move (.generated .holder 1)) [(.mk (.adt 0 0 [.wild]) (.mk [] (.succeed (.lit (.nat 1))))), (.mk (.adt 0 1 [(.bind (.generated .boxed 8)), (.bind (.generated .boxed 9))]) (.mk [(.mk (.bind (.generated .binding 2)) none (.unbox (.generated .boxed 8))), (.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 9))), (.mk (.bind (.generated .operand 4)) none (.block (.mk [(.mk (.bind (.generated .operand 2)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 3)) none (.call (.function 1) [(.clone (.generated .binding 3))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 2)), (.move (.generated .operand 3))] true)))), (.mk (.bind (.generated .operand 5)) none (.lit (.nat 1)))] (.call (.runtime .natAdd) [(.move (.generated .operand 4)), (.move (.generated .operand 5))] false))), (.mk (.adt 0 2 [(.bind (.generated .binding 4)), (.bind (.generated .boxed 10))]) (.mk [(.mk (.bind (.generated .binding 5)) none (.unbox (.generated .boxed 10))), (.mk (.bind (.generated .operand 6)) none (.call (.function 2) [(.clone (.generated .binding 4))] true)), (.mk (.bind (.generated .operand 7)) none (.call (.function 1) [(.clone (.generated .binding 5))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] false)))]))),
    (.function (.generated .function 2) [{ pattern := (.bind (.generated .binding 0)), type := (.list (.adt 1)) }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 11)) none (.clone (.generated .binding 0)))] (.matchOn (.uncons (.generated .holder 11)) [(.mk .none (.mk [] (.succeed (.lit (.nat 0))))), (.mk (.some (.tuple [(.bind (.generated .binding 1)), (.bind (.generated .binding 2))])) (.mk [(.mk (.bind (.generated .operand 12)) none (.call (.function 3) [(.clone (.generated .binding 1))] true)), (.mk (.bind (.generated .operand 13)) none (.call (.function 2) [(.clone (.generated .binding 2))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 12)), (.move (.generated .operand 13))] false)))]))),
    (.function (.generated .function 3) [{ pattern := (.bind (.generated .binding 0)), type := (.adt 1) }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 14)) none (.clone (.generated .binding 0)))] (.matchOn (.move (.generated .holder 14)) [(.mk (.adt 1 0 [.wild, (.bind (.generated .binding 2))]) (.mk [(.mk (.bind (.generated .operand 15)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 16)) none (.lit (.nat 1)))] (.call (.runtime .natAdd) [(.move (.generated .operand 15)), (.move (.generated .operand 16))] false))), (.mk (.adt 1 1 [(.bind (.generated .boxed 19)), (.bind (.generated .boxed 20))]) (.mk [(.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 19))), (.mk (.bind (.generated .binding 4)) none (.unbox (.generated .boxed 20))), (.mk (.bind (.generated .operand 17)) none (.call (.function 3) [(.clone (.generated .binding 3))] true)), (.mk (.bind (.generated .operand 18)) none (.call (.function 3) [(.clone (.generated .binding 4))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 17)), (.move (.generated .operand 18))] false)))])))] } : LexLeanTarget.RustSyntax.Crate)

def flags : Flags := []

theorem fun0 : FunOK program krate flags 0 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.call (.function 1) [(.clone (.generated .binding 0))] false), [(0, (.adt 0), (some 0))], rfl, rfl,
    (Corr.callF (ts := [(.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl)⟩⟩

theorem fun1 : FunOK program krate flags 1 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 1)) none (.clone (.generated .binding 0)))], (.matchOn (.move (.generated .holder 1)) [(.mk (.adt 0 0 [.wild]) (.mk [] (.succeed (.lit (.nat 1))))), (.mk (.adt 0 1 [(.bind (.generated .boxed 8)), (.bind (.generated .boxed 9))]) (.mk [(.mk (.bind (.generated .binding 2)) none (.unbox (.generated .boxed 8))), (.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 9))), (.mk (.bind (.generated .operand 4)) none (.block (.mk [(.mk (.bind (.generated .operand 2)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 3)) none (.call (.function 1) [(.clone (.generated .binding 3))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 2)), (.move (.generated .operand 3))] true)))), (.mk (.bind (.generated .operand 5)) none (.lit (.nat 1)))] (.call (.runtime .natAdd) [(.move (.generated .operand 4)), (.move (.generated .operand 5))] false))), (.mk (.adt 0 2 [(.bind (.generated .binding 4)), (.bind (.generated .boxed 10))]) (.mk [(.mk (.bind (.generated .binding 5)) none (.unbox (.generated .boxed 10))), (.mk (.bind (.generated .operand 6)) none (.call (.function 2) [(.clone (.generated .binding 4))] true)), (.mk (.bind (.generated .operand 7)) none (.call (.function 1) [(.clone (.generated .binding 5))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] false)))]), [(0, (.adt 0), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.adt 0)) (U := []) (view := false) (idx := [0, 1, 2]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(1, .nat, none), (0, (.adt 0), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.succeed (.lit (.nat 1)))) (Corr.mCons (Γ' := [(3, (.adt 0), (some 3)), (2, (.adt 0), (some 2)), (0, (.adt 0), (some 0))]) (j := 1) (loads := [(.mk (.bind (.generated .binding 2)) none (.unbox (.generated .boxed 8))), (.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 9)))]) (lets := [(.mk (.bind (.generated .operand 4)) none (.block (.mk [(.mk (.bind (.generated .operand 2)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 3)) none (.call (.function 1) [(.clone (.generated .binding 3))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 2)), (.move (.generated .operand 3))] true)))), (.mk (.bind (.generated .operand 5)) none (.lit (.nat 1)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 4)), (.move (.generated .operand 5))] false)) (Corr.mCons (Γ' := [(5, (.adt 0), (some 5)), (4, (.list (.adt 1)), (some 4)), (0, (.adt 0), (some 0))]) (j := 2) (loads := [(.mk (.bind (.generated .binding 5)) none (.unbox (.generated .boxed 10)))]) (lets := [(.mk (.bind (.generated .operand 6)) none (.call (.function 2) [(.clone (.generated .binding 4))] true)), (.mk (.bind (.generated .operand 7)) none (.call (.function 1) [(.clone (.generated .binding 5))] true))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] false)) (Corr.mNil) rfl rfl rfl (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.list (.adt 1))]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 2)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 3)) none (.call (.function 1) [(.clone (.generated .binding 3))] true))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 2)), (.move (.generated .operand 3))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.value rfl rfl)))) rfl rfl rfl)⟩⟩

theorem fun2 : FunOK program krate flags 2 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 11)) none (.clone (.generated .binding 0)))], (.matchOn (.uncons (.generated .holder 11)) [(.mk .none (.mk [] (.succeed (.lit (.nat 0))))), (.mk (.some (.tuple [(.bind (.generated .binding 1)), (.bind (.generated .binding 2))])) (.mk [(.mk (.bind (.generated .operand 12)) none (.call (.function 3) [(.clone (.generated .binding 1))] true)), (.mk (.bind (.generated .operand 13)) none (.call (.function 2) [(.clone (.generated .binding 2))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 12)), (.move (.generated .operand 13))] false)))]), [(0, (.list (.adt 1)), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.list (.adt 1))) (U := []) (view := true) (idx := [0, 1]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(0, (.list (.adt 1)), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.succeed (.lit (.nat 0)))) (Corr.mCons (Γ' := [(2, (.list (.adt 1)), (some 2)), (1, (.adt 1), (some 1)), (0, (.list (.adt 1)), (some 0))]) (j := 1) (loads := []) (lets := [(.mk (.bind (.generated .operand 12)) none (.call (.function 3) [(.clone (.generated .binding 1))] true)), (.mk (.bind (.generated .operand 13)) none (.call (.function 2) [(.clone (.generated .binding 2))] true))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 12)), (.move (.generated .operand 13))] false)) (Corr.mNil) rfl rfl rfl (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 1)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.list (.adt 1))]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.value rfl rfl)))) rfl rfl rfl)⟩⟩

theorem fun3 : FunOK program krate flags 3 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 14)) none (.clone (.generated .binding 0)))], (.matchOn (.move (.generated .holder 14)) [(.mk (.adt 1 0 [.wild, (.bind (.generated .binding 2))]) (.mk [(.mk (.bind (.generated .operand 15)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 16)) none (.lit (.nat 1)))] (.call (.runtime .natAdd) [(.move (.generated .operand 15)), (.move (.generated .operand 16))] false))), (.mk (.adt 1 1 [(.bind (.generated .boxed 19)), (.bind (.generated .boxed 20))]) (.mk [(.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 19))), (.mk (.bind (.generated .binding 4)) none (.unbox (.generated .boxed 20))), (.mk (.bind (.generated .operand 17)) none (.call (.function 3) [(.clone (.generated .binding 3))] true)), (.mk (.bind (.generated .operand 18)) none (.call (.function 3) [(.clone (.generated .binding 4))] true))] (.call (.runtime .natAdd) [(.move (.generated .operand 17)), (.move (.generated .operand 18))] false)))]), [(0, (.adt 1), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.adt 1)) (U := []) (view := false) (idx := [0, 1]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(2, (.adt 0), (some 2)), (1, .string, none), (0, (.adt 1), (some 0))]) (j := 0) (loads := []) (lets := [(.mk (.bind (.generated .operand 15)) none (.call (.function 1) [(.clone (.generated .binding 2))] true)), (.mk (.bind (.generated .operand 16)) none (.lit (.nat 1)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 15)), (.move (.generated .operand 16))] false)) (Corr.mCons (Γ' := [(4, (.adt 1), (some 4)), (3, (.adt 1), (some 3)), (0, (.adt 1), (some 0))]) (j := 1) (loads := [(.mk (.bind (.generated .binding 3)) none (.unbox (.generated .boxed 19))), (.mk (.bind (.generated .binding 4)) none (.unbox (.generated .boxed 20)))]) (lets := [(.mk (.bind (.generated .operand 17)) none (.call (.function 3) [(.clone (.generated .binding 3))] true)), (.mk (.bind (.generated .operand 18)) none (.call (.function 3) [(.clone (.generated .binding 4))] true))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 17)), (.move (.generated .operand 18))] false)) (Corr.mNil) rfl rfl rfl (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 1)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 1)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.primF (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfBNil (Corr.callOps (ts := [(.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) rfl rfl rfl)⟩⟩

theorem crate_ok : CrateOK program krate flags := by
  intro f fn h
  match f with
  | 0 => exact fun0
  | 1 => exact fun1
  | 2 => exact fun2
  | 3 => exact fun3
  | _ + 4 => simp [program, index_eq] at h

/-- Every function of the program is simulated by its rendering. -/
theorem root : ∀ n f, FunSem program krate flags n f := fun n f => simulate crate_ok n f

end LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R30.RustStd
