module
import Reasoning.Clinic
#print axioms Reasoning.Clinic.Chart
#print axioms Reasoning.Clinic.Consistent
#print axioms Reasoning.Clinic.Discharged
#print axioms Reasoning.Clinic.Escalate.apply
#print axioms Reasoning.Clinic.Escalate.apply_progress
#print axioms Reasoning.Clinic.Escalate.apply_sound
#print axioms Reasoning.Clinic.Escalate.conclusion
#print axioms Reasoning.Clinic.Escalate.guard
#print axioms Reasoning.Clinic.Febrile
#print axioms Reasoning.Clinic.Fever.apply
#print axioms Reasoning.Clinic.Fever.apply_progress
#print axioms Reasoning.Clinic.Fever.apply_sound
#print axioms Reasoning.Clinic.Fever.conclusion
#print axioms Reasoning.Clinic.Fever.guard
#print axioms Reasoning.Clinic.Findings.preserves
#print axioms Reasoning.Clinic.Hypotensive
#print axioms Reasoning.Clinic.Indicated
#print axioms Reasoning.Clinic.Justified
#print axioms Reasoning.Clinic.Leukocytic
#print axioms Reasoning.Clinic.Leukocytosis.apply
#print axioms Reasoning.Clinic.Leukocytosis.apply_progress
#print axioms Reasoning.Clinic.Leukocytosis.apply_sound
#print axioms Reasoning.Clinic.Leukocytosis.conclusion
#print axioms Reasoning.Clinic.Leukocytosis.guard
#print axioms Reasoning.Clinic.Outpatient.sound
#print axioms Reasoning.Clinic.Pending
#print axioms Reasoning.Clinic.Recommendation.complete
#print axioms Reasoning.Clinic.Recommendation.sound
#print axioms Reasoning.Clinic.Review
#print axioms Reasoning.Clinic.Review.Ledger
#print axioms Reasoning.Clinic.Review.Run
#print axioms Reasoning.Clinic.Review.Step
#print axioms Reasoning.Clinic.Review.accept
#print axioms Reasoning.Clinic.Review.accept_sound
#print axioms Reasoning.Clinic.Review.account
#print axioms Reasoning.Clinic.Review.answer
#print axioms Reasoning.Clinic.Review.attempts
#print axioms Reasoning.Clinic.Review.conclude
#print axioms Reasoning.Clinic.Review.conclude_accept
#print axioms Reasoning.Clinic.Review.conclude_sound
#print axioms Reasoning.Clinic.Review.derivation
#print axioms Reasoning.Clinic.Review.explained
#print axioms Reasoning.Clinic.Review.extract
#print axioms Reasoning.Clinic.Review.fire
#print axioms Reasoning.Clinic.Review.fire_sound
#print axioms Reasoning.Clinic.Review.firings_bounded
#print axioms Reasoning.Clinic.Review.follow
#print axioms Reasoning.Clinic.Review.follow_invariant
#print axioms Reasoning.Clinic.Review.iterations_bounded
#print axioms Reasoning.Clinic.Review.next
#print axioms Reasoning.Clinic.Review.next_preserves
#print axioms Reasoning.Clinic.Review.next_sound
#print axioms Reasoning.Clinic.Review.observe
#print axioms Reasoning.Clinic.Review.replay
#print axioms Reasoning.Clinic.Review.replay_fire
#print axioms Reasoning.Clinic.Review.replay_sound
#print axioms Reasoning.Clinic.Review.run
#print axioms Reasoning.Clinic.Review.run_state
#print axioms Reasoning.Clinic.Review.run_trace
#print axioms Reasoning.Clinic.Review.saturate
#print axioms Reasoning.Clinic.Review.saturate_derivation
#print axioms Reasoning.Clinic.Review.saturate_invariant
#print axioms Reasoning.Clinic.Review.select
#print axioms Reasoning.Clinic.Review.start
#print axioms Reasoning.Clinic.Review.step
#print axioms Reasoning.Clinic.Review.step_count
#print axioms Reasoning.Clinic.Review.step_fired
#print axioms Reasoning.Clinic.Review.step_none
#print axioms Reasoning.Clinic.Review.step_some
#print axioms Reasoning.Clinic.Review.step_trace
#print axioms Reasoning.Clinic.Review.verdict
#print axioms Reasoning.Clinic.Review.verdict_sound
#print axioms Reasoning.Clinic.Sepsis.apply
#print axioms Reasoning.Clinic.Sepsis.apply_progress
#print axioms Reasoning.Clinic.Sepsis.apply_sound
#print axioms Reasoning.Clinic.Sepsis.conclusion
#print axioms Reasoning.Clinic.Sepsis.guard
#print axioms Reasoning.Clinic.Shock.apply
#print axioms Reasoning.Clinic.Shock.apply_progress
#print axioms Reasoning.Clinic.Shock.apply_sound
#print axioms Reasoning.Clinic.Shock.conclusion
#print axioms Reasoning.Clinic.Shock.guard
#print axioms Reasoning.Clinic.Sirs.apply
#print axioms Reasoning.Clinic.Sirs.apply_progress
#print axioms Reasoning.Clinic.Sirs.apply_sound
#print axioms Reasoning.Clinic.Sirs.conclusion
#print axioms Reasoning.Clinic.Sirs.guard
#print axioms Reasoning.Clinic.Tachycardia.apply
#print axioms Reasoning.Clinic.Tachycardia.apply_progress
#print axioms Reasoning.Clinic.Tachycardia.apply_sound
#print axioms Reasoning.Clinic.Tachycardia.conclusion
#print axioms Reasoning.Clinic.Tachycardia.guard
#print axioms Reasoning.Clinic.Tachycardic
#print axioms Reasoning.Clinic.Tachypnea.apply
#print axioms Reasoning.Clinic.Tachypnea.apply_progress
#print axioms Reasoning.Clinic.Tachypnea.apply_sound
#print axioms Reasoning.Clinic.Tachypnea.conclusion
#print axioms Reasoning.Clinic.Tachypnea.guard
#print axioms Reasoning.Clinic.Tachypneic
#print axioms Reasoning.Clinic.Triage
#print axioms Reasoning.Clinic.Triage.Ledger
#print axioms Reasoning.Clinic.Triage.Run
#print axioms Reasoning.Clinic.Triage.Step
#print axioms Reasoning.Clinic.Triage.accept
#print axioms Reasoning.Clinic.Triage.accept_sound
#print axioms Reasoning.Clinic.Triage.account
#print axioms Reasoning.Clinic.Triage.answer
#print axioms Reasoning.Clinic.Triage.attempts
#print axioms Reasoning.Clinic.Triage.conclude
#print axioms Reasoning.Clinic.Triage.conclude_accept
#print axioms Reasoning.Clinic.Triage.conclude_sound
#print axioms Reasoning.Clinic.Triage.derivation
#print axioms Reasoning.Clinic.Triage.explained
#print axioms Reasoning.Clinic.Triage.extract
#print axioms Reasoning.Clinic.Triage.fire
#print axioms Reasoning.Clinic.Triage.fire_progress
#print axioms Reasoning.Clinic.Triage.fire_sound
#print axioms Reasoning.Clinic.Triage.firings_bounded
#print axioms Reasoning.Clinic.Triage.follow
#print axioms Reasoning.Clinic.Triage.follow_invariant
#print axioms Reasoning.Clinic.Triage.iterations_bounded
#print axioms Reasoning.Clinic.Triage.next
#print axioms Reasoning.Clinic.Triage.next_preserves
#print axioms Reasoning.Clinic.Triage.next_progress
#print axioms Reasoning.Clinic.Triage.next_sound
#print axioms Reasoning.Clinic.Triage.observe
#print axioms Reasoning.Clinic.Triage.replay
#print axioms Reasoning.Clinic.Triage.replay_fire
#print axioms Reasoning.Clinic.Triage.replay_sound
#print axioms Reasoning.Clinic.Triage.run
#print axioms Reasoning.Clinic.Triage.run_state
#print axioms Reasoning.Clinic.Triage.run_trace
#print axioms Reasoning.Clinic.Triage.saturate
#print axioms Reasoning.Clinic.Triage.saturate_derivation
#print axioms Reasoning.Clinic.Triage.saturate_invariant
#print axioms Reasoning.Clinic.Triage.saturates
#print axioms Reasoning.Clinic.Triage.select
#print axioms Reasoning.Clinic.Triage.start
#print axioms Reasoning.Clinic.Triage.step
#print axioms Reasoning.Clinic.Triage.step_count
#print axioms Reasoning.Clinic.Triage.step_fired
#print axioms Reasoning.Clinic.Triage.step_none
#print axioms Reasoning.Clinic.Triage.step_some
#print axioms Reasoning.Clinic.Triage.step_trace
#print axioms Reasoning.Clinic.Triage.verdict
#print axioms Reasoning.Clinic.Triage.verdict_sound
#print axioms Reasoning.Clinic.Vitals
#print axioms Reasoning.Clinic.Warranted
#print axioms Reasoning.Clinic.admitted_consistent
#print axioms Reasoning.Clinic.admitted_pending
#print axioms Reasoning.Clinic.consistent_preserved
#print axioms Reasoning.Clinic.dischargeCheck
#print axioms Reasoning.Clinic.discharge_sound
#print axioms Reasoning.Clinic.escalate_progress
#print axioms Reasoning.Clinic.escalate_sound
#print axioms Reasoning.Clinic.fever_progress
#print axioms Reasoning.Clinic.fever_sound
#print axioms Reasoning.Clinic.feverish
#print axioms Reasoning.Clinic.hypotensive
#print axioms Reasoning.Clinic.leukocytic
#print axioms Reasoning.Clinic.leukocytosis_progress
#print axioms Reasoning.Clinic.leukocytosis_sound
#print axioms Reasoning.Clinic.recommendationCheck
#print axioms Reasoning.Clinic.recommendation_complete
#print axioms Reasoning.Clinic.recommendation_sound
#print axioms Reasoning.Clinic.sepsis_progress
#print axioms Reasoning.Clinic.sepsis_sound
#print axioms Reasoning.Clinic.shock_progress
#print axioms Reasoning.Clinic.shock_sound
#print axioms Reasoning.Clinic.sirs_progress
#print axioms Reasoning.Clinic.sirs_sound
#print axioms Reasoning.Clinic.tachycardia_progress
#print axioms Reasoning.Clinic.tachycardia_sound
#print axioms Reasoning.Clinic.tachycardic
#print axioms Reasoning.Clinic.tachypnea_progress
#print axioms Reasoning.Clinic.tachypnea_sound
#print axioms Reasoning.Clinic.tachypneic
