module
import Reasoning.Budget
#print axioms Reasoning.Budget.Burn.apply
#print axioms Reasoning.Budget.Burn.apply_progress
#print axioms Reasoning.Budget.Burn.apply_sound
#print axioms Reasoning.Budget.Burn.candidates
#print axioms Reasoning.Budget.Burn.conclusion
#print axioms Reasoning.Budget.Burn.guard
#print axioms Reasoning.Budget.Drained.sound
#print axioms Reasoning.Budget.Empty
#print axioms Reasoning.Budget.Refund
#print axioms Reasoning.Budget.Refund.Ledger
#print axioms Reasoning.Budget.Refund.Run
#print axioms Reasoning.Budget.Refund.Step
#print axioms Reasoning.Budget.Refund.accept
#print axioms Reasoning.Budget.Refund.accept_sound
#print axioms Reasoning.Budget.Refund.account
#print axioms Reasoning.Budget.Refund.answer
#print axioms Reasoning.Budget.Refund.attempts
#print axioms Reasoning.Budget.Refund.conclude
#print axioms Reasoning.Budget.Refund.conclude_accept
#print axioms Reasoning.Budget.Refund.conclude_sound
#print axioms Reasoning.Budget.Refund.derivation
#print axioms Reasoning.Budget.Refund.explained
#print axioms Reasoning.Budget.Refund.extract
#print axioms Reasoning.Budget.Refund.fire
#print axioms Reasoning.Budget.Refund.fire_sound
#print axioms Reasoning.Budget.Refund.follow
#print axioms Reasoning.Budget.Refund.iterations_bounded
#print axioms Reasoning.Budget.Refund.next
#print axioms Reasoning.Budget.Refund.next_sound
#print axioms Reasoning.Budget.Refund.observe
#print axioms Reasoning.Budget.Refund.replay
#print axioms Reasoning.Budget.Refund.replay_fire
#print axioms Reasoning.Budget.Refund.replay_sound
#print axioms Reasoning.Budget.Refund.run
#print axioms Reasoning.Budget.Refund.run_state
#print axioms Reasoning.Budget.Refund.run_trace
#print axioms Reasoning.Budget.Refund.saturate
#print axioms Reasoning.Budget.Refund.saturate_derivation
#print axioms Reasoning.Budget.Refund.select
#print axioms Reasoning.Budget.Refund.start
#print axioms Reasoning.Budget.Refund.step
#print axioms Reasoning.Budget.Refund.step_count
#print axioms Reasoning.Budget.Refund.step_none
#print axioms Reasoning.Budget.Refund.step_some
#print axioms Reasoning.Budget.Refund.step_trace
#print axioms Reasoning.Budget.Refund.verdict
#print axioms Reasoning.Budget.Refund.verdict_sound
#print axioms Reasoning.Budget.Remaining
#print axioms Reasoning.Budget.Spend
#print axioms Reasoning.Budget.Spend.Ledger
#print axioms Reasoning.Budget.Spend.Run
#print axioms Reasoning.Budget.Spend.Step
#print axioms Reasoning.Budget.Spend.accept
#print axioms Reasoning.Budget.Spend.accept_sound
#print axioms Reasoning.Budget.Spend.account
#print axioms Reasoning.Budget.Spend.answer
#print axioms Reasoning.Budget.Spend.attempts
#print axioms Reasoning.Budget.Spend.conclude
#print axioms Reasoning.Budget.Spend.conclude_accept
#print axioms Reasoning.Budget.Spend.conclude_sound
#print axioms Reasoning.Budget.Spend.derivation
#print axioms Reasoning.Budget.Spend.explained
#print axioms Reasoning.Budget.Spend.extract
#print axioms Reasoning.Budget.Spend.fire
#print axioms Reasoning.Budget.Spend.fire_progress
#print axioms Reasoning.Budget.Spend.fire_sound
#print axioms Reasoning.Budget.Spend.follow
#print axioms Reasoning.Budget.Spend.iterations_bounded
#print axioms Reasoning.Budget.Spend.next
#print axioms Reasoning.Budget.Spend.next_progress
#print axioms Reasoning.Budget.Spend.next_sound
#print axioms Reasoning.Budget.Spend.observe
#print axioms Reasoning.Budget.Spend.replay
#print axioms Reasoning.Budget.Spend.replay_fire
#print axioms Reasoning.Budget.Spend.replay_sound
#print axioms Reasoning.Budget.Spend.run
#print axioms Reasoning.Budget.Spend.run_state
#print axioms Reasoning.Budget.Spend.run_trace
#print axioms Reasoning.Budget.Spend.saturate
#print axioms Reasoning.Budget.Spend.saturate_derivation
#print axioms Reasoning.Budget.Spend.saturates
#print axioms Reasoning.Budget.Spend.select
#print axioms Reasoning.Budget.Spend.start
#print axioms Reasoning.Budget.Spend.step
#print axioms Reasoning.Budget.Spend.step_count
#print axioms Reasoning.Budget.Spend.step_none
#print axioms Reasoning.Budget.Spend.step_some
#print axioms Reasoning.Budget.Spend.step_trace
#print axioms Reasoning.Budget.Spend.verdict
#print axioms Reasoning.Budget.Spend.verdict_sound
#print axioms Reasoning.Budget.Spent
#print axioms Reasoning.Budget.Tick.apply
#print axioms Reasoning.Budget.Tick.apply_progress
#print axioms Reasoning.Budget.Tick.apply_sound
#print axioms Reasoning.Budget.Tick.conclusion
#print axioms Reasoning.Budget.Tick.guard
#print axioms Reasoning.Budget.allowance_bound
#print axioms Reasoning.Budget.burn_progress
#print axioms Reasoning.Budget.burn_sound
#print axioms Reasoning.Budget.emptyCheck
#print axioms Reasoning.Budget.empty_sound
#print axioms Reasoning.Budget.tick_progress
#print axioms Reasoning.Budget.tick_sound
