module
import Recursion.Main
#print axioms Recursion.Main.countdown
#print axioms Recursion.Main.countdown_decreases
#print axioms Recursion.Main.countdown_nine
#print axioms Recursion.Main.exprSize
#print axioms Recursion.Main.expression_size
#print axioms Recursion.Main.foldExpr
#print axioms Recursion.Main.foldStatement
#print axioms Recursion.Main.foldStatements
#print axioms Recursion.Main.folding_sample
#print axioms Recursion.Main.forestSize
#print axioms Recursion.Main.isEven
#print axioms Recursion.Main.isOdd
#print axioms Recursion.Main.ping
#print axioms Recursion.Main.ping_seven
#print axioms Recursion.Main.ping_to_pong
#print axioms Recursion.Main.pong
#print axioms Recursion.Main.pong_to_ping
#print axioms Recursion.Main.prune
#print axioms Recursion.Main.prune_plus
#print axioms Recursion.Main.prune_result
#print axioms Recursion.Main.reassociate
#print axioms Recursion.Main.reassociate_literal
#print axioms Recursion.Main.reassociate_plus
#print axioms Recursion.Main.reassociate_weight
#print axioms Recursion.Main.reduce
#print axioms Recursion.Main.reduce_decreases
#print axioms Recursion.Main.reduce_twenty_three
#print axioms Recursion.Main.roseSize
#print axioms Recursion.Main.rose_size
#print axioms Recursion.Main.search
#print axioms Recursion.Main.search_decreases
#print axioms Recursion.Main.search_first
#print axioms Recursion.Main.statementSize
#print axioms Recursion.Main.statementsSize
#print axioms Recursion.Main.ten_is_even
#print axioms Recursion.Main.weight
