module
import Collections.Main
#print axioms Collections.Main.ancestor_closure
#print axioms Collections.Main.ancestors
#print axioms Collections.Main.bounded_iteration
#print axioms Collections.Main.call_order
#print axioms Collections.Main.cycle_has_no_order
#print axioms Collections.Main.family
#print axioms Collections.Main.key_order_bool
#print axioms Collections.Main.key_order_int
#print axioms Collections.Main.key_order_int16
#print axioms Collections.Main.key_order_int32
#print axioms Collections.Main.key_order_int64
#print axioms Collections.Main.key_order_int8
#print axioms Collections.Main.key_order_nat
#print axioms Collections.Main.key_order_product
#print axioms Collections.Main.key_order_string
#print axioms Collections.Main.key_order_uint16
#print axioms Collections.Main.key_order_uint32
#print axioms Collections.Main.key_order_uint64
#print axioms Collections.Main.key_order_uint8
#print axioms Collections.Main.op_graph_reachable
#print axioms Collections.Main.op_graph_successors
#print axioms Collections.Main.op_graph_successors_absent
#print axioms Collections.Main.op_graph_topological
#print axioms Collections.Main.op_iterate_until_exhausted
#print axioms Collections.Main.op_iterate_until_fixed_point
#print axioms Collections.Main.op_iterate_zero
#print axioms Collections.Main.op_list_fold
#print axioms Collections.Main.op_map_contains
#print axioms Collections.Main.op_map_entries
#print axioms Collections.Main.op_map_fold
#print axioms Collections.Main.op_map_insert
#print axioms Collections.Main.op_map_insert_replaces
#print axioms Collections.Main.op_map_keys
#print axioms Collections.Main.op_map_lookup
#print axioms Collections.Main.op_map_lookup_absent
#print axioms Collections.Main.op_map_remove
#print axioms Collections.Main.op_map_remove_absent
#print axioms Collections.Main.op_map_size
#print axioms Collections.Main.op_map_values
#print axioms Collections.Main.op_set_contains
#print axioms Collections.Main.op_set_difference
#print axioms Collections.Main.op_set_elements
#print axioms Collections.Main.op_set_fold
#print axioms Collections.Main.op_set_insert
#print axioms Collections.Main.op_set_intersection
#print axioms Collections.Main.op_set_remove
#print axioms Collections.Main.op_set_size
#print axioms Collections.Main.op_set_union
#print axioms Collections.Main.parse_reaches_lex
#print axioms Collections.Main.reordered_literals_agree
#print axioms Collections.Main.table_lookup
#print axioms Collections.Main.table_slots
