import LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7
import LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.RustStd
import LexLeanPreservation.Compose
set_option autoImplicit false
set_option maxRecDepth 100000
namespace LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.Compose.RustStd

/-- The rendering of the root, invoked on the encoded arguments, realizes
the encoded source result. -/
theorem root (a : (List (Prod (Prod Nat String) Bool))) (k : (Prod Nat String)) (i : (List (Prod Int8 Nat))) (j : Int8) (b : (List (Prod Bool Nat))) (c : Bool) (d : (List (Prod Int Nat))) (e : Int) (u : (List (Prod UInt64 Nat))) (w : UInt64) : ∃ ro, LexLeanPreservation.Rust.RealizesFn false (LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.denote a k i j b c d e u w) ro ∧ LexLeanPreservation.Rust.RCI LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.RustStd.krate (LexLeanPreservation.Rust.fnIdent 0) [((LexLeanPreservation.encList (LexLeanPreservation.encPair (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) LexLeanTarget.TargetSyntax.Value.bool)) a), ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) k), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.i8 LexLeanTarget.TargetSyntax.Value.nat)) i), (LexLeanTarget.TargetSyntax.Value.i8 j), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.bool LexLeanTarget.TargetSyntax.Value.nat)) b), (LexLeanTarget.TargetSyntax.Value.bool c), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.int LexLeanTarget.TargetSyntax.Value.nat)) d), (LexLeanTarget.TargetSyntax.Value.int e), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u64 LexLeanTarget.TargetSyntax.Value.nat)) u), (LexLeanTarget.TargetSyntax.Value.u64 w)] ro :=
  LexLeanPreservation.Rust.compose (fun n => LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.RustStd.root n 0) rfl (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_nat LexLeanPreservation.Rust.wt_string) LexLeanPreservation.Rust.wt_bool)) a) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_nat LexLeanPreservation.Rust.wt_string) k) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_i8 LexLeanPreservation.Rust.wt_nat)) i) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_i8 j) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_bool LexLeanPreservation.Rust.wt_nat)) b) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_bool c) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_int LexLeanPreservation.Rust.wt_nat)) d) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_int e) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_u64 LexLeanPreservation.Rust.wt_nat)) u) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_u64 w) LexLeanPreservation.Rust.wtl_nil)))))))))) rfl rfl (LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.root a k i j b c d e u w) (LexLeanPreservation.Rust.rel_ne_stuck _ _)

end LexLeanPreserve.C2f1f97944953d8dec983ce8fe0b8fbfc.R7.Compose.RustStd
