import LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8
import LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.RustStd
import LexLeanPreservation.Compose
set_option autoImplicit false
set_option maxRecDepth 100000
set_option linter.unusedVariables false
namespace LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.Compose.RustStd

/-- The rendering of the root's entry, invoked on the encoded arguments,
realizes the encoded source result when the arguments satisfy §17.12's
invariants, and refuses them with `none` otherwise. -/
theorem root (a : (List (Prod (Prod Nat String) Bool))) (k : (Prod Nat String)) (i : (List (Prod Int8 Nat))) (j : Int8) (b : (List (Prod Bool Nat))) (c : Bool) (d : (List (Prod Int Nat))) (e : Int) (u : (List (Prod UInt64 Nat))) (w : UInt64) (hrep : LexLeanPreservation.Rust.RepresentableL [((LexLeanPreservation.encList (LexLeanPreservation.encPair (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) LexLeanTarget.TargetSyntax.Value.bool)) a), ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) k), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.i8 LexLeanTarget.TargetSyntax.Value.nat)) i), (LexLeanTarget.TargetSyntax.Value.i8 j), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.bool LexLeanTarget.TargetSyntax.Value.nat)) b), (LexLeanTarget.TargetSyntax.Value.bool c), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.int LexLeanTarget.TargetSyntax.Value.nat)) d), (LexLeanTarget.TargetSyntax.Value.int e), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u64 LexLeanTarget.TargetSyntax.Value.nat)) u), (LexLeanTarget.TargetSyntax.Value.u64 w)]) : ∃ ro, LexLeanPreservation.Rust.RCI LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.RustStd.krate (LexLeanPreservation.Rust.fnIdent 13) [((LexLeanPreservation.encList (LexLeanPreservation.encPair (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) LexLeanTarget.TargetSyntax.Value.bool)) a), ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.string) k), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.i8 LexLeanTarget.TargetSyntax.Value.nat)) i), (LexLeanTarget.TargetSyntax.Value.i8 j), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.bool LexLeanTarget.TargetSyntax.Value.nat)) b), (LexLeanTarget.TargetSyntax.Value.bool c), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.int LexLeanTarget.TargetSyntax.Value.nat)) d), (LexLeanTarget.TargetSyntax.Value.int e), ((LexLeanPreservation.encList (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u64 LexLeanTarget.TargetSyntax.Value.nat)) u), (LexLeanTarget.TargetSyntax.Value.u64 w)] ro ∧
    (LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.accepts a k i j b c d e u w → LexLeanPreservation.Rust.RealizesFn false (LexLeanPreservation.someObs (LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.denote a k i j b c d e u w)) ro) ∧
    (¬ LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.accepts a k i j b c d e u w → LexLeanPreservation.Rust.RealizesFn false (LexLeanPreservation.Obs.value LexLeanTarget.TargetSyntax.Value.none) ro) :=
  match LexLeanPreservation.Rust.compose (fun n => LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.RustStd.root n 13) rfl (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_nat LexLeanPreservation.Rust.wt_string) LexLeanPreservation.Rust.wt_bool)) a) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_nat LexLeanPreservation.Rust.wt_string) k) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_i8 LexLeanPreservation.Rust.wt_nat)) i) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_i8 j) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_bool LexLeanPreservation.Rust.wt_nat)) b) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_bool c) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_int LexLeanPreservation.Rust.wt_nat)) d) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_int e) (LexLeanPreservation.Rust.wtl_cons ((LexLeanPreservation.Rust.wt_encList (LexLeanPreservation.Rust.wt_encPair LexLeanPreservation.Rust.wt_u64 LexLeanPreservation.Rust.wt_nat)) u) (LexLeanPreservation.Rust.wtl_cons (LexLeanPreservation.Rust.wt_u64 w) LexLeanPreservation.Rust.wtl_nil)))))))))) rfl rfl (LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.entry a k i j b c d e u w) (LexLeanPreservation.Rust.rel_ne_stuck _ _) with
  | ⟨ro, hr, hc⟩ => ⟨ro, hc, fun h => LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.entry_accepts a k i j b c d e u w h ▸ hr, fun h => LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.entry_refuses a k i j b c d e u w h ▸ hr⟩

end LexLeanPreserve.Cdc460baafe2887dd57b499b5743f9c41.R8.Compose.RustStd
