import LexLeanPreservation.Core
import LexLeanPreservation.Values
import LexLeanPreservation.Primitives
import LexLeanPreservation.Fixed
import LexLeanPreservation.Keys
import LexLeanPreservation.Templates
import Coverage.Colls
import Coverage.Main
import Coverage.Prims
import Coverage.RecRoots
import Coverage.Recur
import Coverage.Syntax
import Coverage.Types
set_option autoImplicit false
set_option maxRecDepth 100000
set_option linter.unusedVariables false
namespace LexLeanPreserve.C098c9d7898f8ebcc504db089f79c1a27.R22

def __prog : LexLeanTarget.TargetSyntax.Program :=
  { adts := [], functions := [
    { parameters := [0, 1, 2], types := [(.fixed .i64), (.fixed .i64), (.fixed .u64)], result := (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.option (.fixed .u64))))))),
      body := (.build .pair (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.option (.fixed .u64))))))) [(.prim .checkedAdd [(.var 0), (.var 1)]), (.build .pair (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.option (.fixed .u64)))))) [(.prim .checkedSub [(.var 0), (.var 1)]), (.build .pair (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.option (.fixed .u64))))) [(.prim .checkedMul [(.var 0), (.var 1)]), (.build .pair (.pair (.option (.fixed .i64)) (.pair (.option (.fixed .i64)) (.option (.fixed .u64)))) [(.prim .checkedQuot [(.var 0), (.var 1)]), (.build .pair (.pair (.option (.fixed .i64)) (.option (.fixed .u64))) [(.prim .checkedNeg [(.var 0)]), (.prim .checkedAdd [(.var 2), (.value (.fixed .u64) (.u64 1))])])])])])]) }] }

def __fits_0 (a : Int64) (b : Int64) (c : UInt64) : Bool :=
  ((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((((true && true) && true) && (((true && (true && true)) && true) && true)) && true) && true)) && true) && true)) && true) && true)) && true) && true)) && true)

theorem __rel_0 (a : Int64) (b : Int64) (c : UInt64) : LexLeanPreservation.FunRel __prog 0 [(LexLeanTarget.TargetSyntax.Value.i64 a), (LexLeanTarget.TargetSyntax.Value.i64 b), (LexLeanTarget.TargetSyntax.Value.u64 c)] (LexLeanPreservation.Rel (__fits_0 a b c) ((LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u64)))))) (Coverage.Prims.fixedWide a b c))) :=
  LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_checkedAdd_i64 a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_checkedSub_i64 a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_checkedMul_i64 Coverage.Prims.LexLeanRuntime.multiplyMagnitudeInt64 (fun _ _ _ _ => rfl) (fun _ _ _ _ _ => rfl) a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_checkedQuot_i64 Coverage.Prims.LexLeanRuntime.divideMagnitudeInt64 (fun _ _ _ _ => rfl) (fun _ _ _ _ _ => rfl) a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil) (LexLeanPreservation.prim_checkedNeg_i64 a)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_checkedAdd_u64 c (1 : UInt64))) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair)

def denote (a : Int64) (b : Int64) (c : UInt64) : LexLeanPreservation.Obs :=
  LexLeanPreservation.Rel (__fits_0 a b c) ((LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u64)))))) (Coverage.Prims.fixedWide a b c))

theorem root (a : Int64) (b : Int64) (c : UInt64) : LexLeanPreservation.RunConv __prog 0 [(LexLeanTarget.TargetSyntax.Value.i64 a), (LexLeanTarget.TargetSyntax.Value.i64 b), (LexLeanTarget.TargetSyntax.Value.u64 c)] (LexLeanPreservation.Rel (__fits_0 a b c) ((LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.i64) (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u64)))))) (Coverage.Prims.fixedWide a b c))) :=
  LexLeanPreservation.run_of_funRel (__rel_0 a b c)

end LexLeanPreserve.C098c9d7898f8ebcc504db089f79c1a27.R22
