import LexLeanPreservation.Core
import LexLeanPreservation.Values
import LexLeanPreservation.Primitives
import LexLeanPreservation.Fixed
import LexLeanPreservation.Keys
import LexLeanPreservation.Templates
import Coverage.Colls
import Coverage.Main
import Coverage.Prims
import Coverage.RecRoots
import Coverage.Recur
import Coverage.Syntax
import Coverage.Types
set_option autoImplicit false
set_option maxRecDepth 100000
set_option linter.unusedVariables false
namespace LexLeanPreserve.C098c9d7898f8ebcc504db089f79c1a27.R23

def __prog : LexLeanTarget.TargetSyntax.Program :=
  { adts := [], functions := [
    { parameters := [0, 1, 2], types := [(.fixed .u16), (.fixed .u16), (.fixed .u32)], result := (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool)))))),
      body := (.build .pair (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool)))))) [(.prim .bitAnd [(.var 0), (.var 1)]), (.build .pair (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool))))) [(.prim .bitOr [(.var 0), (.var 1)]), (.build .pair (.pair (.fixed .u16) (.pair (.fixed .u16) (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool)))) [(.prim .bitXor [(.var 0), (.var 1)]), (.build .pair (.pair (.fixed .u16) (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool))) [(.prim .bitNot [(.var 0)]), (.build .pair (.pair (.option (.fixed .u16)) (.pair (.option (.fixed .u16)) .bool)) [(.prim .shiftLeft [(.var 0), (.var 2)]), (.build .pair (.pair (.option (.fixed .u16)) .bool) [(.prim .shiftRight [(.var 0), (.value (.fixed .u32) (.u32 3))]), (.prim .equal [(.var 0), (.var 1)])])])])])])]) }] }

def __fits_0 (a : UInt16) (b : UInt16) (s : UInt32) : Bool :=
  ((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((((true && true) && true) && (((((true && (true && true)) && true) && (((((true && (true && true)) && true) && (((true && (true && true)) && true) && true)) && true) && true)) && true) && true)) && true) && true)) && true) && true)) && true) && true)) && true)

theorem __rel_0 (a : UInt16) (b : UInt16) (s : UInt32) : LexLeanPreservation.FunRel __prog 0 [(LexLeanTarget.TargetSyntax.Value.u16 a), (LexLeanTarget.TargetSyntax.Value.u16 b), (LexLeanTarget.TargetSyntax.Value.u32 s)] (LexLeanPreservation.Rel (__fits_0 a b s) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) LexLeanTarget.TargetSyntax.Value.bool)))))) (Coverage.Prims.bits a b s))) :=
  LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_bitAnd_u16 a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_bitOr_u16 a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_bitXor_u16 a b)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil) (LexLeanPreservation.prim_bitNot_u16 a)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_shiftLeft_u16 a s)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_shiftRight_u16 a (3 : UInt32))) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_equal_u16 a b)) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair)

def denote (a : UInt16) (b : UInt16) (s : UInt32) : LexLeanPreservation.Obs :=
  LexLeanPreservation.Rel (__fits_0 a b s) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) LexLeanTarget.TargetSyntax.Value.bool)))))) (Coverage.Prims.bits a b s))

theorem root (a : UInt16) (b : UInt16) (s : UInt32) : LexLeanPreservation.RunConv __prog 0 [(LexLeanTarget.TargetSyntax.Value.u16 a), (LexLeanTarget.TargetSyntax.Value.u16 b), (LexLeanTarget.TargetSyntax.Value.u32 s)] (LexLeanPreservation.Rel (__fits_0 a b s) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.u16 (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) (LexLeanPreservation.encPair (LexLeanPreservation.encOption LexLeanTarget.TargetSyntax.Value.u16) LexLeanTarget.TargetSyntax.Value.bool)))))) (Coverage.Prims.bits a b s))) :=
  LexLeanPreservation.run_of_funRel (__rel_0 a b s)

end LexLeanPreserve.C098c9d7898f8ebcc504db089f79c1a27.R23
