//! Observe generated byte values independently of the byte-literal lowerer.

use crate::support::{self, P};
use serde_json::json;

pub(super) fn verify() {
    for language in ["1.1", "1.2"] {
        verify_language(language);
    }
}

fn verify_language(language: &str) {
    let project = P::example();
    project.edit(
        "lexlean.toml",
        "language = \"1.0\"",
        &format!("language = {language:?}"),
    );
    let vectors = [
        Vec::new(),
        (0..=255).collect::<Vec<u8>>(),
        vec![0, 255, 128, 0],
    ];
    let declarations = vectors
        .iter()
        .enumerate()
        .map(|(index, bytes)| {
            let hex = bytes
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<String>();
            json!({"kind":"definition", "name":format!("literal{index}"), "parameters":[],
            "result":{"kind":"bytes"}, "axioms":[], "body":{"kind":"bytes", "hex":hex}})
        })
        .collect::<Vec<_>>();
    let module = json!({"spec":"lexlean/semantic-module/1", "declarations":declarations});
    project.write("src/Main.lex.tex", &format!(
        "\\begin{{lexlean}}{{Main}}\n\\useglossary{{lexlean.std.nat@{language}.0}}\n\\title{{Natural number addition}}\n\\begin{{semanticmodule}}\n\\semanticdata{{{module}}}\n\\end{{semanticmodule}}\n\\end{{lexlean}}\n"
    ));
    project.relock();
    let _ = support::verify_ok_backed("SM-19", &project);
    if !support::lean_backed("SM-19") {
        return;
    }
    let built = project.build_ok();
    let source = project
        .build_dir(&built.build_id.expect("build identity"))
        .join("modules/LexLeanExample/Main.lean");
    let generated = std::fs::read_to_string(source).expect("generated byte definitions");
    // These are observation commands only. The values come exclusively from
    // the generated definitions; expected values are independently encoded.
    let probes = (0..vectors.len())
        .map(|index| format!("#eval LexLeanExample.Main.literal{index}.toList.map UInt8.toNat\n"))
        .collect::<String>();
    let directory = tempfile::tempdir().expect("byte observation directory");
    let path = directory.path().join("ByteObservation.lean");
    std::fs::write(&path, format!("{generated}\n{probes}"))
        .expect("generated values and observations");
    let binary = support::real_elan_home()
        .join("toolchains")
        .join(support::mangled_toolchain_name())
        .join("bin")
        .join(if cfg!(windows) { "lean.exe" } else { "lean" });
    let output = std::process::Command::new(binary)
        .arg(path)
        .current_dir(directory.path())
        .env("LEAN_PATH", "")
        .output()
        .expect("pinned Lean observes generated bytes");
    assert!(
        output.status.success(),
        "{}\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let expected = vectors
        .iter()
        .map(|bytes| format!("{bytes:?}\n"))
        .collect::<String>();
    let observed = String::from_utf8(output.stdout).expect("UTF-8 observation");
    assert_eq!(
        observed.split_whitespace().collect::<String>(),
        expected.split_whitespace().collect::<String>(),
        "every generated byte is observed in order"
    );
}
