import LexLeanPreservation.RustSound
set_option autoImplicit false
set_option maxRecDepth 100000
namespace LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R7.RustStd
open LexLeanTarget LexLeanPreservation.Rust

def program : TargetSyntax.Program :=
  { adts := [{ constructors := [[], [.nat]] }], functions := [
    { parameters := [0], types := [.nat], result := .nat,
      body := (.«match» .nat (.call 1 [(.build .pair (.pair .nat .nat) [(.var 0), (.var 0)])]) [(.arm .ok [1] (.var 1)), (.arm .error [2] (.value .nat (.nat 9)))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.result .nat (.pair .bool .bool)),
      body := (.«let» 1 (.pair (.pair .nat .nat) .bool) (.call 2 [(.var 0)]) (.«match» (.result .nat (.pair .bool .bool)) (.second (.var 1)) [(.arm .true [] (.call 3 [(.var 0), (.first (.var 1))])), (.arm .false [] (.build .error (.result .nat (.pair .bool .bool)) [(.build .pair (.pair .bool .bool) [(.build .false .bool []), (.build .false .bool [])])]))])) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.pair (.pair .nat .nat) .bool),
      body := (.call 4 [(.closure 5 []), (.prim .natAdd [(.second (.var 0)), (.value .nat (.nat 4))]), (.call 6 [(.var 0)])]) },
    { parameters := [0, 1], types := [(.pair .nat .nat), (.pair .nat .nat)], result := (.result .nat (.pair .bool .bool)),
      body := (.«match» (.result .nat (.pair .bool .bool)) (.call 7 [(.var 0), (.var 1)]) [(.arm .some [2] (.build .ok (.result .nat (.pair .bool .bool)) [(.var 2)])), (.arm .none [] (.«match» (.result .nat (.pair .bool .bool)) (.call 8 [(.var 1)]) [(.arm .some [3] (.build .error (.result .nat (.pair .bool .bool)) [(.build .pair (.pair .bool .bool) [(.build .true .bool []), (.build .false .bool [])])])), (.arm .none [] (.build .error (.result .nat (.pair .bool .bool)) [(.build .pair (.pair .bool .bool) [(.build .false .bool []), (.build .true .bool [])])]))]))]) },
    { parameters := [0, 1, 2], types := [(.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), .nat, (.pair .nat .nat)], result := (.pair (.pair .nat .nat) .bool),
      body := (.«match» (.pair (.pair .nat .nat) .bool) (.var 1) [(.arm .zero [] (.build .pair (.pair (.pair .nat .nat) .bool) [(.var 2), (.build .false .bool [])])), (.arm .succ [3] (.«match» (.pair (.pair .nat .nat) .bool) (.apply (.var 0) [(.var 2)]) [(.arm .none [] (.build .pair (.pair (.pair .nat .nat) .bool) [(.var 2), (.build .true .bool [])])), (.arm .some [4] (.call 4 [(.var 0), (.var 3), (.var 4)]))]))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.option (.pair .nat .nat)),
      body := (.«match» (.option (.pair .nat .nat)) (.call 9 [(.var 0)]) [(.arm .none [] (.build .none (.option (.pair .nat .nat)) [])), (.arm .some [1] (.call 10 [(.var 0), (.var 1)]))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.pair .nat .nat),
      body := (.build .pair (.pair .nat .nat) [(.first (.var 0)), (.prim .natAdd [(.second (.var 0)), (.value .nat (.nat 3))])]) },
    { parameters := [0, 1], types := [(.pair .nat .nat), (.pair .nat .nat)], result := (.option .nat),
      body := (.«match» (.option .nat) (.call 8 [(.var 1)]) [(.arm .none [] (.build .none (.option .nat) [])), (.arm .some [2] (.cond (.call 11 [(.var 0), (.var 2)]) (.build .some (.option .nat) [(.var 2)]) (.build .none (.option .nat) [])))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.option .nat),
      body := (.build .some (.option .nat) [(.second (.var 0))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.option (.adt 0)),
      body := (.«match» (.option (.adt 0)) (.cond (.call 12 [(.var 0)]) (.build .some (.option (.adt 0)) [(.build (.adt 0) (.adt 0) [])]) (.build .none (.option (.adt 0)) [])) [(.arm .some [1] (.build .some (.option (.adt 0)) [(.var 1)])), (.arm .none [] (.call 13 [(.closure 14 [(.var 0)]), (.build .none (.option (.adt 0)) []), (.call 15 [(.var 0)])]))]) },
    { parameters := [0, 1], types := [(.pair .nat .nat), (.adt 0)], result := (.option (.pair .nat .nat)),
      body := (.«match» (.option (.pair .nat .nat)) (.var 1) [(.arm (.adt 0) [] (.call 16 [(.var 0)])), (.arm (.adt 1) [2] (.call 17 [(.var 0), (.var 2)]))]) },
    { parameters := [0, 1], types := [(.pair .nat .nat), .nat], result := .bool,
      body := (.prim .natEq [(.var 1), (.value .nat (.nat 0))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := .bool,
      body := (.prim .natLt [(.value .nat (.nat 2)), (.second (.var 0))]) },
    { parameters := [0, 1, 2], types := [(.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (.option (.adt 0)), (.list .nat)], result := (.option (.adt 0)),
      body := (.«match» (.option (.adt 0)) (.var 2) [(.arm .nil [] (.var 1)), (.arm .cons [3, 4] (.call 13 [(.var 0), (.apply (.var 0) [(.var 1), (.var 3)]), (.var 4)]))]) },
    { parameters := [0, 1, 2], types := [(.pair .nat .nat), (.option (.adt 0)), .nat], result := (.option (.adt 0)),
      body := (.«match» (.option (.adt 0)) (.var 1) [(.arm .some [3] (.build .some (.option (.adt 0)) [(.var 3)])), (.arm .none [] (.cond (.call 18 [(.var 0), (.var 2)]) (.build .some (.option (.adt 0)) [(.build (.adt 1) (.adt 0) [(.var 2)])]) (.build .none (.option (.adt 0)) [])))]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.list .nat),
      body := (.build .cons (.list .nat) [(.value .nat (.nat 2)), (.build .cons (.list .nat) [(.value .nat (.nat 1)), (.build .nil (.list .nat) [])])]) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.option (.pair .nat .nat)),
      body := (.cond (.call 12 [(.var 0)]) (.build .some (.option (.pair .nat .nat)) [(.call 19 [(.var 0)])]) (.build .none (.option (.pair .nat .nat)) [])) },
    { parameters := [0, 1], types := [(.pair .nat .nat), .nat], result := (.option (.pair .nat .nat)),
      body := (.cond (.call 18 [(.var 0), (.var 1)]) (.build .some (.option (.pair .nat .nat)) [(.call 20 [(.var 0), (.var 1)])]) (.build .none (.option (.pair .nat .nat)) [])) },
    { parameters := [0, 1], types := [(.pair .nat .nat), .nat], result := .bool,
      body := (.cond (.prim .natLe [(.var 1), (.second (.var 0))]) (.prim .natLt [(.value .nat (.nat 0)), (.var 1)]) (.build .false .bool [])) },
    { parameters := [0], types := [(.pair .nat .nat)], result := (.pair .nat .nat),
      body := (.build .pair (.pair .nat .nat) [(.first (.var 0)), (.prim .natSub [(.second (.var 0)), (.value .nat (.nat 1))])]) },
    { parameters := [0, 1], types := [(.pair .nat .nat), .nat], result := (.pair .nat .nat),
      body := (.build .pair (.pair .nat .nat) [(.first (.var 0)), (.prim .natSub [(.second (.var 0)), (.var 1)])]) }] }

def krate : RustSyntax.Crate :=
  ({ profile := .std, items := [
    (.enum (.adt 0) [{ number := 0, fields := [] }, { number := 1, fields := [.nat] }]),
    (.enum (.fn 0) [{ number := 5, fields := [] }]),
    (.apply 0 [(.pair .nat .nat)] (.option (.pair .nat .nat)) false [{ function := 5, captures := [], functionFallible := false }]),
    (.enum (.fn 1) [{ number := 14, fields := [(.pair .nat .nat)] }]),
    (.apply 1 [(.option (.adt 0)), .nat] (.option (.adt 0)) false [{ function := 14, captures := [.copy], functionFallible := false }]),
    (.function (.generated .function 0) [{ pattern := (.bind (.generated .binding 0)), type := .nat }] (.fallible .nat) (.mk [(.mk (.bind (.generated .holder 1)) none (.call (.function 1) [(.pair (.copy (.generated .binding 0)) (.copy (.generated .binding 0)))] true))] (.matchOn (.move (.generated .holder 1)) [(.mk (.ok (.bind (.generated .binding 1))) (.mk [] (.succeed (.copy (.generated .binding 1))))), (.mk (.err .wild) (.mk [] (.succeed (.lit (.nat 9)))))]))),
    (.function (.generated .function 1) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.fallible (.result .nat (.pair .bool .bool))) (.mk [(.mk (.bind (.generated .binding 1)) (some (.pair (.pair .nat .nat) .bool)) (.call (.function 2) [(.copy (.generated .binding 0))] true)), (.mk (.bind (.generated .holder 3)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 2))]) none (.copy (.generated .binding 1)))] (.move (.generated .part 2)))))] (.cond (.move (.generated .holder 3)) (.mk [] (.succeed (.call (.function 3) [(.copy (.generated .binding 0)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 4)), .wild]) none (.copy (.generated .binding 1)))] (.move (.generated .part 4))))] false))) (.mk [] (.succeed (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool false)))])))))),
    (.function (.generated .function 2) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.fallible (.pair (.pair .nat .nat) .bool)) (.mk [] (.succeed (.call (.function 4) [(.construct (.closure 0 5) []), (.block (.mk [(.mk (.bind (.generated .operand 6)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 5))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 5))))), (.mk (.bind (.generated .operand 7)) none (.lit (.nat 4)))] (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] true))), (.call (.function 6) [(.copy (.generated .binding 0))] true)] false)))),
    (.function (.generated .function 3) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := (.pair .nat .nat) }] (.result .nat (.pair .bool .bool)) (.mk [(.mk (.bind (.generated .holder 8)) none (.call (.function 7) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false))] (.matchOn (.move (.generated .holder 8)) [(.mk .none (.mk [(.mk (.bind (.generated .holder 9)) none (.call (.function 8) [(.copy (.generated .binding 1))] false))] (.matchOn (.move (.generated .holder 9)) [(.mk .none (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool true)))]))), (.mk (.some .wild) (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool true)) (.lit (.bool false)))])))]))), (.mk (.some (.bind (.generated .binding 2))) (.mk [] (.construct (.ok .nat (.pair .bool .bool)) [(.copy (.generated .binding 2))])))]))),
    (.function (.generated .function 4) [{ pattern := (.bind (.generated .binding 0)), type := (.fn 0) }, { pattern := (.bind (.generated .binding 1)), type := .nat }, { pattern := (.bind (.generated .binding 2)), type := (.pair .nat .nat) }] (.pair (.pair .nat .nat) .bool) (.mk [(.mk (.bind (.generated .holder 10)) none (.copy (.generated .binding 1)))] (.cond (.isZero (.generated .holder 10)) (.mk [] (.pair (.copy (.generated .binding 2)) (.lit (.bool false)))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 10))), (.mk (.bind (.generated .holder 12)) none (.block (.mk [(.mk (.bind (.generated .callee 11)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 11) [(.copy (.generated .binding 2))] false))))] (.matchOn (.move (.generated .holder 12)) [(.mk .none (.mk [] (.pair (.copy (.generated .binding 2)) (.lit (.bool true))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 4) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))]))))),
    (.function (.generated .function 5) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.option (.pair .nat .nat)) (.mk [(.mk (.bind (.generated .holder 13)) none (.call (.function 9) [(.copy (.generated .binding 0))] false))] (.matchOn (.move (.generated .holder 13)) [(.mk .none (.mk [] (.construct (.none (.pair .nat .nat)) []))), (.mk (.some (.bind (.generated .binding 1))) (.mk [] (.call (.function 10) [(.copy (.generated .binding 0)), (.clone (.generated .binding 1))] false)))]))),
    (.function (.generated .function 6) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.fallible (.pair .nat .nat)) (.mk [] (.succeed (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 14)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 14)))) (.block (.mk [(.mk (.bind (.generated .operand 16)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 15))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 15))))), (.mk (.bind (.generated .operand 17)) none (.lit (.nat 3)))] (.call (.runtime .natAdd) [(.move (.generated .operand 16)), (.move (.generated .operand 17))] true))))))),
    (.function (.generated .function 7) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := (.pair .nat .nat) }] (.option .nat) (.mk [(.mk (.bind (.generated .holder 18)) none (.call (.function 8) [(.copy (.generated .binding 1))] false))] (.matchOn (.move (.generated .holder 18)) [(.mk .none (.mk [] (.construct (.none .nat) []))), (.mk (.some (.bind (.generated .binding 2))) (.mk [] (.cond (.call (.function 11) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.copy (.generated .binding 2))])) (.mk [] (.construct (.none .nat) [])))))]))),
    (.function (.generated .function 8) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.option .nat) (.mk [] (.construct .some [(.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 19))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 19))))]))),
    (.function (.generated .function 9) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.option (.adt 0)) (.mk [(.mk (.bind (.generated .holder 20)) none (.cond (.call (.function 12) [(.copy (.generated .binding 0))] false) (.mk [] (.construct .some [(.construct (.adt 0 0) [])])) (.mk [] (.construct (.none (.adt 0)) []))))] (.matchOn (.move (.generated .holder 20)) [(.mk .none (.mk [] (.call (.function 13) [(.construct (.closure 1 14) [(.copy (.generated .binding 0))]), (.construct (.none (.adt 0)) []), (.call (.function 15) [(.copy (.generated .binding 0))] false)] false))), (.mk (.some (.bind (.generated .binding 1))) (.mk [] (.construct .some [(.clone (.generated .binding 1))])))]))),
    (.function (.generated .function 10) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := (.adt 0) }] (.option (.pair .nat .nat)) (.mk [(.mk (.bind (.generated .holder 21)) none (.clone (.generated .binding 1)))] (.matchOn (.move (.generated .holder 21)) [(.mk (.adt 0 0 []) (.mk [] (.call (.function 16) [(.copy (.generated .binding 0))] false))), (.mk (.adt 0 1 [(.bind (.generated .binding 2))]) (.mk [] (.call (.function 17) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false)))]))),
    (.function (.generated .function 11) [{ pattern := .wild, type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := .nat }] .bool (.mk [(.mk (.bind (.generated .operand 22)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 23)) none (.lit (.nat 0)))] (.call (.runtime .natEq) [(.move (.generated .operand 22)), (.move (.generated .operand 23))] false))),
    (.function (.generated .function 12) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] .bool (.mk [(.mk (.bind (.generated .operand 25)) none (.lit (.nat 2))), (.mk (.bind (.generated .operand 26)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 24))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 24)))))] (.call (.runtime .natLt) [(.move (.generated .operand 25)), (.move (.generated .operand 26))] false))),
    (.function (.generated .function 13) [{ pattern := (.bind (.generated .binding 0)), type := (.fn 1) }, { pattern := (.bind (.generated .binding 1)), type := (.option (.adt 0)) }, { pattern := (.bind (.generated .binding 2)), type := (.list .nat) }] (.option (.adt 0)) (.mk [(.mk (.bind (.generated .holder 27)) none (.clone (.generated .binding 2)))] (.matchOn (.uncons (.generated .holder 27)) [(.mk .none (.mk [] (.clone (.generated .binding 1)))), (.mk (.some (.tuple [(.bind (.generated .binding 3)), (.bind (.generated .binding 4))])) (.mk [] (.call (.function 13) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 28)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 28) [(.clone (.generated .binding 1)), (.copy (.generated .binding 3))] false))), (.clone (.generated .binding 4))] false)))]))),
    (.function (.generated .function 14) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := (.option (.adt 0)) }, { pattern := (.bind (.generated .binding 2)), type := .nat }] (.option (.adt 0)) (.mk [(.mk (.bind (.generated .holder 29)) none (.clone (.generated .binding 1)))] (.matchOn (.move (.generated .holder 29)) [(.mk .none (.mk [] (.cond (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.construct (.adt 0 1) [(.copy (.generated .binding 2))])])) (.mk [] (.construct (.none (.adt 0)) []))))), (.mk (.some (.bind (.generated .binding 3))) (.mk [] (.construct .some [(.clone (.generated .binding 3))])))]))),
    (.function (.generated .function 15) [{ pattern := .wild, type := (.pair .nat .nat) }] (.list .nat) (.mk [] (.construct .cons [(.lit (.nat 2)), (.construct .cons [(.lit (.nat 1)), (.construct (.nil .nat) [])])]))),
    (.function (.generated .function 16) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.option (.pair .nat .nat)) (.mk [] (.cond (.call (.function 12) [(.copy (.generated .binding 0))] false) (.mk [] (.construct .some [(.call (.function 19) [(.copy (.generated .binding 0))] false)])) (.mk [] (.construct (.none (.pair .nat .nat)) []))))),
    (.function (.generated .function 17) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := .nat }] (.option (.pair .nat .nat)) (.mk [] (.cond (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false) (.mk [] (.construct .some [(.call (.function 20) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false)])) (.mk [] (.construct (.none (.pair .nat .nat)) []))))),
    (.function (.generated .function 18) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := .nat }] .bool (.mk [(.mk (.bind (.generated .operand 31)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 32)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 30))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 30)))))] (.cond (.call (.runtime .natLe) [(.move (.generated .operand 31)), (.move (.generated .operand 32))] false) (.mk [(.mk (.bind (.generated .operand 33)) none (.lit (.nat 0))), (.mk (.bind (.generated .operand 34)) none (.copy (.generated .binding 1)))] (.call (.runtime .natLt) [(.move (.generated .operand 33)), (.move (.generated .operand 34))] false)) (.mk [] (.lit (.bool false)))))),
    (.function (.generated .function 19) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }] (.pair .nat .nat) (.mk [] (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 35)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 35)))) (.block (.mk [(.mk (.bind (.generated .operand 37)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 36))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 36))))), (.mk (.bind (.generated .operand 38)) none (.lit (.nat 1)))] (.call (.runtime .natSub) [(.move (.generated .operand 37)), (.move (.generated .operand 38))] false)))))),
    (.function (.generated .function 20) [{ pattern := (.bind (.generated .binding 0)), type := (.pair .nat .nat) }, { pattern := (.bind (.generated .binding 1)), type := .nat }] (.pair .nat .nat) (.mk [] (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 39)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 39)))) (.block (.mk [(.mk (.bind (.generated .operand 41)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 40))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 40))))), (.mk (.bind (.generated .operand 42)) none (.copy (.generated .binding 1)))] (.call (.runtime .natSub) [(.move (.generated .operand 41)), (.move (.generated .operand 42))] false))))))] } : LexLeanTarget.RustSyntax.Crate)

def flags : Flags := [(([(.pair .nat .nat)], (.option (.pair .nat .nat))), false), (([(.option (.adt 0)), .nat], (.option (.adt 0))), false)]

theorem fun0 : FunOK program krate flags 0 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 1)) none (.call (.function 1) [(.pair (.copy (.generated .binding 0)) (.copy (.generated .binding 0)))] true))], (.matchOn (.move (.generated .holder 1)) [(.mk (.ok (.bind (.generated .binding 1))) (.mk [] (.succeed (.copy (.generated .binding 1))))), (.mk (.err .wild) (.mk [] (.succeed (.lit (.nat 9)))))]), [(0, .nat, (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.result .nat (.pair .bool .bool))) (U := []) (view := false) (idx := [0, 1]) (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.buildPair (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(1, .nat, (some 1)), (0, .nat, (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.succeed (.copy (.generated .binding 1)))) (Corr.mCons (Γ' := [(2, (.pair .bool .bool), none), (0, .nat, (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.succeed (.lit (.nat 9)))) (Corr.mNil) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.value rfl rfl)))) rfl rfl rfl (Corr.fOfB (Corr.bOfE (Corr.var rfl rfl)))) rfl rfl rfl)⟩⟩

theorem fun1 : FunOK program krate flags 1 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .binding 1)) (some (.pair (.pair .nat .nat) .bool)) (.call (.function 2) [(.copy (.generated .binding 0))] true)), (.mk (.bind (.generated .holder 3)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 2))]) none (.copy (.generated .binding 1)))] (.move (.generated .part 2)))))], (.cond (.move (.generated .holder 3)) (.mk [] (.succeed (.call (.function 3) [(.copy (.generated .binding 0)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 4)), .wild]) none (.copy (.generated .binding 1)))] (.move (.generated .part 4))))] false))) (.mk [] (.succeed (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool false)))])))), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.letBind (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) rfl (Corr.matchBool (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 2))]) none (.copy (.generated .binding 1)))]) (tail := (.move (.generated .part 2))) (Corr.second (ta := (.pair .nat .nat)) (tb := .bool) (Corr.var rfl rfl) rfl)) rfl rfl (Corr.kIf (la := []) (ta := (.succeed (.call (.function 3) [(.copy (.generated .binding 0)), (.block (.mk [(.mk (.tuple [(.bind (.generated .part 4)), .wild]) none (.copy (.generated .binding 1)))] (.move (.generated .part 4))))] false))) (lb := []) (tb := (.succeed (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool false)))]))) (Corr.fOfB (Corr.callOps (ts := [(.pair .nat .nat), (.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [(.bind (.generated .part 4)), .wild]) none (.copy (.generated .binding 1)))]) (tail := (.move (.generated .part 4))) (Corr.first (ta := (.pair .nat .nat)) (tb := .bool) (Corr.var rfl rfl) rfl)) (Corr.lNil)))) rfl rfl rfl rfl rfl)) (Corr.fOfB (Corr.build (ts := [(.pair .bool .bool)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.buildPair (Corr.lCons (Corr.buildConst rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil)))) (Corr.lNil))) rfl)))))⟩⟩

theorem fun2 : FunOK program krate flags 2 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.succeed (.call (.function 4) [(.construct (.closure 0 5) []), (.block (.mk [(.mk (.bind (.generated .operand 6)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 5))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 5))))), (.mk (.bind (.generated .operand 7)) none (.lit (.nat 4)))] (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] true))), (.call (.function 6) [(.copy (.generated .binding 0))] true)] false)), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.fOfB (Corr.callOps (ts := [(.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), .nat, (.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.closure (caps := []) (mask := []) (af := false) (ff := false) (Corr.opsNil) rfl rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 6)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 5))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 5))))), (.mk (.bind (.generated .operand 7)) none (.lit (.nat 4)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 6)), (.move (.generated .operand 7))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 5))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 5))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.lNil))))) rfl rfl rfl rfl rfl))⟩⟩

theorem fun3 : FunOK program krate flags 3 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 8)) none (.call (.function 7) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false))], (.matchOn (.move (.generated .holder 8)) [(.mk .none (.mk [(.mk (.bind (.generated .holder 9)) none (.call (.function 8) [(.copy (.generated .binding 1))] false))] (.matchOn (.move (.generated .holder 9)) [(.mk .none (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool true)))]))), (.mk (.some .wild) (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool true)) (.lit (.bool false)))])))]))), (.mk (.some (.bind (.generated .binding 2))) (.mk [] (.construct (.ok .nat (.pair .bool .bool)) [(.copy (.generated .binding 2))])))]), [(1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.option .nat)) (U := []) (view := false) (idx := [1, 0]) (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat), (.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := [(.mk (.bind (.generated .holder 9)) none (.call (.function 8) [(.copy (.generated .binding 1))] false))]) (tail := (.matchOn (.move (.generated .holder 9)) [(.mk .none (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool true)))]))), (.mk (.some .wild) (.mk [] (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool true)) (.lit (.bool false)))])))])) (Corr.mCons (Γ' := [(2, .nat, (some 2)), (1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct (.ok .nat (.pair .bool .bool)) [(.copy (.generated .binding 2))])) (Corr.mNil) rfl rfl rfl (Corr.build (ts := [.nat]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl)) rfl rfl rfl (Corr.matchArms (st := (.option .nat)) (U := []) (view := false) (idx := [1, 0]) (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool false)) (.lit (.bool true)))])) (Corr.mCons (Γ' := [(3, .nat, none), (1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct (.err .nat (.pair .bool .bool)) [(.pair (.lit (.bool true)) (.lit (.bool false)))])) (Corr.mNil) rfl rfl rfl (Corr.build (ts := [(.pair .bool .bool)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.buildPair (Corr.lCons (Corr.buildConst rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil)))) (Corr.lNil))) rfl)) rfl rfl rfl (Corr.build (ts := [(.pair .bool .bool)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.buildPair (Corr.lCons (Corr.buildConst rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil)))) (Corr.lNil))) rfl)) rfl rfl rfl)) rfl rfl rfl)⟩⟩

theorem fun4 : FunOK program krate flags 4 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 10)) none (.copy (.generated .binding 1)))], (.cond (.isZero (.generated .holder 10)) (.mk [] (.pair (.copy (.generated .binding 2)) (.lit (.bool false)))) (.mk [(.mk (.bind (.generated .binding 3)) none (.predecessor (.generated .holder 10))), (.mk (.bind (.generated .holder 12)) none (.block (.mk [(.mk (.bind (.generated .callee 11)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 11) [(.copy (.generated .binding 2))] false))))] (.matchOn (.move (.generated .holder 12)) [(.mk .none (.mk [] (.pair (.copy (.generated .binding 2)) (.lit (.bool true))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 4) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))]))), [(2, (.pair .nat .nat), (some 2)), (1, .nat, (some 1)), (0, (.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), (some 0))], rfl, rfl,
    (Corr.matchNat (sl := (some 3)) (Corr.var rfl rfl) rfl rfl rfl (Corr.kIf (la := []) (ta := (.pair (.copy (.generated .binding 2)) (.lit (.bool false)))) (lb := [(.mk (.bind (.generated .holder 12)) none (.block (.mk [(.mk (.bind (.generated .callee 11)) (some (.fn 0)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 11) [(.copy (.generated .binding 2))] false))))]) (tb := (.matchOn (.move (.generated .holder 12)) [(.mk .none (.mk [] (.pair (.copy (.generated .binding 2)) (.lit (.bool true))))), (.mk (.some (.bind (.generated .binding 4))) (.mk [] (.call (.function 4) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)))])) (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil))))) (Corr.matchArms (st := (.option (.pair .nat .nat))) (U := []) (view := false) (idx := [0, 1]) (Corr.eOfB (lets := [(.mk (.bind (.generated .callee 11)) (some (.fn 0)) (.clone (.generated .binding 0)))]) (tail := (.apply (.generated .callee 11) [(.copy (.generated .binding 2))] false)) (Corr.apply (ps := [(.pair .nat .nat)]) (af := false) (Corr.var rfl rfl) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(3, .nat, (some 3)), (2, (.pair .nat .nat), (some 2)), (1, .nat, (some 1)), (0, (.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.pair (.copy (.generated .binding 2)) (.lit (.bool true)))) (Corr.mCons (Γ' := [(4, (.pair .nat .nat), (some 4)), (3, .nat, (some 3)), (2, (.pair .nat .nat), (some 2)), (1, .nat, (some 1)), (0, (.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 4) [(.clone (.generated .binding 0)), (.copy (.generated .binding 3)), (.copy (.generated .binding 4))] false)) (Corr.mNil) rfl rfl rfl (Corr.callOps (ts := [(.fn [(.pair .nat .nat)] (.option (.pair .nat .nat))), .nat, (.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.buildConst rfl) (Corr.lNil)))))) rfl rfl rfl)))⟩⟩

theorem fun5 : FunOK program krate flags 5 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 13)) none (.call (.function 9) [(.copy (.generated .binding 0))] false))], (.matchOn (.move (.generated .holder 13)) [(.mk .none (.mk [] (.construct (.none (.pair .nat .nat)) []))), (.mk (.some (.bind (.generated .binding 1))) (.mk [] (.call (.function 10) [(.copy (.generated .binding 0)), (.clone (.generated .binding 1))] false)))]), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.option (.adt 0))) (U := []) (view := false) (idx := [0, 1]) (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct (.none (.pair .nat .nat)) [])) (Corr.mCons (Γ' := [(1, (.adt 0), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 10) [(.copy (.generated .binding 0)), (.clone (.generated .binding 1))] false)) (Corr.mNil) rfl rfl rfl (Corr.callOps (ts := [(.pair .nat .nat), (.adt 0)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)) rfl rfl rfl)⟩⟩

theorem fun6 : FunOK program krate flags 6 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.succeed (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 14)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 14)))) (.block (.mk [(.mk (.bind (.generated .operand 16)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 15))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 15))))), (.mk (.bind (.generated .operand 17)) none (.lit (.nat 3)))] (.call (.runtime .natAdd) [(.move (.generated .operand 16)), (.move (.generated .operand 17))] true))))), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.fOfB (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [(.bind (.generated .part 14)), .wild]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 14))) (Corr.first (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 16)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 15))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 15))))), (.mk (.bind (.generated .operand 17)) none (.lit (.nat 3)))]) (tail := (.call (.runtime .natAdd) [(.move (.generated .operand 16)), (.move (.generated .operand 17))] true)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 15))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 15))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.lNil))))))⟩⟩

theorem fun7 : FunOK program krate flags 7 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 18)) none (.call (.function 8) [(.copy (.generated .binding 1))] false))], (.matchOn (.move (.generated .holder 18)) [(.mk .none (.mk [] (.construct (.none .nat) []))), (.mk (.some (.bind (.generated .binding 2))) (.mk [] (.cond (.call (.function 11) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.copy (.generated .binding 2))])) (.mk [] (.construct (.none .nat) [])))))]), [(1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.option .nat)) (U := []) (view := false) (idx := [0, 1]) (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.mCons (Γ' := [(1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct (.none .nat) [])) (Corr.mCons (Γ' := [(2, .nat, (some 2)), (1, (.pair .nat .nat), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.cond (.call (.function 11) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.copy (.generated .binding 2))])) (.mk [] (.construct (.none .nat) [])))) (Corr.mNil) rfl rfl rfl (Corr.cond (lc := []) (ce := (.call (.function 11) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false)) (lk := []) (Corr.callOps (ts := [(.pair .nat .nat), .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.construct .some [(.copy (.generated .binding 2))])) (lb := []) (tb := (.construct (.none .nat) [])) (Corr.build (ts := [.nat]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl) (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)))) rfl rfl rfl (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)) rfl rfl rfl)⟩⟩

theorem fun8 : FunOK program krate flags 8 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.construct .some [(.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 19))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 19))))]), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.build (ts := [.nat]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 19))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 19))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lNil))) rfl)⟩⟩

theorem fun9 : FunOK program krate flags 9 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 20)) none (.cond (.call (.function 12) [(.copy (.generated .binding 0))] false) (.mk [] (.construct .some [(.construct (.adt 0 0) [])])) (.mk [] (.construct (.none (.adt 0)) []))))], (.matchOn (.move (.generated .holder 20)) [(.mk .none (.mk [] (.call (.function 13) [(.construct (.closure 1 14) [(.copy (.generated .binding 0))]), (.construct (.none (.adt 0)) []), (.call (.function 15) [(.copy (.generated .binding 0))] false)] false))), (.mk (.some (.bind (.generated .binding 1))) (.mk [] (.construct .some [(.clone (.generated .binding 1))])))]), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.option (.adt 0))) (U := []) (view := false) (idx := [1, 0]) (Corr.eOfBNil (Corr.cond (lc := []) (ce := (.call (.function 12) [(.copy (.generated .binding 0))] false)) (lk := []) (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.construct .some [(.construct (.adt 0 0) [])])) (lb := []) (tb := (.construct (.none (.adt 0)) [])) (Corr.build (ts := [(.adt 0)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)) (Corr.lNil))) rfl) (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)))) (Corr.mCons (Γ' := [(0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 13) [(.construct (.closure 1 14) [(.copy (.generated .binding 0))]), (.construct (.none (.adt 0)) []), (.call (.function 15) [(.copy (.generated .binding 0))] false)] false)) (Corr.mCons (Γ' := [(1, (.adt 0), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct .some [(.clone (.generated .binding 1))])) (Corr.mNil) rfl rfl rfl (Corr.build (ts := [(.adt 0)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl)) rfl rfl rfl (Corr.callOps (ts := [(.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (.option (.adt 0)), (.list .nat)]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.closure (caps := [(.pair .nat .nat)]) (mask := [false]) (af := false) (ff := false) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl rfl rfl)) (Corr.lCons (Corr.eOfBNil (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)) (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.lNil))))) rfl rfl rfl rfl rfl)) rfl rfl rfl)⟩⟩

theorem fun10 : FunOK program krate flags 10 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 21)) none (.clone (.generated .binding 1)))], (.matchOn (.move (.generated .holder 21)) [(.mk (.adt 0 0 []) (.mk [] (.call (.function 16) [(.copy (.generated .binding 0))] false))), (.mk (.adt 0 1 [(.bind (.generated .binding 2))]) (.mk [] (.call (.function 17) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false)))]), [(1, (.adt 0), (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.adt 0)) (U := []) (view := false) (idx := [0, 1]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(1, (.adt 0), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.call (.function 16) [(.copy (.generated .binding 0))] false)) (Corr.mCons (Γ' := [(2, .nat, (some 2)), (1, (.adt 0), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 17) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false)) (Corr.mNil) rfl rfl rfl (Corr.callOps (ts := [(.pair .nat .nat), .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) rfl rfl rfl)⟩⟩

theorem fun11 : FunOK program krate flags 11 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 22)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 23)) none (.lit (.nat 0)))], (.call (.runtime .natEq) [(.move (.generated .operand 22)), (.move (.generated .operand 23))] false), [(1, .nat, (some 1)), (0, (.pair .nat .nat), none)], rfl, rfl,
    (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)⟩⟩

theorem fun12 : FunOK program krate flags 12 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 25)) none (.lit (.nat 2))), (.mk (.bind (.generated .operand 26)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 24))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 24)))))], (.call (.runtime .natLt) [(.move (.generated .operand 25)), (.move (.generated .operand 26))] false), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 24))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 24))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)⟩⟩

theorem fun13 : FunOK program krate flags 13 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 27)) none (.clone (.generated .binding 2)))], (.matchOn (.uncons (.generated .holder 27)) [(.mk .none (.mk [] (.clone (.generated .binding 1)))), (.mk (.some (.tuple [(.bind (.generated .binding 3)), (.bind (.generated .binding 4))])) (.mk [] (.call (.function 13) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 28)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 28) [(.clone (.generated .binding 1)), (.copy (.generated .binding 3))] false))), (.clone (.generated .binding 4))] false)))]), [(2, (.list .nat), (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.list .nat)) (U := []) (view := true) (idx := [0, 1]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(2, (.list .nat), (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.clone (.generated .binding 1))) (Corr.mCons (Γ' := [(4, (.list .nat), (some 4)), (3, .nat, (some 3)), (2, (.list .nat), (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.call (.function 13) [(.clone (.generated .binding 0)), (.block (.mk [(.mk (.bind (.generated .callee 28)) (some (.fn 1)) (.clone (.generated .binding 0)))] (.apply (.generated .callee 28) [(.clone (.generated .binding 1)), (.copy (.generated .binding 3))] false))), (.clone (.generated .binding 4))] false)) (Corr.mNil) rfl rfl rfl (Corr.callOps (ts := [(.fn [(.option (.adt 0)), .nat] (.option (.adt 0))), (.option (.adt 0)), (.list .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .callee 28)) (some (.fn 1)) (.clone (.generated .binding 0)))]) (tail := (.apply (.generated .callee 28) [(.clone (.generated .binding 1)), (.copy (.generated .binding 3))] false)) (Corr.apply (ps := [(.option (.adt 0)), .nat]) (af := false) (Corr.var rfl rfl) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl)) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))))) rfl rfl rfl rfl rfl)) rfl rfl rfl (Corr.bOfE (Corr.var rfl rfl))) rfl rfl rfl)⟩⟩

theorem fun14 : FunOK program krate flags 14 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .holder 29)) none (.clone (.generated .binding 1)))], (.matchOn (.move (.generated .holder 29)) [(.mk .none (.mk [] (.cond (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.construct (.adt 0 1) [(.copy (.generated .binding 2))])])) (.mk [] (.construct (.none (.adt 0)) []))))), (.mk (.some (.bind (.generated .binding 3))) (.mk [] (.construct .some [(.clone (.generated .binding 3))])))]), [(2, .nat, (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.matchArms (st := (.option (.adt 0))) (U := []) (view := false) (idx := [1, 0]) (Corr.var rfl rfl) (Corr.mCons (Γ' := [(2, .nat, (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 1) (loads := []) (lets := []) (tail := (.cond (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false) (.mk [] (.construct .some [(.construct (.adt 0 1) [(.copy (.generated .binding 2))])])) (.mk [] (.construct (.none (.adt 0)) [])))) (Corr.mCons (Γ' := [(3, (.adt 0), (some 3)), (2, .nat, (some 2)), (1, (.option (.adt 0)), (some 1)), (0, (.pair .nat .nat), (some 0))]) (j := 0) (loads := []) (lets := []) (tail := (.construct .some [(.clone (.generated .binding 3))])) (Corr.mNil) rfl rfl rfl (Corr.build (ts := [(.adt 0)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl)) rfl rfl rfl (Corr.cond (lc := []) (ce := (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 2))] false)) (lk := []) (Corr.callOps (ts := [(.pair .nat .nat), .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.construct .some [(.construct (.adt 0 1) [(.copy (.generated .binding 2))])])) (lb := []) (tb := (.construct (.none (.adt 0)) [])) (Corr.build (ts := [(.adt 0)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.build (ts := [.nat]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl)) (Corr.lNil))) rfl) (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)))) rfl rfl rfl)⟩⟩

theorem fun15 : FunOK program krate flags 15 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.construct .cons [(.lit (.nat 2)), (.construct .cons [(.lit (.nat 1)), (.construct (.nil .nat) [])])]), [(0, (.pair .nat .nat), none)], rfl, rfl,
    (Corr.build (ts := [.nat, (.list .nat)]) (mask := [false, false]) (Corr.opsOfL (Corr.lCons (Corr.value rfl rfl) (Corr.lCons (Corr.eOfBNil (Corr.build (ts := [.nat, (.list .nat)]) (mask := [false, false]) (Corr.opsOfL (Corr.lCons (Corr.value rfl rfl) (Corr.lCons (Corr.eOfBNil (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)) (Corr.lNil)))) rfl)) (Corr.lNil)))) rfl)⟩⟩

theorem fun16 : FunOK program krate flags 16 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.cond (.call (.function 12) [(.copy (.generated .binding 0))] false) (.mk [] (.construct .some [(.call (.function 19) [(.copy (.generated .binding 0))] false)])) (.mk [] (.construct (.none (.pair .nat .nat)) []))), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.cond (lc := []) (ce := (.call (.function 12) [(.copy (.generated .binding 0))] false)) (lk := []) (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.construct .some [(.call (.function 19) [(.copy (.generated .binding 0))] false)])) (lb := []) (tb := (.construct (.none (.pair .nat .nat)) [])) (Corr.build (ts := [(.pair .nat .nat)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat)]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lNil))) rfl rfl rfl rfl rfl)) (Corr.lNil))) rfl) (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)))⟩⟩

theorem fun17 : FunOK program krate flags 17 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.cond (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false) (.mk [] (.construct .some [(.call (.function 20) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false)])) (.mk [] (.construct (.none (.pair .nat .nat)) []))), [(1, .nat, (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.cond (lc := []) (ce := (.call (.function 18) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false)) (lk := []) (Corr.callOps (ts := [(.pair .nat .nat), .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl) (Corr.kIf (la := []) (ta := (.construct .some [(.call (.function 20) [(.copy (.generated .binding 0)), (.copy (.generated .binding 1))] false)])) (lb := []) (tb := (.construct (.none (.pair .nat .nat)) [])) (Corr.build (ts := [(.pair .nat .nat)]) (mask := [false]) (Corr.opsOfL (Corr.lCons (Corr.eOfBNil (Corr.callOps (ts := [(.pair .nat .nat), .nat]) (Corr.opsOfL (Corr.lCons (Corr.var rfl rfl) (Corr.lCons (Corr.var rfl rfl) (Corr.lNil)))) rfl rfl rfl rfl rfl)) (Corr.lNil))) rfl) (Corr.build (ts := []) (mask := []) (Corr.opsNil) rfl)))⟩⟩

theorem fun18 : FunOK program krate flags 18 :=
  ⟨_, rfl, .inl ⟨_, _, [(.mk (.bind (.generated .operand 31)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 32)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 30))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 30)))))], (.cond (.call (.runtime .natLe) [(.move (.generated .operand 31)), (.move (.generated .operand 32))] false) (.mk [(.mk (.bind (.generated .operand 33)) none (.lit (.nat 0))), (.mk (.bind (.generated .operand 34)) none (.copy (.generated .binding 1)))] (.call (.runtime .natLt) [(.move (.generated .operand 33)), (.move (.generated .operand 34))] false)) (.mk [] (.lit (.bool false)))), [(1, .nat, (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.cond (lc := [(.mk (.bind (.generated .operand 31)) none (.copy (.generated .binding 1))), (.mk (.bind (.generated .operand 32)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 30))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 30)))))]) (ce := (.call (.runtime .natLe) [(.move (.generated .operand 31)), (.move (.generated .operand 32))] false)) (lk := []) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 30))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 30))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl) (Corr.kIf (la := [(.mk (.bind (.generated .operand 33)) none (.lit (.nat 0))), (.mk (.bind (.generated .operand 34)) none (.copy (.generated .binding 1)))]) (ta := (.call (.runtime .natLt) [(.move (.generated .operand 33)), (.move (.generated .operand 34))] false)) (lb := []) (tb := (.lit (.bool false))) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl) (Corr.bOfE (Corr.buildConst rfl))))⟩⟩

theorem fun19 : FunOK program krate flags 19 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 35)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 35)))) (.block (.mk [(.mk (.bind (.generated .operand 37)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 36))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 36))))), (.mk (.bind (.generated .operand 38)) none (.lit (.nat 1)))] (.call (.runtime .natSub) [(.move (.generated .operand 37)), (.move (.generated .operand 38))] false)))), [(0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [(.bind (.generated .part 35)), .wild]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 35))) (Corr.first (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 37)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 36))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 36))))), (.mk (.bind (.generated .operand 38)) none (.lit (.nat 1)))]) (tail := (.call (.runtime .natSub) [(.move (.generated .operand 37)), (.move (.generated .operand 38))] false)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 36))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 36))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsCons (Corr.value rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.lNil)))))⟩⟩

theorem fun20 : FunOK program krate flags 20 :=
  ⟨_, rfl, .inl ⟨_, _, [], (.pair (.block (.mk [(.mk (.tuple [(.bind (.generated .part 39)), .wild]) none (.copy (.generated .binding 0)))] (.move (.generated .part 39)))) (.block (.mk [(.mk (.bind (.generated .operand 41)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 40))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 40))))), (.mk (.bind (.generated .operand 42)) none (.copy (.generated .binding 1)))] (.call (.runtime .natSub) [(.move (.generated .operand 41)), (.move (.generated .operand 42))] false)))), [(1, .nat, (some 1)), (0, (.pair .nat .nat), (some 0))], rfl, rfl,
    (Corr.bOfE (Corr.buildPair (Corr.lCons (Corr.eOfB (lets := [(.mk (.tuple [(.bind (.generated .part 39)), .wild]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 39))) (Corr.first (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.lCons (Corr.eOfB (lets := [(.mk (.bind (.generated .operand 41)) none (.block (.mk [(.mk (.tuple [.wild, (.bind (.generated .part 40))]) none (.copy (.generated .binding 0)))] (.move (.generated .part 40))))), (.mk (.bind (.generated .operand 42)) none (.copy (.generated .binding 1)))]) (tail := (.call (.runtime .natSub) [(.move (.generated .operand 41)), (.move (.generated .operand 42))] false)) (Corr.prim (ts := [.nat, .nat]) (Corr.opsCons (Corr.eOfB (lets := [(.mk (.tuple [.wild, (.bind (.generated .part 40))]) none (.copy (.generated .binding 0)))]) (tail := (.move (.generated .part 40))) (Corr.second (ta := .nat) (tb := .nat) (Corr.var rfl rfl) rfl)) (Corr.opsCons (Corr.var rfl rfl) (Corr.opsNil) rfl rfl) rfl rfl) rfl rfl rfl rfl rfl rfl)) (Corr.lNil)))))⟩⟩

theorem crate_ok : CrateOK program krate flags := by
  intro f fn h
  match f with
  | 0 => exact fun0
  | 1 => exact fun1
  | 2 => exact fun2
  | 3 => exact fun3
  | 4 => exact fun4
  | 5 => exact fun5
  | 6 => exact fun6
  | 7 => exact fun7
  | 8 => exact fun8
  | 9 => exact fun9
  | 10 => exact fun10
  | 11 => exact fun11
  | 12 => exact fun12
  | 13 => exact fun13
  | 14 => exact fun14
  | 15 => exact fun15
  | 16 => exact fun16
  | 17 => exact fun17
  | 18 => exact fun18
  | 19 => exact fun19
  | 20 => exact fun20
  | _ + 21 => simp [program, index_eq] at h

/-- Every function of the program is simulated by its rendering. -/
theorem root : ∀ n f, FunSem program krate flags n f := fun n f => simulate crate_ok n f

end LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R7.RustStd
