import LexLeanPreservation.Core
import LexLeanPreservation.Values
import LexLeanPreservation.Primitives
import LexLeanPreservation.Fixed
import LexLeanPreservation.Keys
import LexLeanPreservation.Templates
import Coverage.Colls
import Coverage.Main
import Coverage.Prims
import Coverage.RecRoots
import Coverage.Recur
import Coverage.Syntax
import Coverage.Types
set_option autoImplicit false
set_option maxRecDepth 100000
set_option linter.unusedVariables false
namespace LexLeanPreserve.Ca8439f8ad54c9966573138a0891a81f4.R31

def __prog : LexLeanTarget.TargetSyntax.Program :=
  { adts := [], functions := [
    { parameters := [0, 1], types := [.nat, .nat], result := (.pair .nat (.pair .nat .nat)),
      body := (.build .pair (.pair .nat (.pair .nat .nat)) [(.call 1 [(.var 0), (.value .nat (.nat 0))]), (.build .pair (.pair .nat .nat) [(.call 2 [(.var 0), (.var 1)]), (.call 3 [(.var 0), (.value .nat (.nat 0)), (.var 1)])])]) },
    { parameters := [0, 1], types := [.nat, .nat], result := .nat,
      body := (.cond (.prim .natLt [(.var 0), (.value .nat (.nat 2))]) (.var 1) (.call 1 [(.prim .natSub [(.var 0), (.value .nat (.nat 2))]), (.prim .natAdd [(.var 1), (.value .nat (.nat 1))])])) },
    { parameters := [0, 1], types := [.nat, .nat], result := .nat,
      body := (.cond (.prim .natEq [(.var 1), (.value .nat (.nat 0))]) (.var 0) (.cond (.prim .natLt [(.var 0), (.var 1)]) (.var 0) (.call 2 [(.prim .natSub [(.var 0), (.var 1)]), (.var 1)]))) },
    { parameters := [0, 1, 2], types := [.nat, .nat, .nat], result := .nat,
      body := (.cond (.prim .natLt [(.var 1), (.var 2)]) (.cond (.prim .natLe [(.var 0), (.prim .natAdd [(.var 1), (.var 1)])]) (.var 1) (.call 3 [(.var 0), (.prim .natAdd [(.var 1), (.value .nat (.nat 1))]), (.var 2)])) (.var 2)) }] }

def __fits_1 (number : Nat) (steps : Nat) : Bool :=
  (((true && (true && true)) && true) && (match (generalizing := false) __decrease0 : (Nat.blt number (2 : Nat)) with | true => true | false => ((((true && (true && true)) && true) && (((true && (true && true)) && (Nat.blt (steps + (1 : Nat)) 18446744073709551616)) && true)) && (__fits_1 ((Coverage.Recur.LexLeanRuntime.subtract (number) ((2 : Nat)) : Nat)) ((steps + (1 : Nat)))))))
termination_by number
decreasing_by all_goals first | (have __evidence := Coverage.Recur.countdown_decreases (number) (steps) (__decrease0); subst_vars; exact __evidence)

theorem __rel_1 (number : Nat) (steps : Nat) : LexLeanPreservation.FunRel __prog 1 [(LexLeanTarget.TargetSyntax.Value.nat number), (LexLeanTarget.TargetSyntax.Value.nat steps)] (LexLeanPreservation.Rel (__fits_1 number steps) (LexLeanTarget.TargetSyntax.Value.nat (Coverage.Recur.countdown number steps))) := by
  rw [Coverage.Recur.countdown.eq_def, __fits_1.eq_def]
  exact LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_cond (fun (__b : Bool) => (match (generalizing := false) __decrease0 : __b with | true => true | false => ((((true && (true && true)) && true) && (((true && (true && true)) && (Nat.blt (steps + (1 : Nat)) 18446744073709551616)) && true)) && (__fits_1 ((Coverage.Recur.LexLeanRuntime.subtract (number) ((2 : Nat)) : Nat)) ((steps + (1 : Nat))))))) (fun (__b : Bool) => LexLeanTarget.TargetSyntax.Value.nat (match (generalizing := false) __decrease0 : __b with | true => steps | false => (Coverage.Recur.countdown ((Coverage.Recur.LexLeanRuntime.subtract (number) ((2 : Nat)) : Nat)) ((steps + (1 : Nat)))))) (Nat.blt number (2 : Nat)) (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natLt number (2 : Nat))) (fun __decrease0 => (LexLeanPreservation.conv_var rfl)) (fun __decrease0 => (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natSub number (2 : Nat))) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natAdd steps (1 : Nat))) LexLeanPreservation.convL_nil)) (__rel_1 ((Coverage.Recur.LexLeanRuntime.subtract (number) ((2 : Nat)) : Nat)) ((steps + (1 : Nat)))))))
termination_by number
decreasing_by all_goals first | (have __evidence := Coverage.Recur.countdown_decreases (number) (steps) (__decrease0); subst_vars; exact __evidence)

def __fits_2 (value : Nat) (bound : Nat) : Bool :=
  (((true && (true && true)) && true) && (match (generalizing := false) __decrease0 : (Nat.beq bound (0 : Nat)) with | true => true | false => (((true && (true && true)) && true) && (match (generalizing := false) __decrease1 : (Nat.blt value bound) with | true => true | false => ((((true && (true && true)) && true) && (true && true)) && (__fits_2 ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound)))))))
termination_by value
decreasing_by all_goals first | (have __evidence := Coverage.Recur.reduce_decreases (value) (bound) (__decrease0) (__decrease1); subst_vars; exact __evidence)

theorem __rel_2 (value : Nat) (bound : Nat) : LexLeanPreservation.FunRel __prog 2 [(LexLeanTarget.TargetSyntax.Value.nat value), (LexLeanTarget.TargetSyntax.Value.nat bound)] (LexLeanPreservation.Rel (__fits_2 value bound) (LexLeanTarget.TargetSyntax.Value.nat (Coverage.Recur.reduce value bound))) := by
  rw [Coverage.Recur.reduce.eq_def, __fits_2.eq_def]
  exact LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_cond (fun (__b : Bool) => (match (generalizing := false) __decrease0 : __b with | true => true | false => (((true && (true && true)) && true) && (match (generalizing := false) __decrease1 : (Nat.blt value bound) with | true => true | false => ((((true && (true && true)) && true) && (true && true)) && (__fits_2 ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound))))))) (fun (__b : Bool) => LexLeanTarget.TargetSyntax.Value.nat (match (generalizing := false) __decrease0 : __b with | true => value | false => (match (generalizing := false) __decrease1 : (Nat.blt value bound) with | true => value | false => (Coverage.Recur.reduce ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound))))) (Nat.beq bound (0 : Nat)) (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natEq bound (0 : Nat))) (fun __decrease0 => (LexLeanPreservation.conv_var rfl)) (fun __decrease0 => (LexLeanPreservation.conv_cond (fun (__b : Bool) => (match (generalizing := false) __decrease1 : __b with | true => true | false => ((((true && (true && true)) && true) && (true && true)) && (__fits_2 ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound))))) (fun (__b : Bool) => LexLeanTarget.TargetSyntax.Value.nat (match (generalizing := false) __decrease1 : __b with | true => value | false => (Coverage.Recur.reduce ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound)))) (Nat.blt value bound) (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natLt value bound)) (fun __decrease1 => (LexLeanPreservation.conv_var rfl)) (fun __decrease1 => (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natSub value bound)) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (__rel_2 ((Coverage.Recur.LexLeanRuntime.subtract (value) (bound) : Nat)) (bound)))))))
termination_by value
decreasing_by all_goals first | (have __evidence := Coverage.Recur.reduce_decreases (value) (bound) (__decrease0) (__decrease1); subst_vars; exact __evidence)

def __fits_3 (target : Nat) (low : Nat) (high : Nat) : Bool :=
  (((true && (true && true)) && true) && (match (generalizing := false) __decrease0 : (Nat.blt low high) with | true => (((true && (((true && (true && true)) && (Nat.blt (low + low) 18446744073709551616)) && true)) && true) && (match (generalizing := false) __decrease1 : (Nat.ble target (low + low)) with | true => true | false => ((true && (((true && (true && true)) && (Nat.blt (low + (1 : Nat)) 18446744073709551616)) && (true && true))) && (__fits_3 (target) ((low + (1 : Nat))) (high))))) | false => true))
termination_by (Coverage.Recur.LexLeanRuntime.subtract (high) (low) : Nat)
decreasing_by all_goals first | (have __evidence := Coverage.Recur.search_decreases (target) (low) (high) (__decrease0) (__decrease1); subst_vars; exact __evidence)

theorem __rel_3 (target : Nat) (low : Nat) (high : Nat) : LexLeanPreservation.FunRel __prog 3 [(LexLeanTarget.TargetSyntax.Value.nat target), (LexLeanTarget.TargetSyntax.Value.nat low), (LexLeanTarget.TargetSyntax.Value.nat high)] (LexLeanPreservation.Rel (__fits_3 target low high) (LexLeanTarget.TargetSyntax.Value.nat (Coverage.Recur.search target low high))) := by
  rw [Coverage.Recur.search.eq_def, __fits_3.eq_def]
  exact LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_cond (fun (__b : Bool) => (match (generalizing := false) __decrease0 : __b with | true => (((true && (((true && (true && true)) && (Nat.blt (low + low) 18446744073709551616)) && true)) && true) && (match (generalizing := false) __decrease1 : (Nat.ble target (low + low)) with | true => true | false => ((true && (((true && (true && true)) && (Nat.blt (low + (1 : Nat)) 18446744073709551616)) && (true && true))) && (__fits_3 (target) ((low + (1 : Nat))) (high))))) | false => true)) (fun (__b : Bool) => LexLeanTarget.TargetSyntax.Value.nat (match (generalizing := false) __decrease0 : __b with | true => (match (generalizing := false) __decrease1 : (Nat.ble target (low + low)) with | true => low | false => (Coverage.Recur.search (target) ((low + (1 : Nat))) (high))) | false => high)) (Nat.blt low high) (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natLt low high)) (fun __decrease0 => (LexLeanPreservation.conv_cond (fun (__b : Bool) => (match (generalizing := false) __decrease1 : __b with | true => true | false => ((true && (((true && (true && true)) && (Nat.blt (low + (1 : Nat)) 18446744073709551616)) && (true && true))) && (__fits_3 (target) ((low + (1 : Nat))) (high))))) (fun (__b : Bool) => LexLeanTarget.TargetSyntax.Value.nat (match (generalizing := false) __decrease1 : __b with | true => low | false => (Coverage.Recur.search (target) ((low + (1 : Nat))) (high)))) (Nat.ble target (low + low)) (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natAdd low low)) LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natLe target (low + low))) (fun __decrease1 => (LexLeanPreservation.conv_var rfl)) (fun __decrease1 => (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_prim (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (LexLeanPreservation.prim_natAdd low (1 : Nat))) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil))) (__rel_3 (target) ((low + (1 : Nat))) (high)))))) (fun __decrease0 => (LexLeanPreservation.conv_var rfl)))
termination_by (Coverage.Recur.LexLeanRuntime.subtract (high) (low) : Nat)
decreasing_by all_goals first | (have __evidence := Coverage.Recur.search_decreases (target) (low) (high) (__decrease0) (__decrease1); subst_vars; exact __evidence)

def __fits_0 (a : Nat) (b : Nat) : Bool :=
  ((((true && (true && true)) && (__fits_1 (a) ((0 : Nat)))) && (((((true && (true && true)) && (__fits_2 (a) (b))) && (((true && (true && (true && true))) && (__fits_3 (a) ((0 : Nat)) (b))) && true)) && true) && true)) && true)

theorem __rel_0 (a : Nat) (b : Nat) : LexLeanPreservation.FunRel __prog 0 [(LexLeanTarget.TargetSyntax.Value.nat a), (LexLeanTarget.TargetSyntax.Value.nat b)] (LexLeanPreservation.Rel (__fits_0 a b) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.nat)) (Coverage.RecRoots.wellFounded a b))) :=
  LexLeanPreservation.funRel_intro rfl rfl (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value LexLeanPreservation.convL_nil)) (__rel_1 (a) ((0 : Nat)))) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_build (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil)) (__rel_2 (a) (b))) (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_call (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) (LexLeanPreservation.convL_cons LexLeanPreservation.conv_value (LexLeanPreservation.convL_cons (LexLeanPreservation.conv_var rfl) LexLeanPreservation.convL_nil))) (__rel_3 (a) ((0 : Nat)) (b))) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair) LexLeanPreservation.convL_nil)) LexLeanPreservation.construct_pair)

def denote (a : Nat) (b : Nat) : LexLeanPreservation.Obs :=
  LexLeanPreservation.Rel (__fits_0 a b) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.nat)) (Coverage.RecRoots.wellFounded a b))

theorem root (a : Nat) (b : Nat) : LexLeanPreservation.RunConv __prog 0 [(LexLeanTarget.TargetSyntax.Value.nat a), (LexLeanTarget.TargetSyntax.Value.nat b)] (LexLeanPreservation.Rel (__fits_0 a b) ((LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat (LexLeanPreservation.encPair LexLeanTarget.TargetSyntax.Value.nat LexLeanTarget.TargetSyntax.Value.nat)) (Coverage.RecRoots.wellFounded a b))) :=
  LexLeanPreservation.run_of_funRel (__rel_0 a b)

end LexLeanPreserve.Ca8439f8ad54c9966573138a0891a81f4.R31
