module
import Compiler.TargetSemantics
#print axioms Compiler.TargetSemantics.Outcome
#print axioms Compiler.TargetSemantics.Outcomes
#print axioms Compiler.TargetSemantics.addSteps
#print axioms Compiler.TargetSemantics.bindAll
#print axioms Compiler.TargetSemantics.chargeResult
#print axioms Compiler.TargetSemantics.compareValue
#print axioms Compiler.TargetSemantics.compareValues
#print axioms Compiler.TargetSemantics.construct
#print axioms Compiler.TargetSemantics.depth
#print axioms Compiler.TargetSemantics.destruct
#print axioms Compiler.TargetSemantics.eval
#print axioms Compiler.TargetSemantics.evalArms
#print axioms Compiler.TargetSemantics.evalList
#print axioms Compiler.TargetSemantics.fromOrdering
#print axioms Compiler.TargetSemantics.fromStrings
#print axioms Compiler.TargetSemantics.intResult
#print axioms Compiler.TargetSemantics.lookup
#print axioms Compiler.TargetSemantics.natResult
#print axioms Compiler.TargetSemantics.orderBool
#print axioms Compiler.TargetSemantics.orderI16
#print axioms Compiler.TargetSemantics.orderI32
#print axioms Compiler.TargetSemantics.orderI64
#print axioms Compiler.TargetSemantics.orderI8
#print axioms Compiler.TargetSemantics.orderInt
#print axioms Compiler.TargetSemantics.orderNat
#print axioms Compiler.TargetSemantics.orderOf
#print axioms Compiler.TargetSemantics.orderString
#print axioms Compiler.TargetSemantics.orderU16
#print axioms Compiler.TargetSemantics.orderU32
#print axioms Compiler.TargetSemantics.orderU64
#print axioms Compiler.TargetSemantics.orderU8
#print axioms Compiler.TargetSemantics.primitive
#print axioms Compiler.TargetSemantics.run
#print axioms Compiler.TargetSemantics.sameOrder
#print axioms Compiler.TargetSemantics.toStrings
#print axioms Compiler.TargetSemantics.weight
#print axioms Compiler.TargetSemantics.weights
