module
import LexLeanTarget.TargetSemantics
#print axioms LexLeanTarget.TargetSemantics.Outcome
#print axioms LexLeanTarget.TargetSemantics.Outcomes
#print axioms LexLeanTarget.TargetSemantics.addSteps
#print axioms LexLeanTarget.TargetSemantics.bindAll
#print axioms LexLeanTarget.TargetSemantics.chargeResult
#print axioms LexLeanTarget.TargetSemantics.compareValue
#print axioms LexLeanTarget.TargetSemantics.compareValues
#print axioms LexLeanTarget.TargetSemantics.construct
#print axioms LexLeanTarget.TargetSemantics.depth
#print axioms LexLeanTarget.TargetSemantics.destruct
#print axioms LexLeanTarget.TargetSemantics.eval
#print axioms LexLeanTarget.TargetSemantics.evalArms
#print axioms LexLeanTarget.TargetSemantics.evalList
#print axioms LexLeanTarget.TargetSemantics.fromOrdering
#print axioms LexLeanTarget.TargetSemantics.fromStrings
#print axioms LexLeanTarget.TargetSemantics.intResult
#print axioms LexLeanTarget.TargetSemantics.lookup
#print axioms LexLeanTarget.TargetSemantics.natResult
#print axioms LexLeanTarget.TargetSemantics.orderBool
#print axioms LexLeanTarget.TargetSemantics.orderI16
#print axioms LexLeanTarget.TargetSemantics.orderI32
#print axioms LexLeanTarget.TargetSemantics.orderI64
#print axioms LexLeanTarget.TargetSemantics.orderI8
#print axioms LexLeanTarget.TargetSemantics.orderInt
#print axioms LexLeanTarget.TargetSemantics.orderNat
#print axioms LexLeanTarget.TargetSemantics.orderOf
#print axioms LexLeanTarget.TargetSemantics.orderString
#print axioms LexLeanTarget.TargetSemantics.orderU16
#print axioms LexLeanTarget.TargetSemantics.orderU32
#print axioms LexLeanTarget.TargetSemantics.orderU64
#print axioms LexLeanTarget.TargetSemantics.orderU8
#print axioms LexLeanTarget.TargetSemantics.primitive
#print axioms LexLeanTarget.TargetSemantics.run
#print axioms LexLeanTarget.TargetSemantics.sameOrder
#print axioms LexLeanTarget.TargetSemantics.toStrings
#print axioms LexLeanTarget.TargetSemantics.weight
#print axioms LexLeanTarget.TargetSemantics.weights
