module
import LexLeanTarget.BudgetOracle
#print axioms LexLeanTarget.BudgetOracle.Burn.apply
#print axioms LexLeanTarget.BudgetOracle.Burn.apply_progress
#print axioms LexLeanTarget.BudgetOracle.Burn.apply_sound
#print axioms LexLeanTarget.BudgetOracle.Burn.candidates
#print axioms LexLeanTarget.BudgetOracle.Burn.conclusion
#print axioms LexLeanTarget.BudgetOracle.Burn.guard
#print axioms LexLeanTarget.BudgetOracle.Drained.sound
#print axioms LexLeanTarget.BudgetOracle.Empty
#print axioms LexLeanTarget.BudgetOracle.Refund
#print axioms LexLeanTarget.BudgetOracle.Refund.Ledger
#print axioms LexLeanTarget.BudgetOracle.Refund.Run
#print axioms LexLeanTarget.BudgetOracle.Refund.Step
#print axioms LexLeanTarget.BudgetOracle.Refund.accept
#print axioms LexLeanTarget.BudgetOracle.Refund.accept_sound
#print axioms LexLeanTarget.BudgetOracle.Refund.account
#print axioms LexLeanTarget.BudgetOracle.Refund.answer
#print axioms LexLeanTarget.BudgetOracle.Refund.attempts
#print axioms LexLeanTarget.BudgetOracle.Refund.conclude
#print axioms LexLeanTarget.BudgetOracle.Refund.conclude_accept
#print axioms LexLeanTarget.BudgetOracle.Refund.conclude_sound
#print axioms LexLeanTarget.BudgetOracle.Refund.derivation
#print axioms LexLeanTarget.BudgetOracle.Refund.explained
#print axioms LexLeanTarget.BudgetOracle.Refund.extract
#print axioms LexLeanTarget.BudgetOracle.Refund.fire
#print axioms LexLeanTarget.BudgetOracle.Refund.fire_sound
#print axioms LexLeanTarget.BudgetOracle.Refund.firings_bounded
#print axioms LexLeanTarget.BudgetOracle.Refund.follow
#print axioms LexLeanTarget.BudgetOracle.Refund.iterations_bounded
#print axioms LexLeanTarget.BudgetOracle.Refund.next
#print axioms LexLeanTarget.BudgetOracle.Refund.next_sound
#print axioms LexLeanTarget.BudgetOracle.Refund.observe
#print axioms LexLeanTarget.BudgetOracle.Refund.replay
#print axioms LexLeanTarget.BudgetOracle.Refund.replay_fire
#print axioms LexLeanTarget.BudgetOracle.Refund.replay_sound
#print axioms LexLeanTarget.BudgetOracle.Refund.run
#print axioms LexLeanTarget.BudgetOracle.Refund.run_state
#print axioms LexLeanTarget.BudgetOracle.Refund.run_trace
#print axioms LexLeanTarget.BudgetOracle.Refund.saturate
#print axioms LexLeanTarget.BudgetOracle.Refund.saturate_derivation
#print axioms LexLeanTarget.BudgetOracle.Refund.select
#print axioms LexLeanTarget.BudgetOracle.Refund.start
#print axioms LexLeanTarget.BudgetOracle.Refund.step
#print axioms LexLeanTarget.BudgetOracle.Refund.step_count
#print axioms LexLeanTarget.BudgetOracle.Refund.step_fired
#print axioms LexLeanTarget.BudgetOracle.Refund.step_none
#print axioms LexLeanTarget.BudgetOracle.Refund.step_some
#print axioms LexLeanTarget.BudgetOracle.Refund.step_trace
#print axioms LexLeanTarget.BudgetOracle.Refund.verdict
#print axioms LexLeanTarget.BudgetOracle.Refund.verdict_sound
#print axioms LexLeanTarget.BudgetOracle.Remaining
#print axioms LexLeanTarget.BudgetOracle.Spend
#print axioms LexLeanTarget.BudgetOracle.Spend.Ledger
#print axioms LexLeanTarget.BudgetOracle.Spend.Run
#print axioms LexLeanTarget.BudgetOracle.Spend.Step
#print axioms LexLeanTarget.BudgetOracle.Spend.accept
#print axioms LexLeanTarget.BudgetOracle.Spend.accept_sound
#print axioms LexLeanTarget.BudgetOracle.Spend.account
#print axioms LexLeanTarget.BudgetOracle.Spend.answer
#print axioms LexLeanTarget.BudgetOracle.Spend.attempts
#print axioms LexLeanTarget.BudgetOracle.Spend.conclude
#print axioms LexLeanTarget.BudgetOracle.Spend.conclude_accept
#print axioms LexLeanTarget.BudgetOracle.Spend.conclude_sound
#print axioms LexLeanTarget.BudgetOracle.Spend.derivation
#print axioms LexLeanTarget.BudgetOracle.Spend.explained
#print axioms LexLeanTarget.BudgetOracle.Spend.extract
#print axioms LexLeanTarget.BudgetOracle.Spend.fire
#print axioms LexLeanTarget.BudgetOracle.Spend.fire_progress
#print axioms LexLeanTarget.BudgetOracle.Spend.fire_sound
#print axioms LexLeanTarget.BudgetOracle.Spend.firings_bounded
#print axioms LexLeanTarget.BudgetOracle.Spend.follow
#print axioms LexLeanTarget.BudgetOracle.Spend.iterations_bounded
#print axioms LexLeanTarget.BudgetOracle.Spend.next
#print axioms LexLeanTarget.BudgetOracle.Spend.next_progress
#print axioms LexLeanTarget.BudgetOracle.Spend.next_sound
#print axioms LexLeanTarget.BudgetOracle.Spend.observe
#print axioms LexLeanTarget.BudgetOracle.Spend.replay
#print axioms LexLeanTarget.BudgetOracle.Spend.replay_fire
#print axioms LexLeanTarget.BudgetOracle.Spend.replay_sound
#print axioms LexLeanTarget.BudgetOracle.Spend.run
#print axioms LexLeanTarget.BudgetOracle.Spend.run_state
#print axioms LexLeanTarget.BudgetOracle.Spend.run_trace
#print axioms LexLeanTarget.BudgetOracle.Spend.saturate
#print axioms LexLeanTarget.BudgetOracle.Spend.saturate_derivation
#print axioms LexLeanTarget.BudgetOracle.Spend.saturates
#print axioms LexLeanTarget.BudgetOracle.Spend.select
#print axioms LexLeanTarget.BudgetOracle.Spend.start
#print axioms LexLeanTarget.BudgetOracle.Spend.step
#print axioms LexLeanTarget.BudgetOracle.Spend.step_count
#print axioms LexLeanTarget.BudgetOracle.Spend.step_fired
#print axioms LexLeanTarget.BudgetOracle.Spend.step_none
#print axioms LexLeanTarget.BudgetOracle.Spend.step_some
#print axioms LexLeanTarget.BudgetOracle.Spend.step_trace
#print axioms LexLeanTarget.BudgetOracle.Spend.verdict
#print axioms LexLeanTarget.BudgetOracle.Spend.verdict_sound
#print axioms LexLeanTarget.BudgetOracle.Spent
#print axioms LexLeanTarget.BudgetOracle.Tick.apply
#print axioms LexLeanTarget.BudgetOracle.Tick.apply_progress
#print axioms LexLeanTarget.BudgetOracle.Tick.apply_sound
#print axioms LexLeanTarget.BudgetOracle.Tick.conclusion
#print axioms LexLeanTarget.BudgetOracle.Tick.guard
#print axioms LexLeanTarget.BudgetOracle.allowance_bound
#print axioms LexLeanTarget.BudgetOracle.burn_progress
#print axioms LexLeanTarget.BudgetOracle.burn_sound
#print axioms LexLeanTarget.BudgetOracle.emptyCheck
#print axioms LexLeanTarget.BudgetOracle.empty_sound
#print axioms LexLeanTarget.BudgetOracle.tick_progress
#print axioms LexLeanTarget.BudgetOracle.tick_sound
