import LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0
import LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore
import LexLeanPreservation.Compose
set_option autoImplicit false
set_option maxRecDepth 100000
set_option linter.unusedVariables false
namespace LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.Compose.RustCore

theorem __wt_0 : ∀ (__s : (Reasoning.Clinic.Vitals)), _root_.LexLeanPreservation.Rust.WT _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.program _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.krate _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.flags (_root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.__enc_0 __s) (.adt 0) :=
  fun __s => _root_.LexLeanPreservation.Rust.wt_adt rfl (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).temperature) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).heartRate) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).respiratoryRate) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).whiteCells) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).systolic) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).infection) _root_.LexLeanPreservation.Rust.wtl_nil))))))

theorem __wt_1 : ∀ (__s : (Reasoning.Clinic.Chart)), _root_.LexLeanPreservation.Rust.WT _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.program _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.krate _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.flags (_root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.__enc_1 __s) (.adt 1) :=
  fun __s => _root_.LexLeanPreservation.Rust.wt_adt rfl (_root_.LexLeanPreservation.Rust.wtl_cons (__wt_0 (__s).vitals) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).fever) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).tachycardia) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).tachypnea) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).leukocytosis) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).sirs) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).sepsis) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).shock) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat (__s).level) _root_.LexLeanPreservation.Rust.wtl_nil)))))))))

theorem __wt_2 : ∀ (__v : (Reasoning.Clinic.Triage.Step)), _root_.LexLeanPreservation.Rust.WT _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.program _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.krate _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.flags (_root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.__enc_2 __v) (.adt 2)
  | Reasoning.Clinic.Triage.Step.Fever => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Tachycardia => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Tachypnea => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Leukocytosis => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Sirs => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Sepsis => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Shock => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil
  | Reasoning.Clinic.Triage.Step.Escalate => _root_.LexLeanPreservation.Rust.wt_adt rfl _root_.LexLeanPreservation.Rust.wtl_nil

/-- The rendering of the root, invoked on the encoded arguments, realizes
the encoded source result. -/
theorem root (temperature : Nat) (heartRate : Nat) (respiratoryRate : Nat) (whiteCells : Nat) (systolic : Nat) (infection : Nat) (__e_hrep : _root_.LexLeanPreservation.Rust.RepresentableL [(_root_.LexLeanTarget.TargetSyntax.Value.nat temperature), (_root_.LexLeanTarget.TargetSyntax.Value.nat heartRate), (_root_.LexLeanTarget.TargetSyntax.Value.nat respiratoryRate), (_root_.LexLeanTarget.TargetSyntax.Value.nat whiteCells), (_root_.LexLeanTarget.TargetSyntax.Value.nat systolic), (_root_.LexLeanTarget.TargetSyntax.Value.nat infection)]) : ∃ __e_ro, _root_.LexLeanPreservation.Rust.RealizesFn Bool.true (_root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.denote temperature heartRate respiratoryRate whiteCells systolic infection) __e_ro ∧ _root_.LexLeanPreservation.Rust.RCI _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.krate (_root_.LexLeanPreservation.Rust.fnIdent 0) [(_root_.LexLeanTarget.TargetSyntax.Value.nat temperature), (_root_.LexLeanTarget.TargetSyntax.Value.nat heartRate), (_root_.LexLeanTarget.TargetSyntax.Value.nat respiratoryRate), (_root_.LexLeanTarget.TargetSyntax.Value.nat whiteCells), (_root_.LexLeanTarget.TargetSyntax.Value.nat systolic), (_root_.LexLeanTarget.TargetSyntax.Value.nat infection)] __e_ro :=
  _root_.LexLeanPreservation.Rust.compose (fun __e_n => _root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.RustCore.root __e_n 0) rfl (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat temperature) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat heartRate) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat respiratoryRate) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat whiteCells) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat systolic) (_root_.LexLeanPreservation.Rust.wtl_cons (_root_.LexLeanPreservation.Rust.wt_nat infection) _root_.LexLeanPreservation.Rust.wtl_nil)))))) rfl rfl (_root_.LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.root temperature heartRate respiratoryRate whiteCells systolic infection) (_root_.LexLeanPreservation.Rust.rel_ne_stuck _ _)

end LexLeanPreserve.C18ad574fdbd90d6971bb010291acf197.R0.Compose.RustCore
